### ISSUE TITLE
v3 ipv6 User and admins can't login only first admin

### ISSUE THREAD

**Issue by pierrehenrymuller** [nuxsmin/sysPass#1044]
**sysPass Version**
3.0 beta latest commit

**Describe the bug**
All accounts (users and admin) except the first admin can't connect to Syspass webui.

**To Reproduce**
Nginx + PHP-FPM 7.2 + MariaDB 10.1
Nginx configure to listen ipv4 and ipv6 with 
`listen			[::]:443	   default_server ipv6only=off ssl http2;`
Nginx record ipv4 in a ipv6 format like ::ffff:192.X.X.X

**Event log**
`[23-Sep-2018 14:45:48 Europe/Paris] [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
[23-Sep-2018 14:45:48 Europe/Paris] [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT id, userId 
            FROM Track 
            WHERE `time` >= ? 
            AND (ipv4 = ? OR ipv6 = ?) 
            AND `source` = ?;
[23-Sep-2018 14:45:48 Europe/Paris] [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT U.id,
            U.name,
            U.userGroupId,
            UG.name AS userGroupName,
            U.login,
            U.ssoLogin,
            U.email,
            U.notes,
            U.loginCount,
            U.userProfileId,
            U.lastLogin,
            U.lastUpdate,
            U.lastUpdateMPass,
            U.preferences,
            U.pass,
            U.hashSalt,
            U.mPass,
            U.mKey,            
            U.isAdminApp,
            U.isAdminAcc,
            U.isLdap,
            U.isDisabled,
            U.isChangePass,
            U.isChangedPass,
            U.isMigrate
            FROM User U
            INNER JOIN UserGroup UG ON U.userGroupId = UG.id
            WHERE U.login = ? OR U.ssoLogin = ? LIMIT 1;
[23-Sep-2018 14:45:48 Europe/Paris] [DEBUG] [SP\Http\Request::analyzeEncrypted] No RSA encrypted data from request
[23-Sep-2018 14:45:48 Europe/Paris] [DEBUG] [SP\Http\Request::analyzeEncrypted] No RSA encrypted data from request
[23-Sep-2018 14:45:48 Europe/Paris] [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] database.query;SELECT parameter, `value` FROM Config WHERE parameter = ? LIMIT 1;
[23-Sep-2018 14:45:48 Europe/Paris] [EXCEPTION] [N/A] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'ipv4' cannot be null
#0 /XXXX/docroot/lib/SP/Storage/Database/Database.php(248): PDOStatement->execute()
#1 /XXXX/docroot/lib/SP/Storage/Database/Database.php(176): SP\Storage\Database\Database->prepareQueryData(Object(SP\Storage\Database\QueryData))
#2 /XXXX/docroot/lib/SP/Repositories/Track/TrackRepository.php(65): SP\Storage\Database\Database->doQuery(Object(SP\Storage\Database\QueryData))
#3 /XXXX/docroot/lib/SP/Services/Track/TrackService.php(176): SP\Repositories\Track\TrackRepository->add(Object(SP\Repositories\Track\TrackRequest))
#4 /XXXX/docroot/lib/SP/Services/Auth/LoginService.php(184): SP\Services\Track\TrackService->add(Object(SP\Repositories\Track\TrackRequest))
#5 /XXXX/docroot/lib/SP/Services/Auth/LoginService.php(325): SP\Services\Auth\LoginService->addTracking()
#6 /XXXX/docroot/lib/SP/Services/Auth/LoginService.php(168): SP\Services\Auth\LoginService->loadMasterPass()
#7 /XXXX/docroot/app/modules/web/Controllers/LoginController.php(69): SP\Services\Auth\LoginService->doLogin()
#8 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#9 /XXXX/docroot/lib/SP/Bootstrap.php(222): call_user_func_array(Array, Array)
#10 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#11 /XXXX/docroot/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#12 /XXXX/docroot/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#13 /XXXX/docroot/lib/SP/Bootstrap.php(432): Klein\Klein->dispatch(Object(Klein\Request))
#14 /XXXX/docroot/lib/Base.php(72): SP\Bootstrap::run(Object(DI\Container))
#15 /XXXX/docroot/index.php(28): require('/home/hosting/d...')
#16 {main}
[23-Sep-2018 14:45:48 Europe/Paris] [EXCEPTION] [N/A] Internal error
#0 /XXXX/docroot/lib/SP/Services/Auth/LoginService.php(325): SP\Services\Auth\LoginService->addTracking()
#1 /XXXX/docroot/lib/SP/Services/Auth/LoginService.php(168): SP\Services\Auth\LoginService->loadMasterPass()
#2 /XXXX/docroot/app/modules/web/Controllers/LoginController.php(69): SP\Services\Auth\LoginService->doLogin()
#3 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#4 /XXXX/docroot/lib/SP/Bootstrap.php(222): call_user_func_array(Array, Array)
#5 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /XXXX/docroot/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /XXXX/docroot/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#8 /XXXX/docroot/lib/SP/Bootstrap.php(432): Klein\Klein->dispatch(Object(Klein\Request))
#9 /XXXX/docroot/lib/Base.php(72): SP\Bootstrap::run(Object(DI\Container))
#10 /XXXX/docroot/index.php(28): require('/home/hosting/d...')
#11 {main}
[23-Sep-2018 14:46:00 Europe/Paris] [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
[23-Sep-2018 14:46:00 Europe/Paris] [DEBUG] [SP\Config\Config::initialize] Config loaded
[23-Sep-2018 14:46:00 Europe/Paris] [DEBUG] [SP\Bootstrap::run] ------------
[23-Sep-2018 14:46:00 Europe/Paris] [DEBUG] [SP\Bootstrap::run] Boostrap:web
[23-Sep-2018 14:46:00 Europe/Paris] [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
[23-Sep-2018 14:46:00 Europe/Paris] [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
[23-Sep-2018 14:46:00 Europe/Paris] [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
[23-Sep-2018 14:46:00 Europe/Paris] [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
[23-Sep-2018 14:46:00 Europe/Paris] [INFO] [SP\Core\UI\Theme::saveIcons] Saved icons cache
[23-Sep-2018 14:46:00 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
[23-Sep-2018 14:46:00 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
[23-Sep-2018 14:46:00 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\SyslogHandler
[23-Sep-2018 14:46:00 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
[23-Sep-2018 14:46:00 Europe/Paris] [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\LoginController::loginAction::Array
(
)`

**Platform (please complete the following information):**
 - OS: Debian
 - OS Version : 9
 - Browser Firefox and Chromium

**Additional context**
In the table Track, ipv4 is NOT NULL but ipv6 is DEFAULT NULL. Simply patch Track with 
`ALTER TABLE Track MODIFY ipv4 binary(4) DEFAULT NULL;`
Resolve the problem and user can connect to webui.

In a ipv6 only network like reverse proxy in front with ipv4 and ipv6, who reverse ipv6 only web server, the same thing can append.

**Comment by nuxsmin** [comment]
Hello, it seems that Nginx proxy does not provide the client IP address so sysPass is unable to get  it for tracking system.

Tracking system has been designed to avoid unwanted users that would try to get access by using brute force attacks, thus allowing to store null IP v4 / V6 records will disable this kind of protection system.

Thanks for the feedback!

Kind regards

**Comment by pierrehenrymuller** [comment]
Hi,
Nginx give correct informations to PHP in SERVER variables 
`[SERVER_PORT] => 443
    [SERVER_ADDR] => ::ffff:185.X.X.X
    [REMOTE_USER] => 
    [REMOTE_PORT] => 52166
    [REMOTE_ADDR] => ::ffff:185.X.X.X`
But with dual stack enabled in the same listen declaration in Nginx, IPv4 are packaged in IPv6 with IPv4 prefix.
This is normal.

**Comment by nuxsmin** [comment]
Hi, this behavior was fixed in latest commit by ensuring that either IPv4 or IPv6 are set on PHP side.

Regards
