### ISSUE TITLE
v3 API manage groups and add assign account to a main group

### ISSUE THREAD

**Issue by pierrehenrymuller** [nuxsmin/sysPass#1054]
Hi,

With the plugin lookup for Ansible, we can create and get password, it's awesome.
But now when a account is created with API I can't assign in API request the main group of the user login.

Our goal is to have an API access to create / delete account password. Then customers have their credentials to only get password. This be done with login groups and profile.
But I don't see any link between Account Client and Login Group.
I would like that when an account is created, I can put this account into a main group that have the same name of Account client. 
This way as soon as the ansible user with API access create an account, then he is immediately placed in the right group and users with access to this group can see that their passwords.

It's a lake for this feature or I don't see the link between Account Client and login Group?

With what I see in the API code, there is a class missing for the management of groups of people and in the Account->create class to have a field for the id of the "main group".

**Comment by nuxsmin** [comment]
Hi, 

If I understood well, you would like to have the ability to create user groups from the API, so in this way you can assign each client's account to its own user group, am I right?

If so, it could be done. For adding some context, some items like users, groups and profiles aren't implemented in API because they are less common to create/modify through this way, but I would like to implemented a more complete API since it would be useful for any kind of automated task.

Kind regards.

**Comment by pierrehenrymuller** [comment]
Hi,
ok, can you look at Gitter, I would like to give you informations in private, thanks.

**Comment by nuxsmin** [comment]
Hi, this feature has been implemented in latest commit.

**Comment by pierrehenrymuller** [comment]
Hi,

Thank you very much for this @nuxsmin appreciate that.

I'm doing modifications in the ansible lookup plugin and when I pass userGroupId to account/create I get : 
`AccountCreate() got an unexpected keyword argument 'userGroupId'`

It's seem the userGroupId can't be given to Account Create.

In https://github.com/nuxsmin/sysPass/blob/513ab01cff9018ce935613c9ba32ac648c377b5b/app/modules/api/Controllers/AccountController.php
in createAction function
`$accountRequest->userGroupId = $this->context->getUserData()->getUserGroupId();`
need to be 
`$accountRequest->userGroupId = $this->apiService->getParamInt('userGroupId');`
or with a default value
```
diff --git a/app/modules/api/Controllers/AccountController.php b/app/modules/api/Controllers/AccountController.php
index 62022094..c549d410 100644
--- a/app/modules/api/Controllers/AccountController.php
+++ b/app/modules/api/Controllers/AccountController.php
@@ -168,8 +168,10 @@ final class AccountController extends ControllerBase
             $accountRequest->isPrivateGroup = $this->apiService->getParamInt('privateGroup');
             $accountRequest->passDateChange = $this->apiService->getParamInt('expireDate');
             $accountRequest->parentId = $this->apiService->getParamInt('parentId');
-            $accountRequest->userGroupId = $this->context->getUserData()->getUserGroupId();
+            $accountRequest->userGroupId = ( $this->apiService->getParamInt('userGroupId') ?
+                                            $this->apiService->getParamInt('userGroupId') :
+                                            $this->context->getUserData()->getUserGroupId());
             $accountRequest->tags = array_map('intval', $this->apiService->getParamArray('tagsId', false, []));
```
But with this modification I already have the same error, I had search in lib/SP/Services/Account where the verification of args are made but without success.
Where I can find the definition of args verification? I can make you a merge request when I tested this.

Thanks in advance

**Comment by nuxsmin** [comment]
Hi, the error message `AccountCreate() got an unexpected keyword argument 'userGroupId' ` does not come from sysPass. 

The change you made to account's API is fine. A quick review to the code doesn't make me think about any more changes.

Regards

**Comment by pierrehenrymuller** [comment]
You're right, sorry for that.
The patch I propose will be integrated into the next release?

I suggest to ajust test class with the new userGroupId parameter (without, with valid and with not existing group).
Thanks

**Comment by pierrehenrymuller** [comment]
Hi,
I have a regression on account/delete in API since the last commit in devel-0.3
When I call this action they make an 500 error in PHP.

This is the log in php error : 
```
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Config\Config::initialize] Config loaded
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Bootstrap::run] ------------
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Bootstrap::run] Boostrap:api
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
[10-Oct-2018 11:53:58 Europe/Paris] [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Modules\Api\Init::initialize] initialize
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Api\Controllers\AccountController::searchAction
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Config\Config::initialize] Config loaded
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Bootstrap::run] ------------
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Bootstrap::run] Boostrap:api
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
[10-Oct-2018 11:53:58 Europe/Paris] [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Modules\Api\Init::initialize] initialize
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
[10-Oct-2018 11:53:58 Europe/Paris] [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Api\Controllers\AccountController::viewPassAction
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] show.account.pass;Password viewed;Name : SYSPASS TEST
Client : TEST
ID : 94
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Config\Config::initialize] Config loaded
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Bootstrap::run] ------------
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Bootstrap::run] Boostrap:api
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
[10-Oct-2018 11:53:59 Europe/Paris] [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Modules\Api\Init::initialize] initialize
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Api\Controllers\AccountController::searchAction
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Config\Config::initialize] Config loaded
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Bootstrap::run] ------------
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Bootstrap::run] Boostrap:api
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
[10-Oct-2018 11:53:59 Europe/Paris] [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Modules\Api\Init::initialize] initialize
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
[10-Oct-2018 11:53:59 Europe/Paris] [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Api\Controllers\AccountController::deleteAction
[10-Oct-2018 11:53:59 Europe/Paris] [EXCEPTION] [N/A] Internal error
#0 /XXXX/docroot/lib/SP/Services/Api/ApiService.php(103): SP\Services\AuthToken\AuthTokenService->getTokenByToken(6, 'ffb9285e590b480...')
#1 /XXXX/docroot/app/modules/api/Controllers/ControllerBase.php(130): SP\Services\Api\ApiService->setup(6)
#2 /XXXX/docroot/app/modules/api/Controllers/AccountController.php(301): SP\Modules\Api\Controllers\ControllerBase->setupApi(6)
#3 [internal function]: SP\Modules\Api\Controllers\AccountController->deleteAction()
#4 /XXXX/docroot/lib/SP/Bootstrap.php(174): call_user_func(Array)
#5 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /XXXX/docroot/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /XXXX/docroot/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#8 /XXXX/docroot/lib/SP/Bootstrap.php(438): Klein\Klein->dispatch(Object(Klein\Request))
#9 /XXXX/docroot/lib/Base.php(72): SP\Bootstrap::run(Object(DI\Container))
#10 /XXXX/docroot/api.php(28): require('/home/hosting/d...')
#11 {main}
```
The entry with id 94 is correctly created with api account/create and visible in database.

This is the json params gived in the api delete call
```
{'params': {'authToken': 'XXXX', 'tokenPass': 'XXXX', 'id': 94}, 'jsonrpc': '2.0', 'method': 'account/delete', 'id': 2}
```
I have look last commit changes but I don't see anything convincing.
But when I rollback with sources and database of previous version, all work fine.

**Comment by pierrehenrymuller** [comment]
ok I found the problem, the Account Delete right have been removed, when I add the right it's work.
But If possible to not make a fatal error in PHP when the right is not good will be better to investigate and not stop PHP work.
Actually without right to delete I have this in error entry of json :  
```
{u'message': u'Internal error', u'code': 0, u'data': None}
```
It will better to have message: 'You have not the right to remove account'

**Comment by nuxsmin** [comment]
Hi, this is the intended behavior, since if you're using a valid token and you try to use a non granted action, for security reasons, it will throw an internal error message instead of `you don't have permission` which will expose to which actions has the token permission for.  It's a kind of way to not let an attacker to list the granted actions for a valid token.

Regards
