### ISSUE TITLE
Cant install syspass 3.0

### ISSUE THREAD

**Issue by M1k13** [nuxsmin/sysPass#1070]
Hey,

When i load the page I already get 2 red block with the warning:

1. An error occured Not found (error)
2. Error while getting syspass config, please try again or try check web log

I named the database 'syspass' just like it is named by default in the install screen. I have no clue what i'm doing wrong. When i try to press install it keeps report those 2 msges.

2018-10-15 08:16:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-10-15 08:16:03 [DEBUG] [SP\Config\Config::initialize] Config loaded
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::run] ------------
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-10-15 08:16:03 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-10-15 08:16:03 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-10-15 08:16:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_GB.utf8
2018-10-15 08:16:03 [INFO] [SP\Core\UI\Theme::saveIcons] Saved icons cache
2018-10-15 08:16:03 [EXCEPTION] [N/A] Response is locked
#0 /var/www/html/syspass/vendor/klein/klein/src/Klein/AbstractResponse.php(211): Klein\AbstractResponse->requireUnlocked()
#1 /var/www/html/syspass/vendor/klein/klein/src/Klein/AbstractResponse.php(523): Klein\AbstractResponse->code(302)
#2 /var/www/html/syspass/app/modules/web/Init.php(181): Klein\AbstractResponse->redirect('index.php?r=upg...')
#3 /var/www/html/syspass/lib/SP/Bootstrap.php(216): SP\Modules\Web\Init->initialize('index')
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/syspass/lib/SP/Bootstrap.php(432): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/syspass/lib/Base.php(72): SP\Bootstrap::run(Object(DI\Container))
#9 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#10 {main}
2018-10-15 08:16:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-10-15 08:16:03 [DEBUG] [SP\Config\Config::initialize] Config loaded
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::run] ------------
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-10-15 08:16:03 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-10-15 08:16:03 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-10-15 08:16:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_GB.utf8
2018-10-15 08:16:03 [INFO] [SP\Core\UI\Theme::saveIcons] Saved icons cache
2018-10-15 08:16:03 [DEBUG] [SP\Core\Context\SessionContext::close] Session closed
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\InstallController::indexAction::Array
(
)

2018-10-15 08:16:03 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-10-15 08:16:03 [DEBUG] [SP\Core\Context\SessionContext::setContextKey] Session locked; key=pubkey
2018-10-15 08:16:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-10-15 08:16:03 [DEBUG] [SP\Config\Config::initialize] Config loaded
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::run] ------------
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-10-15 08:16:03 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-10-15 08:16:03 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-10-15 08:16:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_GB.utf8
2018-10-15 08:16:03 [INFO] [SP\Core\UI\Theme::saveIcons] Saved icons cache
2018-10-15 08:16:03 [DEBUG] [SP\Core\Context\SessionContext::close] Session closed
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ResourceController::cssAction::Array
(
)

2018-10-15 08:16:03 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-10-15 08:16:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-10-15 08:16:03 [DEBUG] [SP\Config\Config::initialize] Config loaded
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::run] ------------
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-10-15 08:16:03 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-10-15 08:16:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-10-15 08:16:03 [DEBUG] [SP\Config\Config::initialize] Config loaded
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::run] ------------
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-10-15 08:16:03 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-10-15 08:16:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-10-15 08:16:03 [DEBUG] [SP\Config\Config::initialize] Config loaded
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::run] ------------
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-10-15 08:16:03 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-10-15 08:16:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-10-15 08:16:03 [DEBUG] [SP\Config\Config::initialize] Config loaded
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::run] ------------
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-10-15 08:16:03 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-10-15 08:16:03 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-10-15 08:16:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_GB.utf8
2018-10-15 08:16:03 [INFO] [SP\Core\UI\Theme::saveIcons] Saved icons cache
2018-10-15 08:16:03 [DEBUG] [SP\Core\Context\SessionContext::close] Session closed
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ResourceController::cssAction::Array
(
)

2018-10-15 08:16:03 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-10-15 08:16:03 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-10-15 08:16:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_GB.utf8
2018-10-15 08:16:03 [INFO] [SP\Core\UI\Theme::saveIcons] Saved icons cache
2018-10-15 08:16:03 [DEBUG] [SP\Core\Context\SessionContext::close] Session closed
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ResourceController::jsAction::Array
(
)

2018-10-15 08:16:03 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-10-15 08:16:03 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-10-15 08:16:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_GB.utf8
2018-10-15 08:16:03 [INFO] [SP\Core\UI\Theme::saveIcons] Saved icons cache
2018-10-15 08:16:03 [DEBUG] [SP\Core\Context\SessionContext::close] Session closed
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ResourceController::jsAction::Array
(
)

2018-10-15 08:16:03 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-10-15 08:16:03 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-10-15 08:16:03 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_GB.utf8
2018-10-15 08:16:03 [INFO] [SP\Core\UI\Theme::saveIcons] Saved icons cache
2018-10-15 08:16:03 [DEBUG] [SP\Core\Context\SessionContext::close] Session closed
2018-10-15 08:16:03 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ResourceController::jsAction::Array
(
)

2018-10-15 08:16:03 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache

**Comment by M1k13** [comment]
Hey!

Yeah it works perfect now!
I had to edit the httpd path from /var/www/html to /var/www/html/syspass or just place the files inside html it self.

Now I want to try to get syspass3.0 working with out the ius and composer, so I can only use software-collections, epel and the base(orders from the chief)

Kind regards,
