### ISSUE TITLE
Upgrade form dev3.0 to 3.0 branch LDAP login error

### ISSUE THREAD

**Issue by odavis1** [nuxsmin/sysPass#1095]
**sysPass Version**
3.0-beta (300.18110601)
SERVER_VERSION : 5.7.23-0ubuntu0.18.04.1 
CLIENT_VERSION : mysqlnd 5.0.12-dev 

**Describe the bug**
After Moving from branch dev3.0 to 3.0 when trying to log in with LDAP user or internal user I recieve a "Internal Error" at log in. I turn LDAP off via the config.xml and I can log in with the local user. I would like to get this working with LDAP users on the newest version.

**To Reproduce**
have version 3.0-beta (300.18101101) installed
Configure LDAP
Git fetch
Git checkout -b 3.0
git reset --hard origin/3.0
service apache2 stop and start
Try and log in with LDAP user

**Expected behavior**
I expect the LDAP user to log into the application 

**Screenshots**

**Event log**
2018-11-08 10:26:42 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-08 10:26:42 [EXCEPTION] [N/A] Error while searching the group RDN
#0 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/Ldap.php(131): SP\Providers\Auth\Ldap\LdapActions->searchGroupsDn('(objectCategory...')
#1 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapMsAds.php(113): SP\Providers\Auth\Ldap\Ldap->getGroupDn()
#2 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapAuth.php(173): SP\Providers\Auth\Ldap\LdapMsAds->isUserInGroup('CN=User Name...', Array)
#3 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapAuth.php(119): SP\Providers\Auth\Ldap\LdapAuth->getAttributes('user1')
#4 /var/www/html/syspass/lib/SP/Providers/Auth/AuthProvider.php(133): SP\Providers\Auth\Ldap\LdapAuth->authenticate(Object(SP\DataModel\UserLoginData))
#5 /var/www/html/syspass/lib/SP/Providers/Auth/AuthProvider.php(90): SP\Providers\Auth\AuthProvider->authLdap()
#6 /var/www/html/syspass/lib/SP/Services/Auth/LoginService.php(145): SP\Providers\Auth\AuthProvider->doAuth(Object(SP\DataModel\UserLoginData))
#7 /var/www/html/syspass/app/modules/web/Controllers/LoginController.php(61): SP\Services\Auth\LoginService->doLogin()
#8 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#9 /var/www/html/syspass/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#10 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#12 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#13 /var/www/html/syspass/lib/SP/Bootstrap.php(463): Klein\Klein->dispatch(Object(Klein\Request))
#14 /var/www/html/syspass/lib/Base.php(72): SP\Bootstrap::run(Object(DI\Container))
#15 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#16 {main}
2018-11-08 10:26:42 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] login.auth.ldap;Internal error;Type : authLdap
LDAP Server :
User : user1
2018-11-08 10:26:42 [EXCEPTION] [N/A] Internal error
#0 /var/www/html/syspass/lib/SP/Services/Auth/LoginService.php(151): SP\Services\Auth\LoginService->authLdap(Object(SP\Providers\Auth\Ldap\LdapAuthData))
#1 /var/www/html/syspass/app/modules/web/Controllers/LoginController.php(61): SP\Services\Auth\LoginService->doLogin()
#2 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#3 /var/www/html/syspass/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/syspass/lib/SP/Bootstrap.php(463): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/syspass/lib/Base.php(72): SP\Bootstrap::run(Object(DI\Container))
#9 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#10 {main}
2018-11-08 10:26:42 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] exception;Internal error

**Platform (please complete the following information):**
SERVER_VERSION : 5.7.23-0ubuntu0.18.04.1

**Additional context**
Within the logs  the entry LDAP server is blank?? however I can confirm traffic was sent to the LDAP server after doing a TCPdump while logging in.
If I roll back the version I can log in with the LDAP user.
I also turned off LDAP logged in and updated the LDAP query account details to ensure it has the creds. Still did not work.

**Comment by nuxsmin** [comment]
Hello, I've checked out every release (Docker images) using an LDAP server and they worked fine, moreover there weren't any changes on LDAP auth.

Please let me find out what could be causing this issue.

Regards

PS: great point on changing the branch ;)

**Comment by odavis1** [comment]
Hello! 
I have removed the current syspass directory and did a fresh git clone straight onto 3.0 Branch, completed the initial configuration of username/passwords/etc... I configured LDAP and used the test button, the connection all worked OK. 
Tried logging on with a LDAP user and it failed - [EXCEPTION] [N/A] User does not exist
Once I imported the users I was back with the same problem - [EXCEPTION] [N/A] Error while searching the group RDN

Is the same updates applied to the 3.0dev branch at the moment? Will there be a tested path to move from dev3.0 to 3.0 in the future?

![image](https://user-images.githubusercontent.com/44058649/48268506-11514480-e42d-11e8-852f-12a6d51d6b61.png)
![image](https://user-images.githubusercontent.com/44058649/48268540-275f0500-e42d-11e8-8b78-09e3f5c1f493.png)

Kind Regards

**Comment by odavis1** [comment]
Also If it helps im currently running Dev03.0 3.0-beta (300.18101101) from commit and it works fine: 

bcadmin@avmmdcs02:/var/www/html/syspass$ git log
commit e322563a66766886b2010c8e7e303c745b229d7e (HEAD -> devel-3.0, origin/devel-3.0)
Author: nuxsmin <nuxsmin@syspass.org>
Date:   Tue Oct 16 01:13:38 2018 +0200
    * [ADD] Added In-App notifications polling. It will show up a browser notification when there are pending notifications
    * [MOD] Improved Javascript error handling
    * [MOD] Code refactoring
    Signed-off-by: nuxsmin <nuxsmin@syspass.org>

However when I upgrade to the latest of Dev3.0 Branch it produces the same error.

**Comment by nuxsmin** [comment]
I forgot to mention that there weren't any changes from devel-3.0 to 3.0 because it was done using the git rebase way, so it was switched over as it was and then, a few new commits were pushed to 3.0

Regards

**Comment by nuxsmin** [comment]
Hello, this issue has been fixed in latest commits.

Regards.
