### ISSUE TITLE
Another one with database access denied

### ISSUE THREAD

**Issue by alexseys** [nuxsmin/sysPass#1101]
**sysPass Version**
Installation 3.0-rc1

**Describe the question**
Unable to connect to DB
Error 1045: SQLSTATE[HY000] [1045] Access denied for user 'sysPass'@'localhost' (using password: YES)

Getting this error after downloading new version:
git clone https://github.com/nuxsmin/sysPass.git -b 3.0

Trying to run this on same server that i had master branch running yesterday, #1099 
I tried redoing the user, removed database, recreated user and database, used hosting mode no luck. :(

Also config.xml had <filesAllowedExts/> and another one with <.....Mime/> that were throwing string vs array errors.

**Screenshots**
![screen shot 2018-11-13 at 5 24 32 pm](https://user-images.githubusercontent.com/133041/48447235-5c3ec500-e769-11e8-9b39-4c270a5637c5.png)

**Platform (please complete the following information):**
 OS: Centos 7
OS Version: 3.10.0-862.14.4.el7.x86_64
Browser: Firefox, Chrome, Safari

**Additional context**

2018-11-13 22:26:28 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-13 22:26:28 [DEBUG] [SP\Http\Request::analyzeEncrypted] No RSA encrypted data from request
2018-11-13 22:26:29 [DEBUG] [SP\Http\Request::analyzeEncrypted] No RSA encrypted data from request
2018-11-13 22:26:29 [DEBUG] [SP\Http\Request::analyzeEncrypted] No RSA encrypted data from request
2018-11-13 22:26:29 [EXCEPTION] [N/A] Unable to connect to DB
#0 /var/www/html/lib/SP/Services/Install/MySQL.php(94): SP\Storage\Database\MySQLHandler->getConnectionSimple()
#1 /var/www/html/lib/SP/Services/Install/MySQL.php(72): SP\Services\Install\MySQL->connectDatabase()
#2 /var/www/html/lib/SP/Services/Install/Installer.php(266): SP\Services\Install\MySQL->__construct(Object(SP\Services\Install\InstallData), Object(SP\Config\ConfigData))
#3 /var/www/html/lib/SP/Services/Install/Installer.php(182): SP\Services\Install\Installer->setupDb()
#4 /var/www/html/lib/SP/Services/Install/Installer.php(94): SP\Services\Install\Installer->install()
#5 /var/www/html/app/modules/web/Controllers/InstallController.php(87): SP\Services\Install\Installer->run(Object(SP\Services\Install\InstallData))
#6 [internal function]: SP\Modules\Web\Controllers\InstallController->installAction()
#7 /var/www/html/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#8 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/html/lib/SP/Bootstrap.php(466): Klein\Klein->dispatch(Object(Klein\Request))
#12 /var/www/html/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#13 /var/www/html/index.php(28): require('/var/www/html/l...')
#14 {main}
2018-11-13 22:26:29 [EXCEPTION] [N/A] (P) SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)
#0 /var/www/html/lib/SP/Storage/Database/MySQLHandler.php(173): PDO->__construct('mysql:charset=u...', 'root', 'Kufj/Nh+gJBC4m0...', Array)
#1 /var/www/html/lib/SP/Services/Install/MySQL.php(94): SP\Storage\Database\MySQLHandler->getConnectionSimple()
#2 /var/www/html/lib/SP/Services/Install/MySQL.php(72): SP\Services\Install\MySQL->connectDatabase()
#3 /var/www/html/lib/SP/Services/Install/Installer.php(266): SP\Services\Install\MySQL->__construct(Object(SP\Services\Install\InstallData), Object(SP\Config\ConfigData))
#4 /var/www/html/lib/SP/Services/Install/Installer.php(182): SP\Services\Install\Installer->setupDb()
#5 /var/www/html/lib/SP/Services/Install/Installer.php(94): SP\Services\Install\Installer->install()
#6 /var/www/html/app/modules/web/Controllers/InstallController.php(87): SP\Services\Install\Installer->run(Object(SP\Services\Install\InstallData))
#7 [internal function]: SP\Modules\Web\Controllers\InstallController->installAction()
#8 /var/www/html/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#9 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#12 /var/www/html/lib/SP/Bootstrap.php(466): Klein\Klein->dispatch(Object(Klein\Request))
#13 /var/www/html/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#14 /var/www/html/index.php(28): require('/var/www/html/l...')
#15 {main}
2018-11-13 22:26:29 [EXCEPTION] [N/A] Unable to connect to DB
#0 /var/www/html/lib/SP/Services/Install/MySQL.php(72): SP\Services\Install\MySQL->connectDatabase()
#1 /var/www/html/lib/SP/Services/Install/Installer.php(266): SP\Services\Install\MySQL->__construct(Object(SP\Services\Install\InstallData), Object(SP\Config\ConfigData))
#2 /var/www/html/lib/SP/Services/Install/Installer.php(182): SP\Services\Install\Installer->setupDb()
#3 /var/www/html/lib/SP/Services/Install/Installer.php(94): SP\Services\Install\Installer->install()
#4 /var/www/html/app/modules/web/Controllers/InstallController.php(87): SP\Services\Install\Installer->run(Object(SP\Services\Install\InstallData))
#5 [internal function]: SP\Modules\Web\Controllers\InstallController->installAction()
#6 /var/www/html/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#7 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/lib/SP/Bootstrap.php(466): Klein\Klein->dispatch(Object(Klein\Request))
#11 /var/www/html/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#12 /var/www/html/index.php(28): require('/var/www/html/l...')
#13 {main}
2018-11-13 22:26:29 [EXCEPTION] [N/A] (P) Unable to connect to DB
#0 /var/www/html/lib/SP/Services/Install/MySQL.php(94): SP\Storage\Database\MySQLHandler->getConnectionSimple()
#1 /var/www/html/lib/SP/Services/Install/MySQL.php(72): SP\Services\Install\MySQL->connectDatabase()
#2 /var/www/html/lib/SP/Services/Install/Installer.php(266): SP\Services\Install\MySQL->__construct(Object(SP\Services\Install\InstallData), Object(SP\Config\ConfigData))
#3 /var/www/html/lib/SP/Services/Install/Installer.php(182): SP\Services\Install\Installer->setupDb()
#4 /var/www/html/lib/SP/Services/Install/Installer.php(94): SP\Services\Install\Installer->install()
#5 /var/www/html/app/modules/web/Controllers/InstallController.php(87): SP\Services\Install\Installer->run(Object(SP\Services\Install\InstallData))
#6 [internal function]: SP\Modules\Web\Controllers\InstallController->installAction()
#7 /var/www/html/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#8 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/html/lib/SP/Bootstrap.php(466): Klein\Klein->dispatch(Object(Klein\Request))
#12 /var/www/html/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#13 /var/www/html/index.php(28): require('/var/www/html/l...')
#14 {main}

**Comment by nuxsmin** [comment]
Hello, it seems a database permissions issue?

> Also config.xml had filesAllowedExts/ and another one with <.....Mime/> that were throwing string vs array errors.

Right, I've solved this silly issue in latest commit.

Thanks for the feedback!

Regards
