### ISSUE TITLE
v3.0 git pull and all api request are in maintenance mode

### ISSUE THREAD

**Issue by pierrehenrymuller** [nuxsmin/sysPass#1108]
Hello,
I have upgraded my test syspass installation from git from 
```
commit e322563a66766886b2010c8e7e303c745b229d7e
Author: nuxsmin <nuxsmin@syspass.org>
Date:   Tue Oct 16 01:13:38 2018 +0200

    * [ADD] Added In-App notifications polling. It will show up a browser notification when there are pending notifications
    * [MOD] Improved Javascript error handling
    * [MOD] Code refactoring
```
to latest devel-3.0 and when I have see 3.0 branch I have also switch to this without changes.

For all request I made to api.php I got : 
`{u'message': u'Maintenance mode', u'code': 0, u'data': None}`

There is log from php error : 
```
[18-Nov-2018 18:32:52 Europe/Paris] [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
[18-Nov-2018 18:32:52 Europe/Paris] [DEBUG] [SP\Config\Config::initialize] Config cache loaded
[18-Nov-2018 18:32:52 Europe/Paris] [DEBUG] [SP\Bootstrap::run] ------------
[18-Nov-2018 18:32:52 Europe/Paris] [DEBUG] [SP\Bootstrap::run] Boostrap:api
[18-Nov-2018 18:32:52 Europe/Paris] [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
[18-Nov-2018 18:32:52 Europe/Paris] [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
[18-Nov-2018 18:32:52 Europe/Paris] [DEBUG] [SP\Modules\Api\Init::initialize] initialize
[18-Nov-2018 18:32:52 Europe/Paris] [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
[18-Nov-2018 18:32:52 Europe/Paris] [EXCEPTION] [N/A] Maintenance mode
#0 /home/hosting/domains/corp/vault.corp.digdeo.fr/docroot/lib/SP/Bootstrap.php(171): SP\Modules\Api\Init->initialize('account')
#1 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#2 /home/hosting/domains/corp/vault.corp.digdeo.fr/docroot/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#3 /home/hosting/domains/corp/vault.corp.digdeo.fr/docroot/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#4 /home/hosting/domains/corp/vault.corp.digdeo.fr/docroot/lib/SP/Bootstrap.php(456): Klein\Klein->dispatch(Object(Klein\Request))
#5 /home/hosting/domains/corp/vault.corp.digdeo.fr/docroot/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#6 /home/hosting/domains/corp/vault.corp.digdeo.fr/docroot/api.php(28): require('/home/hosting/d...')
#7 {main}
```
Maintenance is set to 0 in config.xml and I have this version : 
```
  <configVersion>300.18111001</configVersion>                                                                                                                                                                                                 
  <databaseVersion>300.18093001</databaseVersion> 
```
When I set maintenancemode to 1 I have a maintenance mode on webui and api respond only 'error', when I set 0 I have the json with message "Maintenance mode"
The webui works well.

There is an database upgrade I have missed or other things going wrong on update?

**Comment by nuxsmin** [comment]
Hello, please let me check it out since API uses same rules for maintenance mode. In the meantime, could you update it to latest version (a few minutes ago).

Regards

**Comment by pierrehenrymuller** [comment]
Perfect it works, thanks :D

**Comment by nuxsmin** [comment]
Fine, thanks for the feedback!
