### ISSUE TITLE
LDAP Error while searching the group RDN

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#1111]
Hello,

I'm not sure whether this is a duplicate of #1099, so I made a new issue for this.

**sysPass Version**
3.0-rc4 (300.18111902) (3.0 branch with commit 13e12b

**Describe the bug**
Did an upgrade from latest 2.x series to 3.0-rc3 and had the message ```Another Error while searching the group RDN``` when trying to sync MS ADS Ldap users.
I then upgraded to latest 3.0 branch and tried again, with same results.

**To Reproduce**
1. Go to config > LDAP
2. Enter bind password (leave everything else)
3. Click on 'check'

**Expected behavior**
Listing of LDAP users (works with 2.x series on the same server)

**Event log**
```
2018-11-21 18:56:42 [DEBUG] [SP\Core\Language::setLocales] Locale set to: fr_FR.utf8
2018-11-21 18:56:42 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] exception;Erreur de connexion (BIND)
2018-11-21 18:56:42 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-21 18:57:06 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-21 18:57:06 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-21 18:57:06 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-21 18:57:06 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-21 18:57:06 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-21 18:57:06 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-21 18:57:06 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-21 18:57:06 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-21 18:57:06 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-21 18:57:06 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-21 18:57:06 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-21 18:57:06 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Mail\MailHandler
2018-11-21 18:57:06 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-21 18:57:06 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-21 18:57:06 [DEBUG] [SP\Core\Language::setLocales] Locale set to: fr_FR.utf8
2018-11-21 18:57:06 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] edit.plugin.unavailable;;Plugin unavailable: Authenticator
2018-11-21 18:57:06 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-21 18:57:06 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ConfigLdapController::checkAction::Array
(
)

2018-11-21 18:57:06 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-21 18:57:06 [EXCEPTION] [N/A] Connection error (BIND)
#0 /home/www/beta.kp.fmi.fr/ftp/www/lib/SP/Providers/Auth/Ldap/LdapConnection.php(114): SP\Providers\Auth\Ldap\LdapConnection->bind()
#1 /home/www/beta.kp.fmi.fr/ftp/www/lib/SP/Providers/Auth/Ldap/LdapConnection.php(95): SP\Providers\Auth\Ldap\LdapConnection->connectAndBind()
#2 /home/www/beta.kp.fmi.fr/ftp/www/lib/SP/Services/Ldap/LdapCheckService.php(55): SP\Providers\Auth\Ldap\LdapConnection->checkConnection()
#3 /home/www/beta.kp.fmi.fr/ftp/www/app/modules/web/Controllers/ConfigLdapController.php(151): SP\Services\Ldap\LdapCheckService->checkConnection(Object(SP\Providers\Auth\Ldap\LdapParams))
#4 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#5 /home/www/beta.kp.fmi.fr/ftp/www/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#6 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /home/www/beta.kp.fmi.fr/ftp/www/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /home/www/beta.kp.fmi.fr/ftp/www/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#9 /home/www/beta.kp.fmi.fr/ftp/www/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#10 /home/www/beta.kp.fmi.fr/ftp/www/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#11 /home/www/beta.kp.fmi.fr/ftp/www/index.php(28): require('/home/www/beta....')
#12 {main}
2018-11-21 18:57:06 [DEBUG] [SP\Core\Language::setLocales] Locale set to: fr_FR.utf8
2018-11-21 18:57:06 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] exception;Erreur de connexion (BIND)
2018-11-21 18:57:06 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-21 18:57:18 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-21 18:57:18 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-21 18:57:18 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-21 18:57:18 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-21 18:57:18 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-21 18:57:18 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-21 18:57:18 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-21 18:57:18 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-21 18:57:18 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-21 18:57:18 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-21 18:57:18 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-21 18:57:18 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Mail\MailHandler
2018-11-21 18:57:18 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-21 18:57:18 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-21 18:57:18 [DEBUG] [SP\Core\Language::setLocales] Locale set to: fr_FR.utf8
2018-11-21 18:57:18 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] edit.plugin.unavailable;;Plugin unavailable: Authenticator
2018-11-21 18:57:18 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-21 18:57:18 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ConfigLdapController::checkAction::Array
(
)

2018-11-21 18:57:18 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-21 18:57:18 [EXCEPTION] [N/A] Error while searching the group RDN
#0 /home/www/beta.kp.fmi.fr/ftp/www/lib/SP/Providers/Auth/Ldap/Ldap.php(145): SP\Providers\Auth\Ldap\LdapActions->searchGroupsDn('(objectCategory...')
#1 /home/www/beta.kp.fmi.fr/ftp/www/lib/SP/Providers/Auth/Ldap/LdapMsAds.php(60): SP\Providers\Auth\Ldap\Ldap->getGroupDn()
#2 /home/www/beta.kp.fmi.fr/ftp/www/lib/SP/Services/Ldap/LdapCheckService.php(80): SP\Providers\Auth\Ldap\LdapMsAds->getGroupMembershipFilter()
#3 /home/www/beta.kp.fmi.fr/ftp/www/app/modules/web/Controllers/ConfigLdapController.php(153): SP\Services\Ldap\LdapCheckService->getObjects(false)
#4 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#5 /home/www/beta.kp.fmi.fr/ftp/www/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#6 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /home/www/beta.kp.fmi.fr/ftp/www/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /home/www/beta.kp.fmi.fr/ftp/www/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#9 /home/www/beta.kp.fmi.fr/ftp/www/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#10 /home/www/beta.kp.fmi.fr/ftp/www/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#11 /home/www/beta.kp.fmi.fr/ftp/www/index.php(28): require('/home/www/beta....')
#12 {main}
2018-11-21 18:57:18 [DEBUG] [SP\Core\Language::setLocales] Locale set to: fr_FR.utf8
2018-11-21 18:57:18 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] exception;Erreur pendant la recherche RDN du groupe
2018-11-21 18:57:18 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
```

**Platform (please complete the following information):**
 - OS: CentOS
 - OS Version: 7.5 x64
 - PHP 7.0
 - Browser Opera 56

**Comment by nuxsmin** [comment]
Hello @deajan ,

It could be caused by the group DN, so could you please enter the full group DN?. Before that, you may set `ldap.` in logging events list, so it should log some useful messages in event log.

Regards

**Comment by deajan** [comment]
The full group DN is already there.
If I happen to remove it, the ldap query works.
I have tried using both cn and dn attributes, they both fail.
I have set ```ldap.```in the events list, but it does not seem to log more.

![image](https://user-images.githubusercontent.com/4681318/48902087-be798300-ee57-11e8-9bf2-e34bf4ec649d.png)

Here's the output
```
2018-11-22 13:09:51 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-22 13:09:51 [DEBUG] [SP\Core\Language::setLocales] Locale set to: fr_FR.utf8
2018-11-22 13:09:51 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-22 13:09:51 [DEBUG] [SP\Core\Language::setLocales] Locale set to: fr_FR.utf8
2018-11-22 13:09:51 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-22 13:09:51 [EXCEPTION] [N/A] Error while searching objects in base DN
#0 /home/www/beta.kp.fmi.fr/ftp/www/lib/SP/Services/Ldap/LdapCheckService.php(80): SP\Providers\Auth\Ldap\LdapActions->getObjects('(&(|(memberOf=c...', Array)
#1 /home/www/beta.kp.fmi.fr/ftp/www/app/modules/web/Controllers/ConfigLdapController.php(153): SP\Services\Ldap\LdapCheckService->getObjects(false)
#2 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#3 /home/www/beta.kp.fmi.fr/ftp/www/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /home/www/beta.kp.fmi.fr/ftp/www/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /home/www/beta.kp.fmi.fr/ftp/www/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#7 /home/www/beta.kp.fmi.fr/ftp/www/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#8 /home/www/beta.kp.fmi.fr/ftp/www/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#9 /home/www/beta.kp.fmi.fr/ftp/www/index.php(28): require('/home/www/beta....')
#10 {main}
2018-11-22 13:09:51 [DEBUG] [SP\Core\Language::setLocales] Locale set to: fr_FR.utf8
2018-11-22 13:09:51 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] exception;Erreur pendant la recherche d'objets dans la base DN
2018-11-22 13:09:51 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-22 13:09:51 [DEBUG] [SP\Core\Language::setLocales] Locale set to: fr_FR.utf8
2018-11-22 13:09:51 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
```

While searching your code, I found a bug in the recursive group membership for MS ADS, and also I found that it is not possible to user uppercase 'cn' attribute. I've made PR #1113 in order to resolve this directly on the 3.0 branch.

**Comment by deajan** [comment]
With those patches (or when using 'cn' instead of 'CN' for group), I get ```Error while searching objects in base DN``` with the lof above.

**Comment by deajan** [comment]
I think I have traced the error.
In lib/SP/Providers/Auth/Ldap/LdapActions.php:
```
$searchRes = @ldap_search($this->ldapHandler, $this->ldapParams->getSearchBase(), $filter, $attributes);
```

Setting $filters variable to something like "(objectClass=top)" works.
Using a filter like "(memberOf=cn=somegroup,ou=users,dc=contoso,dc=local)" does not work.

I logged the original sysPass generated filter using logger() and put it directly into my Win2012 R2 ldp.exe, which worked.

So I tried to change the search base from "dc=contoso,dc=local" to something with a subscope like "ou=users,dc=contoso,dc=local", and it works, even when using the sysPass generated filter.

So it seems that the php ldap_search function does not allow using a memberOf filter when the search base is the top domain.
What bugs me here is that the very same setup worked under sysPass v2, using the same server and php version.

**Comment by deajan** [comment]
Forget the last part, for whatever reason, I had trouble with the filters (maybe too much searching), maybe something fishy with the last composer update, I don't know.

I did another fresh upgrade, applied the PR, and things work out for me :)

**Comment by deajan** [comment]
Okay, got around the problem again...
I've traced the problem to the following:
Searching an MSADS LDAP with a memberOf filter on base scope produces `Warning: ldap_search(): Search: Operations error` unless LDAP_OPT_REFERRALS is set to 0.

In LdapActions.php, you initiate a connection which does not use the LDAP_OPT_REFERRALS value configured in LdapMSAds.php, hence the error.

I could walk round the issue by adding a forced LDAP_OPT_REFERRALS 0 in LdapConnections.php like:
```
        @ldap_set_option($this->ldapHandler, LDAP_OPT_NETWORK_TIMEOUT, self::TIMEOUT);
        @ldap_set_option($this->ldapHandler, LDAP_OPT_PROTOCOL_VERSION, 3);
        @ldap_set_option($this->ldapHandler, LDAP_OPT_REFERRALS, 0);
        $this->isTls = $this->connectTls();
```

I guess the following function in LdapMsAds.php is not used correctly (or not used for basic search operations, or does not update the right handler instance.
```
    public function connect()
    {
        $handler = parent::connect();

        @ldap_set_option($handler, LDAP_OPT_REFERRALS, 0);

        return true;
    }
```

This patch resolves the issue for me.
Since you're using LDAP_OPT_REFERRALS, 0 anyway in both LdapMsAds.php and LdapStd.php, maybe you could get rid of both LDAP_OPT_REFERRALS initialisations in favor for the one in LdapConnections.php.

Hope this will be useful and solve a lot of LDAP issues.

**Comment by vmario89** [comment]
I got a filter problem too:
![grafik](https://user-images.githubusercontent.com/5631071/48948721-db848380-ef35-11e8-8acc-2293bda72966.png)

If i enter something else than a whitespace then i get this error - it does not play a role what i select for previous fields (login attribute, name attribute, ...)

**Comment by deajan** [comment]
Try to use a base scope with an OU instead of the base domain scope, I'm pretty sure it resolves the issue, before applying my patch.

**Comment by vmario89** [comment]
Hi @deajan 

i have different instances on different hardware. on my odroid (Xubuntu 18 arm platform) the ldap libs are:


ii  libaprutil1-ldap:armhf         1.6.1-2                                                 armhf        Apache Portable Runtime Utility Library - LDAP Driver
ii  libldap-2.4-2:armhf            2.4.45+dfsg-1ubuntu1                                    armhf        OpenLDAP libraries
ii  libldap-common                 2.4.45+dfsg-1ubuntu1                                    all          OpenLDAP common files for libraries
rc  php7.1-ldap                    7.1.20-1+ubuntu18.04.1+deb.sury.org+1                   armhf        LDAP module for PHP
ii  php7.2-ldap                    7.2.12-1+ubuntu18.04.1+deb.sury.org+1                   armhf        LDAP module for PHP

and on by Ubuntu 16 they are:

ii  libaprutil1-ldap:amd64               1.5.4-1build1                                            amd64        Apache Portable Runtime Utility Library - LDAP Driver
ii  libldap-2.4-2:amd64                  2.4.42+dfsg-2ubuntu3.3                                   amd64        OpenLDAP libraries
ii  php-ldap                             1:7.2+62+ubuntu16.04.1+deb.sury.org+3                    all          LDAP module for PHP [default]
rc  php7.0-ldap                          7.0.31-1+ubuntu16.04.1+deb.sury.org+1                    amd64        LDAP module for PHP
ii  php7.2-ldap                          7.2.12-1+ubuntu16.04.1+deb.sury.org+1                    amd64        LDAP module for PHP


is there maybe another place where i could have some log traces?

regards, Mario ;)

**Comment by vmario89** [comment]
Wuaah forget the first i mentioned. The LDAP thing i only use on the Ubuntu instance ;o)

**Comment by deajan** [comment]
You may remove the '@' from ldap_search in LdapActions.php in order to have an error string.
I'm still puzzled why this only happens sometimes.
Also, you run php7.0 and php7.2 on your ubuntu... Which one is used ?

**Comment by vmario89** [comment]
Hey, 7.0 is not used for this instance; For this i enabled 7.2; i ran system upgrade but its already the latest state.
Some overview of parameters:

![grafik](https://user-images.githubusercontent.com/5631071/48952369-40de7180-ef42-11e8-8da0-ccf1b562d9cf.png)

I will try out the ting with the @

regards, Mario

**Comment by vmario89** [comment]
Hey,

the ldap option made no difference in my case:
![grafik](https://user-images.githubusercontent.com/5631071/48952665-42f50000-ef43-11e8-8361-a07628140f2b.png)
Still:
![grafik](https://user-images.githubusercontent.com/5631071/48952676-4ab4a480-ef43-11e8-8384-a3f86a3fdd76.png)

i have no idea

**Comment by deajan** [comment]
@vmario89 Have you tried adding an ou to the search base ?
Noticed this works for me.

**Comment by deajan** [comment]
@vmario89 also, have you tried turning it off and on again ? (Sorry, end of the week 8-))

**Comment by nuxsmin** [comment]
@vmario89 hello, so late reply, but I have been traveling the whole day...

The filter must be a valid LDAP filter, so it's an advanced feature which requires to know how LDAP filtering works and schema attributes. This kind of filtering allows to perform a selective import (you can do it in several batches).

Regards.

**Comment by vmario89** [comment]
Hi, thanks for the feedback. Finally i got it working. I used CN=My Username as an example and it worked.

cheers, Mario

**Comment by deajan** [comment]
Well there's still that transient error we're dealing with.
To resume:
Sometimes we get `Error while searching objects in base DN` which can be resolved by adding an OU to the base scope.
I've checked a lot of discussions about php's ldap_search() and they all talk about adding
```
@ldap_set_option($this->ldapHandler, LDAP_OPT_REFERRALS, 0);
```
@vmario89 did test this but using a bad ldap filter, results are biased.
@nuxsmin I still confirm that putting this line right before @ldap_search in LdapActions.php did resolve the issue for me.
Is it possible that the LDAP_OPT_REFERRALS option in LdapMSAds.php and LdapStd.php are not called ?
Or maybe you initiate a new bind somewhere in your code without that option somewhere later in the code ?

Also, adding 'ldap.' in my event log didn't add anything LDAP specific in syspass.log for me, but only in the eventlog itself. Is that the expected behavior ?

**Comment by nuxsmin** [comment]
@deajan I've just added `LDAP_OPT_REFERRALS` option on every connection, so referrals won't be resolved anymore.

Thanks for the feedback!

**Comment by deajan** [comment]
Works for me.

**Comment by deminart** [comment]
Good afternoon everyone, please tell me how to solve...

OU=GK,DC=group,DC=ru,group.com
CN=Users,DC=group,DC=ru,group.com
With this option I get the error:
Error searching for objects in DN

OU=GK,DC=group,DC=ru,group.com
OU=Users,OU=Buh,OU=GK,DC=group,DC=ru,group.com
With this option I get the error:
Error while searching the group RDN
