### ISSUE TITLE
Cannot save mail settings

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#1127]
**sysPass Version**
3.0-rc4

**Describe the bug**
Updating smtp settings, testing them seems to work, saving them gets the following:

![image](https://user-images.githubusercontent.com/4681318/49003929-5ed6ec80-f163-11e8-9471-a79d1faae067.png)

**Event log**
```
2018-11-26 10:07:42 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-26 10:07:42 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-26 10:07:42 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-26 10:07:42 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-26 10:07:42 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-26 10:07:42 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-26 10:07:42 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-26 10:07:42 [DEBUG] [SP\Core\Language::setLocales] Locale set to: fr_FR.utf8
2018-11-26 10:07:42 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-26 10:07:42 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-26 10:07:42 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-26 10:07:42 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Mail\MailHandler
2018-11-26 10:07:42 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-26 10:07:42 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-26 10:07:42 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] edit.plugin.unavailable;;Plugin unavailable: Authenticator
2018-11-26 10:07:42 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ConfigMailController::saveAction::Array
(
)

2018-11-26 10:07:42 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-26 10:07:43 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing error: Argument 1 passed to SP\Config\ConfigData::setMailEvents() must be of the type array, null given, called in /var/www/somevhost.local/ftp/www/app/modules/web/Controllers/ConfigMailController.php on line 87
2018-11-26 10:07:43 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing error: #0 /var/www/somevhost.local/ftp/www/app/modules/web/Controllers/ConfigMailController.php(87): SP\Config\ConfigData->setMailEvents(NULL)
#1 [internal function]: SP\Modules\Web\Controllers\ConfigMailController->saveAction()
#2 /var/www/somevhost.local/ftp/www/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#4 /var/www/somevhost.local/ftp/www/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/somevhost.local/ftp/www/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/somevhost.local/ftp/www/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/somevhost.local/ftp/www/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#8 /var/www/somevhost.local/ftp/www/index.php(28): require('/var/www/beta.k...')
#9 {main}
2018-11-26 10:08:26 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-26 10:08:26 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-26 10:08:26 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-26 10:08:26 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-26 10:08:26 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-26 10:08:26 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-26 10:08:26 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-26 10:08:27 [DEBUG] [SP\Core\Language::setLocales] Locale set to: fr_FR.utf8
2018-11-26 10:08:27 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-26 10:08:27 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-26 10:08:27 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-11-26 10:08:27 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Mail\MailHandler
2018-11-26 10:08:27 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-26 10:08:27 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-26 10:08:27 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] edit.plugin.unavailable;;Plugin unavailable: Authenticator
2018-11-26 10:08:27 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ItemsController::notificationsAction::Array
(
)

2018-11-26 10:08:27 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
```

**Comment by nuxsmin** [comment]
Hello, it seems that if no events are set, the handler fails...I'll fix it shortly.

Thanks for the feedback!

**Comment by deajan** [comment]
Works for me.
