### ISSUE TITLE
Changing Account Preferences not working

### ISSUE THREAD

**Issue by Edll** [nuxsmin/sysPass#1144]
**sysPass Version**
sysPass 3.0-rc5

if I change the account preferences an error appear:

Error in GUI
```
There was an error

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Argument 1 passed to SP\Config\ConfigData::setFilesAllowedMime() must be of the type array, null given, called in /var/www/html/app/modules/web/Controllers/ConfigAccountController.php on line 77
```
Stacktrace from Syslog
```
2018-11-29 11:44:49 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-29 11:44:49 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing error: Argument 1 passed to SP\Config\ConfigData::setFilesAllowedMime() must be of the type array, null given, called in /var/www/html/app/modules/web/Controllers/ConfigAccountController.php on line 77
2018-11-29 11:44:49 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing error: #0 /var/www/html/app/modules/web/Controllers/ConfigAccountController.php(77): SP\Config\ConfigData->setFilesAllowedMime(NULL)
#1 [internal function]: SP\Modules\Web\Controllers\ConfigAccountController->saveAction()
#2 /var/www/html/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#4 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/html/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#8 /var/www/html/index.php(28): require('/var/www/html/l...')
#9 {main}
2018-11-29 11:45:46 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-29 11:45:46 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-29 11:45:46 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-29 11:45:46 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-29 11:45:46 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-29 11:45:46 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-29 11:45:46 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-29 11:45:46 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-29 11:45:46 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-29 11:45:46 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-29 11:45:46 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Mail\MailHandler
2018-11-29 11:45:46 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-29 11:45:46 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-29 11:45:46 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ItemsController::notificationsAction::Array
(
)

2018-11-29 11:45:46 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-29 11:46:33 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-29 11:46:33 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-29 11:46:33 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-29 11:46:33 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-29 11:46:33 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-29 11:46:33 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-29 11:46:33 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-29 11:46:33 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-29 11:46:33 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-29 11:46:33 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-29 11:46:33 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Mail\MailHandler
2018-11-29 11:46:33 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-29 11:46:33 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-29 11:46:33 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ItemsController::notificationsAction::Array
(
)

2018-11-29 11:46:33 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-29 11:47:12 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-29 11:47:12 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-29 11:47:12 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-29 11:47:12 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-29 11:47:12 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-29 11:47:12 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-29 11:47:12 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-29 11:47:12 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-29 11:47:12 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-29 11:47:12 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-29 11:47:12 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Mail\MailHandler
2018-11-29 11:47:12 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-29 11:47:12 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-29 11:47:12 [DEBUG] [SP\Core\Crypt\Session::reKey] SP\Core\Crypt\Session::reKey
2018-11-29 11:47:12 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ConfigAccountController::saveAction::Array
(
)

2018-11-29 11:47:12 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-29 11:47:12 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing error: Argument 1 passed to SP\Config\ConfigData::setFilesAllowedMime() must be of the type array, null given, called in /var/www/html/app/modules/web/Controllers/ConfigAccountController.php on line 77
2018-11-29 11:47:12 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing error: #0 /var/www/html/app/modules/web/Controllers/ConfigAccountController.php(77): SP\Config\ConfigData->setFilesAllowedMime(NULL)
#1 [internal function]: SP\Modules\Web\Controllers\ConfigAccountController->saveAction()
#2 /var/www/html/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#4 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/html/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#8 /var/www/html/index.php(28): require('/var/www/html/l...')
#9 {main}
2018-11-29 11:47:46 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-29 11:47:46 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-11-29 11:47:46 [DEBUG] [SP\Bootstrap::run] ------------
2018-11-29 11:47:46 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-11-29 11:47:46 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-11-29 11:47:46 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-11-29 11:47:46 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-11-29 11:47:46 [DEBUG] [SP\Core\Language::setLocales] Locale set to: en_US.utf8
2018-11-29 11:47:46 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-11-29 11:47:46 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-11-29 11:47:46 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Mail\MailHandler
2018-11-29 11:47:46 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-11-29 11:47:46 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-11-29 11:47:46 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ItemsController::notificationsAction::Array
(
)

2018-11-29 11:47:46 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
```

**Comment by vmario89** [comment]
Hey,
this error appears because last releases the file handling was changes and the settings mask updated. You will either need to set at least a minimum of one allowed mime type or disable the file upload completely. then you can save your settings.

![grafik](https://user-images.githubusercontent.com/5631071/49220143-a49aeb80-f3d5-11e8-9ba0-9a8f40cae45d.png)

**Comment by Edll** [comment]
Thanks that helped.

I still leave this report open so that the error can be replaced by a clear message.

**Comment by nuxsmin** [comment]
Hello, this is a wrong behaviour indeed, since if no mime types were set, it should pass an empty array of items. It has been solved in latest commit (not pushed yet).

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Hello, this issue has been fixed in latest commits. Thanks for the feedback!
