### ISSUE TITLE
Unable to connect to DB

### ISSUE THREAD

**Issue by jorgemfm** [nuxsmin/sysPass#1154]
**sysPass Version**
v3 rc5

**Describe the bug**
Error during installation:

```
Unable to connect to DB
Error 1045: SQLSTATE[HY000] [1045] Access denied for user 'syspass'@'localhost' (using password: YES)
```

I was able to install version 3.0-beta (300.18110601) with the same user/password

I've also tried using root, i've tried with **Hosting Mode** checked and not checked, and tried with the database already created and not created.

**Event log**

```
2018-12-03 20:33:00 [ERROR] [SP\Core\Language::setLocales] Could not set locale
2018-12-03 20:33:00 [DEBUG] [SP\Core\Language::setLocales] Domain path: /var/www/html/syspass/app/locales
2018-12-03 20:33:00 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-12-03 20:33:00 [DEBUG] [SP\Bootstrap::run] ------------
2018-12-03 20:33:00 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-12-03 20:33:00 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-12-03 20:33:00 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-12-03 20:33:00 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-12-03 20:33:00 [ERROR] [SP\Core\Language::setLocales] Could not set locale
2018-12-03 20:33:00 [DEBUG] [SP\Core\Language::setLocales] Domain path: /var/www/html/syspass/app/locales
2018-12-03 20:33:00 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-12-03 20:33:00 [DEBUG] [SP\Core\Context\SessionContext::close] Session closed
2018-12-03 20:33:00 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\InstallController::installAction::Array
(
)

2018-12-03 20:33:00 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-12-03 20:33:00 [DEBUG] [SP\Http\Request::analyzeEncrypted] No RSA encrypted data from request
2018-12-03 20:33:00 [DEBUG] [SP\Http\Request::analyzeEncrypted] No RSA encrypted data from request
2018-12-03 20:33:00 [DEBUG] [SP\Http\Request::analyzeEncrypted] No RSA encrypted data from request
2018-12-03 20:33:00 [EXCEPTION] [N/A] Unable to connect to DB
#0 /var/www/html/syspass/lib/SP/Services/Install/MySQL.php(94): SP\Storage\Database\MySQLHandler->getConnectionSimple()
#1 /var/www/html/syspass/lib/SP/Services/Install/MySQL.php(72): SP\Services\Install\MySQL->connectDatabase()
#2 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(266): SP\Services\Install\MySQL->__construct(Object(SP\Services\Install\InstallData), Object(SP\Config\ConfigData))
#3 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(182): SP\Services\Install\Installer->setupDb()
#4 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(94): SP\Services\Install\Installer->install()
#5 /var/www/html/syspass/app/modules/web/Controllers/InstallController.php(87): SP\Services\Install\Installer->run(Object(SP\Services\Install\InstallData))
#6 [internal function]: SP\Modules\Web\Controllers\InstallController->installAction()
#7 /var/www/html/syspass/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#8 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/html/syspass/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#12 /var/www/html/syspass/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#13 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#14 {main}
2018-12-03 20:33:00 [EXCEPTION] [N/A] (P) SQLSTATE[HY000] [1045] Access denied for user 'syspass'@'localhost' (using password: YES)
#0 /var/www/html/syspass/lib/SP/Storage/Database/MySQLHandler.php(173): PDO->__construct('mysql:charset=u...', 'syspass', 'dBh4el2KkyYLJvv...', Array)
#1 /var/www/html/syspass/lib/SP/Services/Install/MySQL.php(94): SP\Storage\Database\MySQLHandler->getConnectionSimple()
#2 /var/www/html/syspass/lib/SP/Services/Install/MySQL.php(72): SP\Services\Install\MySQL->connectDatabase()
#3 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(266): SP\Services\Install\MySQL->__construct(Object(SP\Services\Install\InstallData), Object(SP\Config\ConfigData))
#4 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(182): SP\Services\Install\Installer->setupDb()
#5 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(94): SP\Services\Install\Installer->install()
#6 /var/www/html/syspass/app/modules/web/Controllers/InstallController.php(87): SP\Services\Install\Installer->run(Object(SP\Services\Install\InstallData))
#7 [internal function]: SP\Modules\Web\Controllers\InstallController->installAction()
#8 /var/www/html/syspass/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#9 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#12 /var/www/html/syspass/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#13 /var/www/html/syspass/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#14 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#15 {main}
2018-12-03 20:33:00 [EXCEPTION] [N/A] Unable to connect to DB
#0 /var/www/html/syspass/lib/SP/Services/Install/MySQL.php(72): SP\Services\Install\MySQL->connectDatabase()
#1 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(266): SP\Services\Install\MySQL->__construct(Object(SP\Services\Install\InstallData), Object(SP\Config\ConfigData))
#2 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(182): SP\Services\Install\Installer->setupDb()
#3 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(94): SP\Services\Install\Installer->install()
#4 /var/www/html/syspass/app/modules/web/Controllers/InstallController.php(87): SP\Services\Install\Installer->run(Object(SP\Services\Install\InstallData))
#5 [internal function]: SP\Modules\Web\Controllers\InstallController->installAction()
#6 /var/www/html/syspass/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#7 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/syspass/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#11 /var/www/html/syspass/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#12 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#13 {main}
2018-12-03 20:33:00 [EXCEPTION] [N/A] (P) Unable to connect to DB
#0 /var/www/html/syspass/lib/SP/Services/Install/MySQL.php(94): SP\Storage\Database\MySQLHandler->getConnectionSimple()
#1 /var/www/html/syspass/lib/SP/Services/Install/MySQL.php(72): SP\Services\Install\MySQL->connectDatabase()
#2 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(266): SP\Services\Install\MySQL->__construct(Object(SP\Services\Install\InstallData), Object(SP\Config\ConfigData))
#3 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(182): SP\Services\Install\Installer->setupDb()
#4 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(94): SP\Services\Install\Installer->install()
#5 /var/www/html/syspass/app/modules/web/Controllers/InstallController.php(87): SP\Services\Install\Installer->run(Object(SP\Services\Install\InstallData))
#6 [internal function]: SP\Modules\Web\Controllers\InstallController->installAction()
#7 /var/www/html/syspass/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#8 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/html/syspass/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#12 /var/www/html/syspass/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#13 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#14 {main}
```

**Platform (please complete the following information):**
 - OS: Linux
 - OS Version: Debian 9.5
 - Browser: Chrome

**Comment by jorgemfm** [comment]
I don't know what happened, but I retried everything from the beginning and it just worked.

I'm almost sure I had the user/pass right.

Anyway, you can close this.

Thank you!

**Comment by nuxsmin** [comment]
Fine, thanks for the feedback!

Regards
