### ISSUE TITLE
Erro during login with Password Change active

### ISSUE THREAD

**Issue by jorgemfm** [nuxsmin/sysPass#1155]
**sysPass Version**
3.0-rc5 (300.18112601)

**Describe the bug**
Error when trying to login with a user with the **Password Change** active 

URL: http://xxx.xxx.xxx.xxx/index.php?r=userPassReset/change/5bd74b1dabee7a7b49b9a9c3d276f063

Error: Oops, it looks like this content does not exist...

**To Reproduce**
1. Create a  user and choose the  **Password Change** options
2. Try to login with the user

**Event log**
```
2018-12-03 21:26:14 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-12-03 21:26:14 [ERROR] [SP\Core\Language::setLocales] Could not set locale
2018-12-03 21:26:14 [DEBUG] [SP\Core\Language::setLocales] Domain path: /var/www/html/syspass/app/locales
2018-12-03 21:26:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] login.auth.database;;Type: authDatabase;User: jfm
2018-12-03 21:26:14 [DEBUG] [SP\Core\Language::setLocales] Locale set to: pt_PT.utf8
2018-12-03 21:26:14 [ERROR] [SP\Core\Language::setLocales] Could not set locale
2018-12-03 21:26:14 [DEBUG] [SP\Core\Language::setLocales] Domain path: /var/www/html/syspass/app/locales
2018-12-03 21:26:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] login.checkUser.changePass;;User: jfm
2018-12-03 21:26:14 [DEBUG] [SP\Core\Language::setLocales] Locale set to: pt_PT.utf8
2018-12-03 21:26:14 [ERROR] [SP\Core\Language::setLocales] Could not set locale
2018-12-03 21:26:14 [DEBUG] [SP\Core\Language::setLocales] Domain path: /var/www/html/syspass/app/locales
2018-12-03 21:26:14 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] login.finish;;
2018-12-03 21:26:14 [DEBUG] [SP\Core\Language::setLocales] Locale set to: pt_PT.utf8
2018-12-03 21:26:14 [ERROR] [SP\Core\Language::setLocales] Could not set locale
2018-12-03 21:26:14 [DEBUG] [SP\Core\Language::setLocales] Domain path: /var/www/html/syspass/app/locales
2018-12-03 21:26:14 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-12-03 21:26:14 [DEBUG] [SP\Bootstrap::run] ------------
2018-12-03 21:26:14 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-12-03 21:26:14 [DEBUG] [SP\Bootstrap::SP\{closure}] SP\Modules\Web\Controllers\UserPassResetController::changeAction
2018-12-03 21:26:14 [EXCEPTION] [N/A] Oops, it looks like this content does not exist...
#0 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#1 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#2 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#3 /var/www/html/syspass/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#4 /var/www/html/syspass/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#5 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#6 {main}
2018-12-03 21:26:51 [ERROR] [SP\Core\Language::setLocales] Could not set locale
2018-12-03 21:26:51 [DEBUG] [SP\Core\Language::setLocales] Domain path: /var/www/html/syspass/app/locales
2018-12-03 21:26:51 [DEBUG] [SP\Config\Config::initialize] Config cache loaded
2018-12-03 21:26:51 [DEBUG] [SP\Bootstrap::run] ------------
2018-12-03 21:26:51 [DEBUG] [SP\Bootstrap::run] Boostrap:web
2018-12-03 21:26:51 [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
2018-12-03 21:26:51 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2018-12-03 21:26:51 [DEBUG] [SP\Modules\Web\Init::initialize] SP\Modules\Web\Init::initialize
2018-12-03 21:26:51 [ERROR] [SP\Core\Language::setLocales] Could not set locale
2018-12-03 21:26:51 [DEBUG] [SP\Core\Language::setLocales] Domain path: /var/www/html/syspass/app/locales
2018-12-03 21:26:51 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2018-12-03 21:26:51 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\FileLogHandler
2018-12-03 21:26:51 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Log\DatabaseLogHandler
2018-12-03 21:26:51 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Mail\MailHandler
2018-12-03 21:26:51 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Acl\AclHandler
2018-12-03 21:26:51 [DEBUG] [SP\Core\Events\EventDispatcherBase::attach] Attach: SP\Providers\Notification\NotificationHandler
2018-12-03 21:26:51 [DEBUG] [SP\Bootstrap::SP\{closure}] Routing call: SP\Modules\Web\Controllers\ItemsController::notificationsAction::Array
(
)
```

**Platform (please complete the following information):**
 - OS: Linux
 - OS Version: Debian 9.5
 - Browser:  Chrome

**Comment by nuxsmin** [comment]
Hello, this issue has been fixed in latest commit. Thanks for the feedback!
