### ISSUE TITLE
File type not allowed

### ISSUE THREAD

**Issue by jorgemfm** [nuxsmin/sysPass#1163]
**sysPass Version**
3.0-rc5 (300.18112601)

**Describe the bug**
File type not allowed while uploading a file on an Account.

**To Reproduce**
1. Edit and account
2. Upload a file

**Expected behavior**
Should be able to upload a file

**Event log**
```
2018-12-13 13:50:53 [EXCEPTION] [N/A] File type not allowed
#0 /var/www/html/syspass/app/modules/web/Controllers/AccountFileController.php(217): SP\Modules\Web\Controllers\AccountFileController->checkAllowedMimeType(Object(SP\DataModel\FileData), Object(SP\Storage\File\FileHandler))
#1 [internal function]: SP\Modules\Web\Controllers\AccountFileController->uploadAction(3)
#2 /var/www/html/syspass/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#4 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/syspass/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/html/syspass/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#8 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#9 {main}
2018-12-13 13:50:53 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] exception;File type not allowed
```
**Platform (please complete the following information):**
- OS: Linux
- OS Version: Debian 9.5
- Browser: Chrome

**Additional context**

Did some debugging and this: `$this->configData->getFilesAllowedMime()` on line 279 of file `app/modules/web/Controllers/AccountFileController.php`  returns an empty array.

**Comment by nuxsmin** [comment]
Hello, did you set the allowed mime types?

**Comment by nuxsmin** [comment]
You're welcome
