### ISSUE TITLE
Internal Error on LDAP 

### ISSUE THREAD

**Issue by thenathlm** [nuxsmin/sysPass#1202]
**sysPass Version**
3.0 (300.18122601)

**Describe the bug**
Can't log in to LDAP using my account, can only do so using other LDAP accounts, but not clear as to why.
Says something regarding duplicate account?
Issue #1183 touches on this, but doesn't give a solution, also doesn't appear to be related, as I can log in with all accounts apart from my own.

**To Reproduce**
Enabled LDAP, put in correct info, tested and checked fine, then when logging out and back in, couldn't get in

**Expected behavior**
For me to be able to log in through LDAP.

**Screenshots**
![image](https://user-images.githubusercontent.com/46557932/51315408-0547bb80-1a4a-11e9-9ede-bb9010bef4cc.png)

**Event log**
```
2019-01-17 11:05:17 [EXCEPTION] [N/A] User does not exist
#0 /var/www/html/lib/SP/Providers/Auth/Database/Database.php(108): SP\Services\User\UserService->getByLogin('user.name@p...')
#1 /var/www/html/lib/SP/Providers/Auth/Database/Database.php(82): SP\Providers\Auth\Database\Database->authUser()
#2 /var/www/html/lib/SP/Providers/Auth/AuthProvider.php(167): SP\Providers\Auth\Database\Database->authenticate(Object(SP\DataModel\UserLoginData))
#3 /var/www/html/lib/SP/Providers/Auth/AuthProvider.php(93): SP\Providers\Auth\AuthProvider->authDatabase()
#4 /var/www/html/lib/SP/Services/Auth/LoginService.php(146): SP\Providers\Auth\AuthProvider->doAuth(Object(SP\DataModel\UserLoginData))
#5 /var/www/html/app/modules/web/Controllers/LoginController.php(62): SP\Services\Auth\LoginService->doLogin()
#6 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#7 /var/www/html/lib/SP/Bootstrap.php(234): call_user_func_array(Array, Array)
#8 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/html/lib/SP/Bootstrap.php(456): Klein\Klein->dispatch(Object(Klein\Request))
#12 /var/www/html/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#13 /var/www/html/index.php(28): require('/var/www/html/l...')
#14 {main}
2019-01-17 11:05:17 [EXCEPTION] [N/A] Internal error
#0 /var/www/html/lib/SP/Services/Auth/LoginService.php(152): SP\Services\Auth\LoginService->authLdap(Object(SP\Providers\Auth\Ldap\LdapAuthData))
#1 /var/www/html/app/modules/web/Controllers/LoginController.php(62): SP\Services\Auth\LoginService->doLogin()
#2 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#3 /var/www/html/lib/SP/Bootstrap.php(234): call_user_func_array(Array, Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/lib/SP/Bootstrap.php(456): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#9 /var/www/html/index.php(28): require('/var/www/html/l...')
#10 {main}
2019-01-17 11:05:17 [EXCEPTION] [N/A] (P) Duplicated user login/email
#0 /var/www/html/lib/SP/Services/User/UserService.php(257): SP\Repositories\User\UserRepository->create(Object(SP\DataModel\UserData))
#1 /var/www/html/lib/SP/Services/User/UserService.php(242): SP\Services\User\UserService->create(Object(SP\DataModel\UserData))
#2 /var/www/html/lib/SP/Services/Auth/LoginService.php(579): SP\Services\User\UserService->createOnLogin(Object(SP\Services\User\UserLoginRequest))
#3 /var/www/html/lib/SP/Services/Auth/LoginService.php(152): SP\Services\Auth\LoginService->authLdap(Object(SP\Providers\Auth\Ldap\LdapAuthData))
#4 /var/www/html/app/modules/web/Controllers/LoginController.php(62): SP\Services\Auth\LoginService->doLogin()
#5 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#6 /var/www/html/lib/SP/Bootstrap.php(234): call_user_func_array(Array, Array)
#7 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/lib/SP/Bootstrap.php(456): Klein\Klein->dispatch(Object(Klein\Request))
#11 /var/www/html/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#12 /var/www/html/index.php(28): require('/var/www/html/l...')
#13 {main}
2019-01-17 11:05:27 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-17 11:05:27 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-17 11:05:27 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-17 11:05:27 [EXCEPTION] [N/A] User does not exist
#0 /var/www/html/lib/SP/Providers/Auth/Database/Database.php(108): SP\Services\User\UserService->getByLogin('user.name')
#1 /var/www/html/lib/SP/Providers/Auth/Database/Database.php(82): SP\Providers\Auth\Database\Database->authUser()
#2 /var/www/html/lib/SP/Providers/Auth/AuthProvider.php(167): SP\Providers\Auth\Database\Database->authenticate(Object(SP\DataModel\UserLoginData))
#3 /var/www/html/lib/SP/Providers/Auth/AuthProvider.php(93): SP\Providers\Auth\AuthProvider->authDatabase()
#4 /var/www/html/lib/SP/Services/Auth/LoginService.php(146): SP\Providers\Auth\AuthProvider->doAuth(Object(SP\DataModel\UserLoginData))
#5 /var/www/html/app/modules/web/Controllers/LoginController.php(62): SP\Services\Auth\LoginService->doLogin()
#6 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#7 /var/www/html/lib/SP/Bootstrap.php(234): call_user_func_array(Array, Array)
#8 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/html/lib/SP/Bootstrap.php(456): Klein\Klein->dispatch(Object(Klein\Request))
#12 /var/www/html/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#13 /var/www/html/index.php(28): require('/var/www/html/l...')
#14 {main}
2019-01-17 11:05:28 [EXCEPTION] [N/A] Internal error
#0 /var/www/html/lib/SP/Services/Auth/LoginService.php(152): SP\Services\Auth\LoginService->authLdap(Object(SP\Providers\Auth\Ldap\LdapAuthData))
#1 /var/www/html/app/modules/web/Controllers/LoginController.php(62): SP\Services\Auth\LoginService->doLogin()
#2 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#3 /var/www/html/lib/SP/Bootstrap.php(234): call_user_func_array(Array, Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/lib/SP/Bootstrap.php(456): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#9 /var/www/html/index.php(28): require('/var/www/html/l...')
#10 {main}
2019-01-17 11:05:28 [EXCEPTION] [N/A] (P) Duplicated user login/email
#0 /var/www/html/lib/SP/Services/User/UserService.php(257): SP\Repositories\User\UserRepository->create(Object(SP\DataModel\UserData))
#1 /var/www/html/lib/SP/Services/User/UserService.php(242): SP\Services\User\UserService->create(Object(SP\DataModel\UserData))
#2 /var/www/html/lib/SP/Services/Auth/LoginService.php(579): SP\Services\User\UserService->createOnLogin(Object(SP\Services\User\UserLoginRequest))
#3 /var/www/html/lib/SP/Services/Auth/LoginService.php(152): SP\Services\Auth\LoginService->authLdap(Object(SP\Providers\Auth\Ldap\LdapAuthData))
#4 /var/www/html/app/modules/web/Controllers/LoginController.php(62): SP\Services\Auth\LoginService->doLogin()
#5 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#6 /var/www/html/lib/SP/Bootstrap.php(234): call_user_func_array(Array, Array)
#7 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)


[CONTINUES, BUT JUST THE SAME AS ABOVE]
```

**Platform (please complete the following information):**
 - OS: centos7
 - AD OS: Server 2012 r2
 - Browser: All

**Additional context**
Getting conflicting messages about the account existing or if it's a duplicate account.

**Comment by nuxsmin** [comment]
Hello, it wouldn't be about the user's login itself but the email instead, that's the email of the user being updated from LDAP matches with another sysPass user's email, could you check it out?

Regards

**Comment by thenathlm** [comment]
My apologies, I don't know why I put my email address on the setup of the syspass admin user, but I did.
Thanks for your time and patience, I'll let you get on with more important things now 😅

**Comment by nuxsmin** [comment]
@thenathlm no worries :wink:
