### ISSUE TITLE
The Master Password either is not saved or is wrong

### ISSUE THREAD

**Issue by Jm0uss3t** [nuxsmin/sysPass#1204]
Hello I got the error "The Master Password either is not saved or is wrong" when trying to login with a non admin user.

I just installed everything from the docker file

==== LOG =====

2019-01-22 15:00:38 [EXCEPTION] [N/A] Unable to read/write file (/var/www/html/sysPass/app/cache/colors.cache)
#0 /var/www/html/sysPass/lib/SP/Storage/File/FileCache.php(40): SP\Storage\File\FileHandler->checkIsReadable()
#1 /var/www/html/sysPass/lib/SP/Services/Account/AccountSearchService.php(427): SP\Storage\File\FileCache->load()
#2 /var/www/html/sysPass/lib/SP/Services/Account/AccountSearchService.php(418): SP\Services\Account\AccountSearchService->loadColors()
#3 /var/www/html/sysPass/lib/SP/Services/Service.php(78): SP\Services\Account\AccountSearchService->initialize()
#4 /var/www/html/sysPass/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(142): SP\Services\Service->__construct(Object(DI\Container))
#5 /var/www/html/sysPass/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#6 /var/www/html/sysPass/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#7 /var/www/html/sysPass/vendor/php-di/php-di/src/Container.php(377): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#8 /var/www/html/sysPass/vendor/php-di/php-di/src/Container.php(137): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#9 /var/www/html/sysPass/app/modules/web/Controllers/Helpers/Account/AccountSearchHelper.php(154): DI\Container->get('SP\\Services\\Acc...')
#10 /var/www/html/sysPass/app/modules/web/Controllers/AccountController.php(90): SP\Modules\Web\Controllers\Helpers\Account\AccountSearchHelper->getAccountSearch()
#11 [internal function]: SP\Modules\Web\Controllers\AccountController->indexAction()
#12 /var/www/html/sysPass/lib/SP/Bootstrap.php(234): call_user_func_array(Array, Array)
#13 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#14 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#15 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#16 /var/www/html/sysPass/lib/SP/Bootstrap.php(456): Klein\Klein->dispatch(Object(Klein\Request))
#17 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#18 /var/www/html/sysPass/index.php(28): require('/var/www/html/s...')
#19 {main}
2019-01-22 15:00:44 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:00:44 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:00:44 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:00:45 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:00:45 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:00:45 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:00:45 [INFO] [SP\Core\MimeTypes::loadCache] Loaded MIME types cache
2019-01-22 15:01:32 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:01:32 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:01:32 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:01:45 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:01:45 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:01:45 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:01:48 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:01:48 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:01:48 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:01:52 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:01:52 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:01:52 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:02:12 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:02:12 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:02:12 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:02:12 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:02:12 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:02:12 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:02:25 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:02:25 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:02:25 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:02:25 [EXCEPTION] [N/A] The Master Password either is not saved or is wrong
#0 /var/www/html/sysPass/lib/SP/Services/Auth/LoginService.php(172): SP\Services\Auth\LoginService->loadMasterPass()
#1 /var/www/html/sysPass/app/modules/web/Controllers/LoginController.php(62): SP\Services\Auth\LoginService->doLogin()
#2 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#3 /var/www/html/sysPass/lib/SP/Bootstrap.php(234): call_user_func_array(Array, Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/sysPass/lib/SP/Bootstrap.php(456): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#9 /var/www/html/sysPass/index.php(28): require('/var/www/html/s...')
#10 {main}
2019-01-22 15:02:38 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:02:38 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:02:38 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:03:53 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:03:53 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:03:53 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:04:00 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:04:00 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:04:00 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:04:01 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:04:01 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:04:01 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:04:01 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:04:01 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:04:01 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:04:01 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:04:01 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:04:01 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:04:01 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:04:01 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:04:01 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:04:02 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:04:02 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:04:02 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:04:02 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:04:02 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:04:02 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:04:06 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:04:06 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:04:06 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:04:11 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:04:11 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:04:11 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:04:12 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:04:12 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:04:12 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:04:23 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:04:23 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:04:23 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-22 15:04:23 [INFO] [SP\Core\MimeTypes::loadCache] Loaded MIME types cache
2019-01-22 15:04:29 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-22 15:04:29 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-22 15:04:29 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache

======= INFO =======

3.0 (301.19012002)
--
Database | SERVER_VERSION : 5.5.5-10.2.21-MariaDB-1:10.2.21+maria~bionic                                             CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $                                             SERVER_INFO : Uptime: 1309   Threads: 8  Questions: 1273  Slow queries: 0  Opens: 46  Flush tables: 1   Open tables: 40  Queries per second avg: 0.972                                             CONNECTION_STATUS : syspass-db via TCP/IP                                         Name: syspass@syspass-db
PHP | Version: 7.0.33-0+deb9u1                         Extensions: Core, date, libxml, openssl,  pcre, zlib, filter, hash, Reflection, SPL, session, standard,  apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring,  fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mcrypt,  mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets,  sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl,  Zend OPcache                                     Used Memory: 2048 KB                         User: root                         Download rate: 43 MB/s                                             OP Cache                                    num_cached_scripts : 394                                    num_cached_keys : 739                                    max_cached_keys : 3907                                    hits : 18908                                    start_time : 1548168168                                    last_restart_time : 0                                    oom_restarts : 0                                    hash_restarts : 0                                    manual_restarts : 0                                    misses : 394                                    blacklist_misses : 0                                    blacklist_miss_ratio : 0                                    opcache_hit_rate : 97.958760750181
Server | Apache/2.4.25 (Debian)

**Comment by Jm0uss3t** [comment]
closed sorry bad use

**Comment by abhiroop93** [comment]
@Jm0uss3t How was this fixed? I am facing a similar issue
