### ISSUE TITLE
Logging is not working as expected

### ISSUE THREAD

**Issue by VexedSyd** [nuxsmin/sysPass#1205]
**sysPass Version**
3.0 (301.19012002)

**Describe the bug**
Event log missing some events like "Log in", "Logout session", "View Password". Event log is showing "save.config.*" events.

**Expected behavior**
Pre v3 installation, the event log showed a comprehensive log of all events.

**Event log**

I can't see anything related to this issue in syspass.log, but I will share the errors that I found in the log.

```
2019-01-23 11:01:23 [EXCEPTION] [N/A] Response is locked
#0 /var/www/html/syspass/vendor/klein/klein/src/Klein/AbstractResponse.php(157): Klein\AbstractResponse->requireUnlocked()
#1 /var/www/html/syspass/lib/SP/Bootstrap.php(145): Klein\AbstractResponse->body('Response is loc...')
#2 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Klein), 'Response is loc...', 'Klein\\Exception...', Object(Klein\Exceptions\LockedResponseException))
#3 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(936): call_user_func(Object(Closure), Object(Klein\Klein), 'Response is loc...', 'Klein\\Exception...', Object(Klein\Exceptions\LockedResponseException))
#4 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(645): Klein\Klein->error(Object(Klein\Exceptions\LockedResponseException))
#5 /var/www/html/syspass/lib/SP/Bootstrap.php(456): Klein\Klein->dispatch(Object(Klein\Request))
#6 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#7 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#8 {main}


2019-01-23 11:32:00 [EXCEPTION] [N/A] Invalid Action
#0 /var/www/html/syspass/app/modules/web/Controllers/AccountController.php(745): SP\Modules\Web\Controllers\ControllerBase->checkSecurityToken(NULL, Object(SP\Http\Request))
#1 [internal function]: SP\Modules\Web\Controllers\AccountController->copyPassAction(2)
#2 /var/www/html/syspass/lib/SP/Bootstrap.php(234): call_user_func_array(Array, Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#4 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/syspass/lib/SP/Bootstrap.php(456): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#8 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#9 {main}
```

**Platform (please complete the following information):**
 - OS: Debian 9
 - OS Version: 4.9.0-8-amd64

I am not sure if I missed anything (permissions?) during the upgrade from v2 to v3? it is strange because save.config.* events are logged, but nothing else.

I would like to thank you for the great effort you are putting in v3. One of the best things about it for me is that LDAP (Group based filtering) is working as expected.

**Comment by nuxsmin** [comment]
> I would like to thank you for the great effort you are putting in v3. One of the best things about it for me is that LDAP (Group based filtering) is working as expected.

I'm glad to know this version is a noticeable step forward the previous one.

**Comment by VexedSyd** [comment]
@nuxsmin 
Many thanks for your prompt response, that was it, I didn't notice the events field although I looked at that page more than 10 times :D 

Have a good day.
