### ISSUE TITLE
Adding php7.3

### ISSUE THREAD

**Issue by andrucha97** [nuxsmin/sysPass#1269]
Hi :)

would it be possible run sysPass on php7.3? I'm trying to install it on Debian 10 but it´s showing "Required PHP version >= 7.0 <= 7.2

**Comment by andrucha97** [comment]
oh and also: Is php-7.0-mcrypt needed? I is not available since php 7.1

**Comment by nuxsmin** [comment]
Hi, 

Yes it can be installed on PHP 7.3, but isn't thoroughly test on that version.

php-mcrypt is only needed if you will import sysPass XML files from 2.0 (not 2.1) or previous versions

Regards

**Comment by andrucha97** [comment]
That sound great. Did you have an idea what I can do if I get the "error"? I'm using the newest version from Releases.

**Comment by andrucha97** [comment]
```
[Wed Feb 27 14:18:26.750790 2019] [php7:notice] [pid 20463] [client 192.168.0.187:33186] [ERROR] [SP\\Core\\Language::setLocales] Could not set locale
[Wed Feb 27 14:18:26.753030 2019] [php7:notice] [pid 20463] [client 192.168.0.187:33186] [INFO] [SP\\Core\\PhpExtensionChecker::checkMandatory] Extensions checked
[Wed Feb 27 14:18:26.753145 2019] [php7:notice] [pid 20463] [client 192.168.0.187:33186] [EXCEPTION] [N/A] Required PHP version >= 7.0 <= 7.2\n#0 /var/www/html/syspass/lib/SP/Bootstrap.php(224): SP\\Bootstrap->initializeCommon()\n#1 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#2 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#3 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#4 /var/www/html/syspass/lib/SP/Bootstrap.php(461): Klein\\Klein->dispatch(Object(Klein\\Request))\n#5 /var/www/html/syspass/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))\n#6 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')\n#7 {main}

```

**Comment by andrucha97** [comment]
I will test all function and than tell a resolution and maybe PR a change

**Comment by nuxsmin** [comment]
Hello, thanks for your contribution. PHP 7.3 will be enabled on next release, since automated tests need to be passed using every supported version.

Regards
