### ISSUE TITLE
DB backup impossible after updating to v3

### ISSUE THREAD

**Issue by mihii** [nuxsmin/sysPass#1292]
Hi, I succefully updated my system from v2 to v3. It's now impossible to perform a backup using the backup feature. When I click on Perform I get "There was an error, internal server error". Here's the log:

```
[Mon Mar 25 11:47:04.481911 2019] [php7:notice] [pid 3695] [client 10.0.0.27:58622] [EXCEPTION] [N/A] Context not initialized\n#0 /var/www/html/syspass/lib/SP/Core/Context/ContextBase.php(143): SP\\Core\\Context\\ContextBase->checkContext()\n#1 /var/www/html/syspass/lib/SP/Core/Context/SessionContext.php(100): SP\\Core\\Context\\ContextBase->getContextKey('locale', NULL)\n#2 /var/www/html/syspass/lib/SP/Core/Context/SessionContext.php(392): SP\\Core\\Context\\SessionContext->getContextKey('locale')\n#3 /var/www/html/syspass/lib/SP/Core/Language.php(209): SP\\Core\\Context\\SessionContext->getLocale()\n#4 /var/www/html/syspass/lib/SP/Providers/Log/FileLogHandler.php(104): SP\\Core\\Language->setAppLocales()\n#5 /var/www/html/syspass/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\\Providers\\Log\\FileLogHandler->updateEvent('upgrade.config....', Object(SP\\Core\\Events\\Event))\n#6 /var/www/html/syspass/lib/SP/Services/Upgrade/UpgradeConfigService.php(214): SP\\Core\\Events\\EventDispatcherBase->notifyEvent('upgrade.config....', Object(SP\\Core\\Events\\Event))\n#7 /var/www/html/syspass/lib/SP/Bootstrap.php(420): SP\\Services\\Upgrade\\UpgradeConfigService->upgrade('300.18111001', Object(SP\\Config\\ConfigData))\n#8 /var/www/html/syspass/lib/SP/Bootstrap.php(394): SP\\Bootstrap->checkConfigVersion()\n#9 /var/www/html/syspass/lib/SP/Bootstrap.php(297): SP\\Bootstrap->initConfig()\n#10 /var/www/html/syspass/lib/SP/Bootstrap.php(224): SP\\Bootstrap->initializeCommon()\n#11 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#12 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#13 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#14 /var/www/html/syspass/lib/SP/Bootstrap.php(461): Klein\\Klein->dispatch(Object(Klein\\Request))\n#15 /var/www/html/syspass/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))\n#16 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')\n#17 {main}, referer: http://10.0.0.109/syspass/index.php
[Mon Mar 25 11:47:04.482131 2019] [php7:notice] [pid 3695] [client 10.0.0.27:58622] [EXCEPTION] [N/A] Context not initialized\n#0 /var/www/html/syspass/lib/SP/Core/Context/ContextBase.php(143): SP\\Core\\Context\\ContextBase->checkContext()\n#1 /var/www/html/syspass/lib/SP/Core/Context/SessionContext.php(100): SP\\Core\\Context\\ContextBase->getContextKey('locale', NULL)\n#2 /var/www/html/syspass/lib/SP/Core/Context/SessionContext.php(392): SP\\Core\\Context\\SessionContext->getContextKey('locale')\n#3 /var/www/html/syspass/lib/SP/Core/Language.php(222): SP\\Core\\Context\\SessionContext->getLocale()\n#4 /var/www/html/syspass/lib/SP/Providers/Log/FileLogHandler.php(112): SP\\Core\\Language->unsetAppLocales()\n#5 /var/www/html/syspass/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\\Providers\\Log\\FileLogHandler->updateEvent('upgrade.config....', Object(SP\\Core\\Events\\Event))\n#6 /var/www/html/syspass/lib/SP/Services/Upgrade/UpgradeConfigService.php(214): SP\\Core\\Events\\EventDispatcherBase->notifyEvent('upgrade.config....', Object(SP\\Core\\Events\\Event))\n#7 /var/www/html/syspass/lib/SP/Bootstrap.php(420): SP\\Services\\Upgrade\\UpgradeConfigService->upgrade('300.18111001', Object(SP\\Config\\ConfigData))\n#8 /var/www/html/syspass/lib/SP/Bootstrap.php(394): SP\\Bootstrap->checkConfigVersion()\n#9 /var/www/html/syspass/lib/SP/Bootstrap.php(297): SP\\Bootstrap->initConfig()\n#10 /var/www/html/syspass/lib/SP/Bootstrap.php(224): SP\\Bootstrap->initializeCommon()\n#11 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#12 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#13 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#14 /var/www/html/syspass/lib/SP/Bootstrap.php(461): Klein\\Klein->dispatch(Object(Klein\\Request))\n#15 /var/www/html/syspass/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))\n#16 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')\n#17 {main}, referer: http://10.0.0.109/syspass/index.php
[Mon Mar 25 11:47:04.482211 2019] [php7:notice] [pid 3695] [client 10.0.0.27:58622] [ERROR] [SP\\Core\\Language::setLocales] Could not set locale, referer: http://10.0.0.109/syspass/index.php
[Mon Mar 25 11:47:04.482335 2019] [php7:notice] [pid 3695] [client 10.0.0.27:58622] [EXCEPTION] [N/A] Context not initialized\n#0 /var/www/html/syspass/lib/SP/Core/Context/ContextBase.php(143): SP\\Core\\Context\\ContextBase->checkContext()\n#1 /var/www/html/syspass/lib/SP/Core/Context/SessionContext.php(100): SP\\Core\\Context\\ContextBase->getContextKey('locale', NULL)\n#2 /var/www/html/syspass/lib/SP/Core/Context/SessionContext.php(392): SP\\Core\\Context\\SessionContext->getContextKey('locale')\n#3 /var/www/html/syspass/lib/SP/Core/Language.php(209): SP\\Core\\Context\\SessionContext->getLocale()\n#4 /var/www/html/syspass/lib/SP/Providers/Log/FileLogHandler.php(104): SP\\Core\\Language->setAppLocales()\n#5 /var/www/html/syspass/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\\Providers\\Log\\FileLogHandler->updateEvent('upgrade.config....', Object(SP\\Core\\Events\\Event))\n#6 /var/www/html/syspass/lib/SP/Services/Upgrade/UpgradeConfigService.php(222): SP\\Core\\Events\\EventDispatcherBase->notifyEvent('upgrade.config....', Object(SP\\Core\\Events\\Event))\n#7 /var/www/html/syspass/lib/SP/Bootstrap.php(420): SP\\Services\\Upgrade\\UpgradeConfigService->upgrade('300.18111001', Object(SP\\Config\\ConfigData))\n#8 /var/www/html/syspass/lib/SP/Bootstrap.php(394): SP\\Bootstrap->checkConfigVersion()\n#9 /var/www/html/syspass/lib/SP/Bootstrap.php(297): SP\\Bootstrap->initConfig()\n#10 /var/www/html/syspass/lib/SP/Bootstrap.php(224): SP\\Bootstrap->initializeCommon()\n#11 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#12 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#13 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#14 /var/www/html/syspass/lib/SP/Bootstrap.php(461): Klein\\Klein->dispatch(Object(Klein\\Request))\n#15 /var/www/html/syspass/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))\n#16 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')\n#17 {main}, referer: http://10.0.0.109/syspass/index.php
[Mon Mar 25 11:47:04.482432 2019] [php7:notice] [pid 3695] [client 10.0.0.27:58622] [EXCEPTION] [N/A] Context not initialized\n#0 /var/www/html/syspass/lib/SP/Core/Context/ContextBase.php(143): SP\\Core\\Context\\ContextBase->checkContext()\n#1 /var/www/html/syspass/lib/SP/Core/Context/SessionContext.php(100): SP\\Core\\Context\\ContextBase->getContextKey('locale', NULL)\n#2 /var/www/html/syspass/lib/SP/Core/Context/SessionContext.php(392): SP\\Core\\Context\\SessionContext->getContextKey('locale')\n#3 /var/www/html/syspass/lib/SP/Core/Language.php(222): SP\\Core\\Context\\SessionContext->getLocale()\n#4 /var/www/html/syspass/lib/SP/Providers/Log/FileLogHandler.php(112): SP\\Core\\Language->unsetAppLocales()\n#5 /var/www/html/syspass/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\\Providers\\Log\\FileLogHandler->updateEvent('upgrade.config....', Object(SP\\Core\\Events\\Event))\n#6 /var/www/html/syspass/lib/SP/Services/Upgrade/UpgradeConfigService.php(222): SP\\Core\\Events\\EventDispatcherBase->notifyEvent('upgrade.config....', Object(SP\\Core\\Events\\Event))\n#7 /var/www/html/syspass/lib/SP/Bootstrap.php(420): SP\\Services\\Upgrade\\UpgradeConfigService->upgrade('300.18111001', Object(SP\\Config\\ConfigData))\n#8 /var/www/html/syspass/lib/SP/Bootstrap.php(394): SP\\Bootstrap->checkConfigVersion()\n#9 /var/www/html/syspass/lib/SP/Bootstrap.php(297): SP\\Bootstrap->initConfig()\n#10 /var/www/html/syspass/lib/SP/Bootstrap.php(224): SP\\Bootstrap->initializeCommon()\n#11 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#12 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#13 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#14 /var/www/html/syspass/lib/SP/Bootstrap.php(461): Klein\\Klein->dispatch(Object(Klein\\Request))\n#15 /var/www/html/syspass/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))\n#16 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')\n#17 {main}, referer: http://10.0.0.109/syspass/index.php
[Mon Mar 25 11:47:04.482485 2019] [php7:notice] [pid 3695] [client 10.0.0.27:58622] [ERROR] [SP\\Core\\Language::setLocales] Could not set locale, referer: http://10.0.0.109/syspass/index.php
[Mon Mar 25 11:47:04.484684 2019] [php7:notice] [pid 3695] [client 10.0.0.27:58622] [INFO] [SP\\Core\\UI\\Theme::saveIcons] Saved icons cache, referer: http://10.0.0.109/syspass/index.php
[Mon Mar 25 11:47:04.489529 2019] [php7:notice] [pid 3695] [client 10.0.0.27:58622] [INFO] [SP\\Core\\Acl\\Actions::loadCache] Loaded actions cache, referer: http://10.0.0.109/syspass/index.php
[Mon Mar 25 11:47:06.512502 2019] [php7:error] [pid 3695] [client 10.0.0.27:58622] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 36864 bytes) in /var/www/html/syspass/lib/SP/Storage/File/ArchiveHandler.php on line 92, referer: http://10.0.0.109/syspass/index.php
```

PHP memory limit is 512M. Any suggestions? What are those errors?

**Comment by nuxsmin** [comment]
Hi, it seems a memory limit issue though you told that it's set to 512MB, but the error states `Allowed memory size of 134217728 bytes exhausted` and it's the default value for a normal PHP installation (128MB)

Could you check whether the new value is actually set?

Regards
