### ISSUE TITLE
Random "Invalid Action" upon saving passwords

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#1312]
**sysPass Version**
305.19020701
3.0 (305.19020701) Config: 300.18112501 App: 300.18072902 DB: 300.18111901
Base de données | SERVER_VERSION : 5.5.60-MariaDB CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407
PHP 7.2.10

**Describe the bug**
When saving URLs / passwords in existant accounts, I randomly have an error "Invalid Action" in the GUI. If I happen to reproduce the same action seconds later, it works.
I have searched my apache logs, nothing in the timeframe where the error happened.
Both actions (the first failed attempt with Invalid Action, and the second attempt that succeed) seem to have have been executed by apache:
```
XX.XX.XX.XX - - [10/Apr/2019:08:50:07 +0200] "POST /index.php?r=account/saveEdit/3255 HTTP/1.1" 200 145 "https://my.syspass.local/index.php?r=index" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.127"
XX.XX.XX.XX - - [10/Apr/2019:08:54:05 +0200] "POST /index.php?r=account/saveEdit/3255 HTTP/1.1" 200 193 "https://my.syspass.local/index.php?r=index" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.127"
```

Furthermore, I have searched my mod_security logs, nothing there too.
I have a couple of the following PHP errors, but they don't occur at the same time the account edition failed:
```
[10-Apr-2019 08:51:37 UTC] [EXCEPTION] [N/A] Integrity check failed.
```

Can you point me in any direction to search please ?

**Event log**
```
2019-04-10 06:50:07 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-04-10 06:50:07 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-04-10 06:50:07 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-04-10 06:50:07 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-04-10 06:50:09 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-04-10 06:50:09 [EXCEPTION] [N/A] Action Invalide
#0 /var/www/my.sys.fr/ftp/www/app/modules/web/Controllers/AccountController.php(865): SP\Modules\Web\Controllers\ControllerBase->checkSecurityToken('79d2c4968e2afa1...', Object(SP\Http\Request))
#1 [internal function]: SP\Modules\Web\Controllers\AccountController->saveEditAction(3255)
#2 /var/www/my.sys.fr/ftp/www/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#4 /var/www/my.sys.fr/ftp/www/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/my.sys.fr/ftp/www/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/my.sys.fr/ftp/www/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/my.sys.fr/ftp/www/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#8 /var/www/my.sys.fr/ftp/www/index.php(28): require('/var/www/my.sys...')
#9 {main}
2019-04-10 06:50:22 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-04-10 06:50:22 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-04-10 06:50:22 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-04-10 06:50:25 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-04-10 06:50:25 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-04-10 06:50:25 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
```

**Platform (please complete the following information):**
 - OS: CentOS 7 x64 uptodate
 - Opera 58 (also happens with Firefox)

Best regards.

**Comment by nuxsmin** [comment]
Hello, this behavior has been tracked since a time ago, and it seems to be related to the refresh of the security token after an AJAX request, since it should update a DOM element to tell the browser which is the new token.

I'll try to improve this behavior in next release.

Thanks for the feedback!

**Comment by deajan** [comment]
Can this be fixed for v3.1 ?
This is the kind of random issue that sysadmins nightmares are made of.

**Comment by nuxsmin** [comment]
Hello, I know it could be a nightmare indeed... 

I'll try to code a tweak, but I'm not sure about implementing it in this release, since this version was released out because there were many important fixes and a major code change about plugins data structure, so I decided not to take so much time for releasing it out.

I'm really commited to solve it but I need to analyze how much it would break the code base, since it involves many JavaScript changes and server side code.

Regards

**Comment by deajan** [comment]
Willing to make all necessary tests if needed.

**Comment by vmario89** [comment]
i can confirm that this happens really really often in our instance since all versions of sysPass i updated to. Its annoying because somethings i have to click change password 5 times until the error disappears

**Comment by deajan** [comment]
Still happening on my 3 instances too.
@nuxsmin willing to help by donating if needed

**Comment by Hr46ph** [comment]
Some time has passed, we get the issue too (30 to 35 users) and I've been questions from users about it.

It would be nice if this issue could get fixed.

**Comment by phil4096** [comment]
I seem to have a similar issue.  New install (just for testing) on Debian 10, using Chrome browser.  After setting up a new local user, the session timed out. Now I can't login - I get "Invalid Action" whether login credentials are good or bad.  If I open Firefox on the same machine, I can login ok.

**Comment by Hr46ph** [comment]
> I seem to have a similar issue. New install (just for testing) on Debian 10, using Chrome browser. After setting up a new local user, the session timed out. Now I can't login - I get "Invalid Action" whether login credentials are good or bad. If I open Firefox on the same machine, I can login ok.

It seems like you have multiple issues. The invalid action could be related but after hitting F5 (refresh) and logging in again it should work. If that doesn't work with Chrome, I think you're likely having another issue specifically with Chrome. I'd look into that if I were you.

**Comment by FcoCosco** [comment]
Hello, i still have this issue using the 3.1 version. Someone find a workaround to this problem?
