### ISSUE TITLE
syspass.log saves LDAP passwords

### ISSUE THREAD

**Issue by ivanmol** [nuxsmin/sysPass#1367]
**sysPass Version**
3.0 (305.19020701) 

**Describe the bug**
The `syspass.log` file under `sysPass/app/config/` saves incorrect password attempts in plaintext when using LDAP auth. This occurs even when debug mode is turned off.

This is a security risk since incorrect password attempts are often typos, meaning that the logfile contains passwords that are very similar to the user's actual password.

**To Reproduce**

**Expected behavior**
The line in the log file should not include the password the user entered, even if incorrect.

**Event log**
```
#0 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/Ldap.php(140): SP\Providers\Auth\Ldap\LdapConnection->bind('CN=NAME,...', 'PASSWORD IN PLAINTEXT...')
#1 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/LdapAuth.php(123): SP\Providers\Auth\Ldap\Ldap->bind('CN=NAME,...', 'PASSWORD IN PLAINTEXT...')
#2 /var/www/html/sysPass/lib/SP/Providers/Auth/AuthProvider.php(115): SP\Providers\Auth\Ldap\LdapAuth->authenticate(Object(SP\DataModel\UserLoginData))
#3 /var/www/html/sysPass/lib/SP/Providers/Auth/AuthProvider.php(93): SP\Providers\Auth\AuthProvider->authLdap()
#4 /var/www/html/sysPass/lib/SP/Services/Auth/LoginService.php(146): SP\Providers\Auth\AuthProvider->doAuth(Object(SP\DataModel\UserLoginData))
#5 /var/www/html/sysPass/app/modules/web/Controllers/LoginController.php(62): SP\Services\Auth\LoginService->doLogin()
#6 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#7 /var/www/html/sysPass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#8 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Kl
ein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(K
lein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\Rout
eCollection), Array)
#11 /var/www/html/sysPass/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#12 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#13 /var/www/html/sysPass/index.php(28): require('/var/www/html/s...')
#14 {main}
2019-06-10 11:05:45 [EXCEPTION] [N/A] Wrong login
```

**Platform (please complete the following information):**
 - OS: CentOS Linux 7
 - All browsers

**Comment by nuxsmin** [comment]
Hello, this behaviour has been changed in latest 3.1-RC4 version.

Regards
