### ISSUE TITLE
DB connection issue when install syspass:3.1.0-rc4

### ISSUE THREAD

**Issue by Envikia** [nuxsmin/sysPass#1383]
**sysPass Version**
syspass:3.1.0-rc4

**Describe the bug**
image: mariadb:10.4
My database is functional with install syspass:3.0.5
I empty the database and use the same credential to fresh install syspass:3.1.0-rc4, the syspass app returned DB connection issue. Is there any compatible between syspass:3.1.0-rc4 and any version of DB? Thanks.

**Event log**
```
[Wed Jul 03 16:47:27.400188 2019] [:error] [pid 713] [client 172.18.0.2:48470] [EXCEPTION] [Unable to connect to DB\n#0 /var/www/html/sysPass/lib/SP/Storage/Database/DatabaseUtil.php(119): SP\\Storage\\Database\\MySQLHandler->getConnection()\n#1 /var/www/html/sysPass/app/modules/web/Init.php(191): SP\\Storage\\Database\\DatabaseUtil->checkDatabaseConnection()\n#2 /var/www/html/sysPass/lib/SP/Bootstrap.php(232): SP\\Modules\\Web\\Init->initialize(String)\n#3 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)\n#4 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)\n#5 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route),Object(Klein\\DataCollection\\RouteCollection),Array)\n#6 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\\Klein->dispatch(Object(Klein\\Request))\n#7 /var/www/html/sysPass/lib/Base.php(75): SP\\Bootstrap->run(Object(DI\\Container))\n#8 /var/www/html/sysPass/index.php(28): require(String)] N/A, referer: https://mysite.mydomain.com/index.php?r=install/index
[Wed Jul 03 16:47:27.400231 2019] [:error] [pid 713] [client 172.18.0.2:48470] [ERROR] [Database connection error] SP\\Modules\\Web\\Init::initialize, referer: https://mysite.mydomain.com/index.php?r=install/index
```

**Comment by Envikia** [comment]
Since syspass:3.1.0-rc5 is released, Let me close this issue, will create another issue if still exists, thanks!
