### ISSUE TITLE
"Error when applying the database update" from sysPass 2.1.16 to 3.0.0

### ISSUE THREAD

**Issue by asir214** [nuxsmin/sysPass#1384]
**sysPass Version**
sysPass 3.0.0

**Describe the bug**
We are updating the version of syspass from 2.1.16 to 3.0.0, everything is fine until the moment of updating the database.

**To Reproduce**

1. Go to the url of the web of the application

2. Put the upgradekey and then give the update button

**Expected behavior**
We expected the application to be updated.

**Screenshots**
![syspass](https://user-images.githubusercontent.com/39795205/60662770-8f030e00-9e5d-11e9-831b-fe35d8218a68.png)

**Event log**
[2019-07-04 12:15:25] syspass.ERROR: logger {"message":"Could not set locale","caller":"SP\Core\Language::setLocales"}
[2019-07-04 12:15:25] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2019-07-04 12:15:25] syspass.INFO: logger {"message":"Saved icons cache","caller":"SP\Core\UI\Theme::saveIcons"}
[2019-07-04 12:15:25] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2019-07-04 12:15:25] syspass.DEBUG: upgrade.db.start {"message":"Actualizar BBDD","user":"N/A","address":"192.168.50.221","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::upgrade"} []
[2019-07-04 12:15:25] syspass.DEBUG: upgrade.db.process {"message":"Versión: 300.18010101","user":"N/A","address":"192.168.50.221","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-07-04 12:15:25] syspass.DEBUG: upgrade.db.process {"message":"Versión: 300.18010101","user":"N/A","address":"192.168.50.221","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-07-04 12:15:25] syspass.DEBUG: upgrade.db.process {"message":"Versión: 300.18010101","user":"N/A","address":"192.168.50.221","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-07-04 12:15:25] syspass.DEBUG: upgrade.db.process {"message":"Versión: 300.18010101","user":"N/A","address":"192.168.50.221","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-07-04 12:15:25] syspass.DEBUG: upgrade.db.process {"message":"Versión: 300.18010101","user":"N/A","address":"192.168.50.221","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-07-04 12:15:25] syspass.DEBUG: upgrade.db.process {"message":"Versión: 300.18010101","user":"N/A","address":"192.168.50.221","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-07-04 12:15:25] syspass.DEBUG: upgrade.db.process {"message":"Versión: 300.18010101","user":"N/A","address":"192.168.50.221","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-07-04 12:15:25] syspass.DEBUG: upgrade.db.process {"message":"Versión: 300.18010101","user":"N/A","address":"192.168.50.221","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-07-04 12:15:25] syspass.DEBUG: upgrade.db.process {"message":"Versión: 300.18010101","user":"N/A","address":"192.168.50.221","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-07-04 12:15:25] syspass.DEBUG: upgrade.db.process {"message":"Versión: 300.18010101","user":"N/A","address":"192.168.50.221","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-07-04 12:15:25] syspass.DEBUG: upgrade.db.process {"message":"Versión: 300.18010101","user":"N/A","address":"192.168.50.221","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-07-04 12:15:25] syspass.EXCEPTION: logger {"message":"SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'customfieldtype' already exists
#0 /var/www/syspass/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(173): PDO->exec(String)
#1 /var/www/syspass/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(108): SP\Services\Upgrade\UpgradeDatabaseService->applyUpgrade(String)
#2 /var/www/syspass/app/modules/web/Controllers/UpgradeController.php(89): SP\Services\Upgrade\UpgradeDatabaseService->upgrade(String,Object(SP\Config\ConfigData))
#3 [internal function]: SP\Modules\Web\Controllers\UpgradeController->upgradeAction()
#4 /var/www/syspass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#5 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#8 /var/www/syspass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#9 /var/www/syspass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#10 /var/www/syspass/index.php(28): require(String)","caller":"N/A"}
[2019-07-04 12:15:25] syspass.EXCEPTION: logger {"message":"Error al aplicar la actualización de la Base de Datos
#0 /var/www/syspass/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(108): SP\Services\Upgrade\UpgradeDatabaseService->applyUpgrade(String)
#1 /var/www/syspass/app/modules/web/Controllers/UpgradeController.php(89): SP\Services\Upgrade\UpgradeDatabaseService->upgrade(String,Object(SP\Config\ConfigData))
#2 [internal function]: SP\Modules\Web\Controllers\UpgradeController->upgradeAction()
#3 /var/www/syspass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/syspass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/syspass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#9 /var/www/syspass/index.php(28): require(String)","caller":"N/A"}

**Platform (please complete the following information):**
 - OS: Debian
 - OS Version: 9.5
 - Browser: Chrome

**Additional context**

**Comment by nuxsmin** [comment]
Hello, did you try to apply an upgrade over a failed one?. If so, some database changes cannot be rolled back automatically, so you'll need to restore the database and then perform the upgrade process again.

Regards

**Comment by duven87** [comment]
Just `mysql_upgrade -u root -p`

**Comment by duven87** [comment]
Hola Ruben!
Today I upgrated syspass from 2.1 to 3 and after 3.2.
All seems good.
Just when I see syspass.log always appears:
[2021-04-01 16:53:30] syspass.ERROR: logger {"message":"Could not set locale","caller":"SP\Core\Language::setLocales"}
Its the unique error that I have but syspass works fine.
How can I solve it?

Gracias! Nos vemos!
