### ISSUE TITLE
Upgrade from 2.1 to 3.0 gives "Error while updating the database"

### ISSUE THREAD

**Issue by bitking** [nuxsmin/sysPass#1404]
**Syspass Version:** 2.1 (2.1.14.17090102)

When trying to upgrade Syspass 2.1 to 3.0 i get the following error:
Error while updating the database.

What is going wrong here?

**In app/config/syspass.log i see the following:**
[2019-07-25 17:44:07] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2019-07-25 17:44:07] syspass.INFO: logger {"message":"Saved icons cache","caller":"SP\Core\UI\Theme::saveIcons"}
[2019-07-25 17:44:07] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2019-07-25 17:44:07] syspass.DEBUG: upgrade.db.start {"message":"Update DB","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::upgrade"} []
[2019-07-25 17:44:07] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:07] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:07] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:07] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:07] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:07] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:07] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:07] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:07] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:07] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:09] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:09] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:09] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:09] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:09] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:10] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:10] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:11] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:11] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:11] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:11] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:11] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:11] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:12] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:12] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:12] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:12] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:12] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:12] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:13] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:13] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:13] syspass.EXCEPTION: logger {"message":"SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'dateEdit' at row 1
#0 /var/www/html/syspass3/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(173): PDO->exec(String)
#1 /var/www/html/syspass3/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(108): SP\Services\Upgrade\UpgradeDatabaseService->applyUpgrade(String)
#2 /var/www/html/syspass3/app/modules/web/Controllers/UpgradeController.php(89): SP\Services\Upgrade\UpgradeDatabaseService->upgrade(String,Object(SP\Config\ConfigData))
#3 [internal function]: SP\Modules\Web\Controllers\UpgradeController->upgradeAction()
#4 /var/www/html/syspass3/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#5 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollectio
n\RouteCollection),Array)
#6 /var/www/html/syspass3/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\
App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/html/syspass3/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#8 /var/www/html/syspass3/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#9 /var/www/html/syspass3/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#10 /var/www/html/syspass3/index.php(28): require(String)","caller":"N/A"}
[2019-07-25 17:44:13] syspass.EXCEPTION: logger {"message":"Error while updating the database
#0 /var/www/html/syspass3/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(108): SP\Services\Upgrade\UpgradeDatabaseService->applyUpgrade(String)
#1 /var/www/html/syspass3/app/modules/web/Controllers/UpgradeController.php(89): SP\Services\Upgrade\UpgradeDatabaseService->upgrade(String,Object(SP\Config\ConfigData))
#2 [internal function]: SP\Modules\Web\Controllers\UpgradeController->upgradeAction()
#3 /var/www/html/syspass3/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollectio
n\RouteCollection),Array)
#5 /var/www/html/syspass3/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\
App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/syspass3/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/html/syspass3/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/syspass3/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#9 /var/www/html/syspass3/index.php(28): require(String)","caller":"N/A"}
[2019-07-25 17:44:32] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2019-07-25 17:44:32] syspass.INFO: logger {"message":"Saved icons cache","caller":"SP\Core\UI\Theme::saveIcons"}
[2019-07-25 17:44:32] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2019-07-25 17:44:32] syspass.DEBUG: upgrade.db.start {"message":"Update DB","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::upgrade"} []
[2019-07-25 17:44:32] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:32] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:32] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:32] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:32] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:32] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:32] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:32] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:32] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:32] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:32] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"10.200.200.183","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::ap
plyUpgrade"} []
[2019-07-25 17:44:32] syspass.EXCEPTION: logger {"message":"SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'CustomFieldType' already exists

**Comment by bitking** [comment]
It was Mysql strict mode.

https://askubuntu.com/questions/811831/whats-the-correct-way-to-revert-mysql-5-7-strict-mode-back-to-how-it-was-in-5-6

&

#478
