### ISSUE TITLE
Error while saving

### ISSUE THREAD

**Issue by andrucha97** [nuxsmin/sysPass#1410]
**sysPass Version**

3.1-RC5 (310.19072001) 
Config: 305.19020701 
App: 310.19042701 
DB: 310.19042701

**Describe the bug**

As soon as I change or create entries I get an error message that this action is invalid. If I try to save it again it gets accepted.

**To Reproduce**
1. Edit a Account
2. Disable Privat for Group
3. Save
5. Save again -> Works

**Event log**

```
[2019-07-30 10:49:28] syspass.EXCEPTION: logger {"message":"Ungültige Aktion
#0 /var/www/html/app/modules/web/Controllers/AccountController.php(876): SP\Modules\Web\Controllers\ControllerBase->checkSecurityToken(String,Object(SP\Http\Request))
#1 [internal function]: SP\Modules\Web\Controllers\AccountController->saveEditAction(Integer)
#2 /var/www/html/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#4 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/html/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#8 /var/www/html/index.php(28): require(String)","caller":"N/A"}
[2019-07-30 10:49:28] syspass.ERROR: exception {"message":"Ungültige Aktion","user":"andreas","address":"192.168.0.127","caller":"SP\\Modules\\Web\\Controllers\\AccountController::saveEditAction"} []
[2019-07-30 10:49:28] syspass.ERROR: exception {"message":"Ungültige Aktion","user":"andreas","address":"192.168.0.127","caller":"SP\\Modules\\Web\\Controllers\\AccountController::saveEditAction"} []
```

**Platform (please complete the following information):**
 - OS: Linux
 - OS Version: Ubuntu 18.04
 - Browser: Chrome

**Comment by nuxsmin** [comment]
Duplicated #1312
