### ISSUE TITLE
Wrong return data/code when calling API without permissions

### ISSUE THREAD

**Issue by matejzero** [nuxsmin/sysPass#1429]
**sysPass Version**
3.1 (310.19081801) 

**Describe the bug**
When I'm calling API without the right permission, I get `Internal server error` JSON response and 200 HTTP code.

I have an API user with `View account` permission. I'm calling the following curl:
```bash
curl -v \
  -H "Content-Type: application/json" \
  -XPOST \
  https://server/api.php -d'{
  "jsonrpc": "2.0",
  "method": "account/search",
  "params": {
    "authToken": "xxxxxxxxxx"
  },
  "id": 1
}'
```

In return, I get 
```
* upload completely sent off: 166 out of 166 bytes
< HTTP/1.1 200 OK
< Date: Wed, 21 Aug 2019 05:00:36 GMT
< Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.1.30
< X-Powered-By: PHP/7.1.30
< Content-Length: 82
< Content-Type: application/json; charset=utf-8
<
* Connection #0 to host server left intact
{"jsonrpc":"2.0","error":{"message":"Internal error","code":0,"data":null},"id":1}%
```
I would expect either:
- return code 500 with the same error (less useful)
- return code 403 with "no permission" or something along this line (more useful).

**To Reproduce**

Run the same curl query with same permissions API key, I think it should be reproducable.

**Event log**
```
[2019-08-21 05:10:24] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2019-08-21 05:10:24] syspass.EXCEPTION: logger {"message":"Internal error
#0 /var/www/html/syspass/lib/SP/Services/Api/ApiService.php(106): SP\Services\AuthToken\AuthTokenService->getTokenByToken(Integer,String)
#1 /var/www/html/syspass/app/modules/api/Controllers/ControllerBase.php(134): SP\Services\Api\ApiService->setup(Integer)
#2 /var/www/html/syspass/app/modules/api/Controllers/AccountController.php(263): SP\Modules\Api\Controllers\ControllerBase->setupApi(Integer)
#3 [internal function]: SP\Modules\Api\Controllers\AccountController->searchAction()
#4 /var/www/html/syspass/lib/SP/Bootstrap.php(181): call_user_func(Array)
#5 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#8 /var/www/html/syspass/lib/SP/Bootstrap.php(470): Klein\Klein->dispatch(Object(Klein\Request))
#9 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#10 /var/www/html/syspass/api.php(28): require(String)","caller":"N/A"}
```

**Platform (please complete the following information):**
 - OS: Linux
 - OS Version: CentOS 7

**Comment by nuxsmin** [comment]
Hello, please be aware that it implements the JSON-RPC spec so it won't return any HTTP response code like a REST API.

Anyway it should return a JSON-RPC internal error, because there's no mapping to "forbidden - 403" or "unauthorized - 401" errors, so it would throw "-32603" error code.

https://www.jsonrpc.org/specification#error_object

Thanks for the feedback!

**Comment by matejzero** [comment]
Oooh, I'm sorry, I'm not familiar with JSON-RPC and I was expecting the same behaviour.

So HTTP error code should still be 200, but `code` parameter should be `-32603`?
