### ISSUE TITLE
Unable to import passwords

### ISSUE THREAD

**Issue by matejzero** [nuxsmin/sysPass#1443]
**sysPass Version**
3.1 (310.19081801) 

**Describe the bug**
I have a user with full accounts privileges and import privilege. When importing a CSV file, I get an error
```
There was an error
Service Unavailable

Invalid Action
```

**To Reproduce**
1. Create a user with full accounts privileges and import privileges.
2. Create a CSV file with some accounts
3. Go to import accounts
4. Try to import
5. See error

**Expected behavior**
I expected to be able to import accounts. I can do it with a user who has Admin profile.

**Log**
```
[2019-08-29 07:47:03] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2019-08-29 07:47:03] syspass.INFO: logger {"message":"Loaded icons cache","caller":"SP\Core\UI\Theme::initIcons"}
[2019-08-29 07:47:03] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2019-08-29 07:47:03] syspass.EXCEPTION: logger {"message":"Invalid Action
#0 /var/www/html/syspass/app/modules/web/Controllers/ConfigImportController.php(59): SP\Modules\Web\Controllers\SimpleControllerBase->checkSecurityToken(String,Object(SP\Http\Request))
#1 [internal function]: SP\Modules\Web\Controllers\ConfigImportController->importAction()
#2 /var/www/html/syspass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#4 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/syspass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#8 /var/www/html/syspass/index.php(28): require(String)","caller":"N/A"}
```

**Platform (please complete the following information):**
- OS: Linux
- Installation: standalone
- Browser: Chrome

**Comment by nuxsmin** [comment]
Hello, this kind of error is mostly caused by an expired token when submitting the CSV file. Did you try it once again?

Regards

**Comment by matejzero** [comment]
This was done right after signing into the app.

I used an admin account and was able to import the file, so I didn't debug further, sorry.

**Comment by nuxsmin** [comment]
So did it succeed at last?

**Comment by matejzero** [comment]
I logged out with the user and logged in with admin account and that worked.

I'll try a test import with a custom user again tomorrow and report back. Just to rule out the issue about expired toked.
