### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by ecojpm** [nuxsmin/sysPass#1455]
**sysPass Version**
Can be found on `Config -> 3.1 (310.19081801)

**Describe the bug**
When uploading a file i receive "Internal error while uploading file"

**To Reproduce**
1. Create new account
2. Modify account and click on files tab
3. upload a binary file (vpn client)
4. get error

**Expected behavior**
store the file in server or database
![Screenshot_4](https://user-images.githubusercontent.com/55194584/64701096-65dbab00-d4a8-11e9-915a-f83ead6c57f6.png)

**Screenshots**

**Event log**
[2019-09-11 15:25:12] syspass.EXCEPTION: logger {"message":"Error interno al leer el archivo
#0 [internal function]: SP\Modules\Web\Controllers\AccountFileController->uploadAction(Integer)
#1 /var/www/consultoria.ovh/itsm/html/apps/syspass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#2 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#3 /var/www/consultoria.ovh/itsm/html/apps/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#4 /var/www/consultoria.ovh/itsm/html/apps/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/consultoria.ovh/itsm/html/apps/syspass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#6 /var/www/consultoria.ovh/itsm/html/apps/syspass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#7 /var/www/consultoria.ovh/itsm/html/apps/syspass/index.php(28): require(String)","caller":"N/A"}

**Platform (please complete the following information):**
 - OS: ubuntu server
 - OS 16.04
 - Browser Chrome

**Additional context**

**Comment by nuxsmin** [comment]
Hello, could you add some more lines from syspass.log file?. It's not clear why it was unable to process the file.

Regards

**Comment by ecojpm** [comment]
well that's what the syspass.log log says

**Comment by nuxsmin** [comment]
Could you reproduce it on demo site?. Is it caused by any binary file?

**Comment by ecojpm** [comment]
[SecuExtender IPSecVPN_Windows 3.8.204.61.32.exe.zip](https://github.com/nuxsmin/sysPass/files/3602292/SecuExtender.IPSecVPN_Windows.3.8.204.61.32.exe.zip)

I try with this file but in 7z format, other files in same format but lower size works fine

I can't reproduce it in demo since is 1024kb max file size and cant be increased by demo user

app/modules/web/Controllers/AccountFileController.php

if it helps, looks like $fileHandler = new FileHandler($file['tmp_name']); deletes the file before than $fileData->setContent() tries to read its content

i checked tmp folder and has permissions

**Comment by ecojpm** [comment]
also i verified in php.ini that memory_limit is -1

**Comment by nuxsmin** [comment]
Hmm, not sure about the JavaScript side, because the file is received by PHP but 'tmp_file' is not being filled out, so something might be happening on server side, since a tmp file should created after uploaded to the server.

Thanks for the feedback!
