### ISSUE TITLE
API Call: Oops, it looks like this content does not exist...

### ISSUE THREAD

**Issue by rldourado** [nuxsmin/sysPass#1456]
Docker Container
Version: syspass/syspass:3.1.0-php7.3

When I call any API, with the command:

```curl -v -k --header 'Accept: */*' --header 'Cache-Control: no-cache' --header 'Content-Type: application/json' --request POST --data '{ "jsonrpc": "2.0", "method": "account/search", "params": { "authToken": "##########" }, "id": "1" }' https://##########/api.php```

 it returns

```{"jsonrpc":"2.0","error":{"message":"Internal error","code":0,"data":null},"id":1}```

The complete log from curl:

```
*   Trying ##########...
* TCP_NODELAY set
* Connected to ########## (##########) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.mppe.mp.br
*  start date: Sep 26 00:00:00 2018 GMT
*  expire date: Sep 25 23:59:59 2020 GMT
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> POST /api.php HTTP/1.1
> Host: ##########
> User-Agent: curl/7.58.0
> Accept: */*
> Cache-Control: no-cache
> Content-Type: application/json
> Content-Length: 154
>
* upload completely sent off: 154 out of 154 bytes
< HTTP/1.1 200 OK
< Date: Wed, 11 Sep 2019 19:55:25 GMT
< Server: Apache/2.4.25 (Debian)
< X-Powered-By: PHP/7.3.8
< Content-Length: 82
< Content-Type: application/json; charset=utf-8
<
* Connection #0 to host ########## left intact
{"jsonrpc":"2.0","error":{"message":"Internal error","code":0,"data":null},"id":1}
```

The SysPass Log:

```
[2019-09-11 19:55:25] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2019-09-11 19:55:25] syspass.EXCEPTION: logger {"message":"Internal error
#0 /var/www/html/sysPass/lib/SP/Services/Api/ApiService.php(106): SP\Services\AuthToken\AuthTokenService->getTokenByToken(Integer,String)
#1 /var/www/html/sysPass/app/modules/api/Controllers/ControllerBase.php(134): SP\Services\Api\ApiService->setup(Integer)
#2 /var/www/html/sysPass/app/modules/api/Controllers/AccountController.php(263): SP\Modules\Api\Controllers\ControllerBase->setupApi(Integer)
#3 [internal function]: SP\Modules\Api\Controllers\AccountController->searchAction()
#4 /var/www/html/sysPass/lib/SP/Bootstrap.php(181): call_user_func(Array)
#5 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Kl
ein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\
ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCol
lection),Array)
#8 /var/www/html/sysPass/lib/SP/Bootstrap.php(470): Klein\Klein->dispatch(Object(Klein\Request))
#9 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#10 /var/www/html/sysPass/api.php(28): require(String)","caller":"N/A"}
[2019-09-11 19:56:03] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2019-09-11 19:56:03] syspass.INFO: logger {"message":"Loaded icons cache","caller":"SP\Core\UI\Theme::initIcons"}
[2019-09-11 19:56:03] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadC
```

If I try to call /api.php in the browser, it returns:

```
Warning: dir(/var/www/html/sysPass/app/modules/api/plugins): failed to open dir: No such file or directory in /var/www/html/sysPass/lib/SP/Plugin/PluginManager.php on line 112
Oops, it looks like this content does not exist...
```

The same happens when I try 'config/backup' as well. It worked on previous versions of SysPass.

**Comment by nuxsmin** [comment]
Hello, it seems to throw an error because an invalid auth token. Did you recently upgrade sysPass?

Regards

**Comment by Ajtak** [comment]
Same problem on latest docker image.

**Comment by nuxsmin** [comment]
Solved in latest release
