### ISSUE TITLE
syspass.log is flooded

### ISSUE THREAD

**Issue by ednt** [nuxsmin/sysPass#1460]
Updated to the latest version 3.1.0 19081801

I see a lot of exception inside the log with 'context not initialized'. How can I fix it?

```
[2019-09-17 13:42:27] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2019-09-17 13:42:27] syspass.EXCEPTION: logger {"message":"Context not initialized
#0 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/ContextBase.php(143): SP\Core\Context\ContextBase->checkContext()
#1 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(100): SP\Core\Context\ContextBase->getContextKey(String,NULL)
#2 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(392): SP\Core\Context\SessionContext->getContextKey(String)
#3 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Language.php(211): SP\Core\Context\SessionContext->getLocale()
#4 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Providers/Log/LoggerBase.php(78): SP\Core\Language->setAppLocales()
#5 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\Providers\Log\LoggerBase->updateEvent(String,Object(SP\Core\Events\Event))
#6 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Services/Upgrade/UpgradeConfigService.php(216): SP\Core\Events\EventDispatcherBase->notifyEvent(String,Object(SP\Core\Events\Event))
#7 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(423): SP\Services\Upgrade\UpgradeConfigService->upgrade(String,Object(SP\Config\ConfigData))
#8 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(397): SP\Bootstrap->checkConfigVersion()
#9 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(300): SP\Bootstrap->initConfig()
#10 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(227): SP\Bootstrap->initializeCommon()
#11 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#12 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#13 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#14 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#15 /var/www/html/sysPass-3.1.0.19081801/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#16 /var/www/html/sysPass-3.1.0.19081801/index.php(28): require(String)","caller":"N/A"}
```

Or

```
[2019-09-17 13:42:27] syspass.EXCEPTION: logger {"message":"Kontext wurde nicht initialisiert
#0 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/ContextBase.php(143): SP\Core\Context\ContextBase->checkContext()
#1 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(100): SP\Core\Context\ContextBase->getContextKey(String,Object(SP\Services\User\UserLoginResponse))
#2 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(232): SP\Core\Context\SessionContext->getContextKey(String,Object(SP\Services\User\UserLoginResponse))
#3 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Providers/Log/LoggerBase.php(80): SP\Core\Context\SessionContext->getUserData()
#4 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\Providers\Log\LoggerBase->updateEvent(String,Object(SP\Core\Events\Event))
#5 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Services/Upgrade/UpgradeConfigService.php(216): SP\Core\Events\EventDispatcherBase->notifyEvent(String,Object(SP\Core\Events\Event))
#6 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(423): SP\Services\Upgrade\UpgradeConfigService->upgrade(String,Object(SP\Config\ConfigData))
#7 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(397): SP\Bootstrap->checkConfigVersion()
#8 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(300): SP\Bootstrap->initConfig()
#9 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(227): SP\Bootstrap->initializeCommon()
#10 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#11 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#12 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#13 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#14 /var/www/html/sysPass-3.1.0.19081801/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#15 /var/www/html/sysPass-3.1.0.19081801/index.php(28): require(String)","caller":"N/A"}
```

Linux Debian 10 with latest updates
Access via FireFox latest version

In general syspass works. But many many log entries.

Also if I call /api I get a 403 forbidden.
I also can see entries of api with context not initialized.
But maybe that's an other problem.

**Comment by nuxsmin** [comment]
Hello, this kind of exceptions could be skipped, since they're caused by the language setting workflow, but it seems that your sysPass instance is trying to upgrade the config version, so when it tries to write the message into the log, the user's session (ie. context) is not available for getting the language set. I'm wondering why it complains about the config version. Could you send me the versions within the `syspass.xml` file?

Regards

**Comment by tanmarpaul** [comment]
Hello, I'm getting the same issue.

I assume you with `syspass.xml` you meant `app/config/config.xml` ?
```
<appVersion>310.19042701</appVersion>
<configVersion>300.18111001</configVersion>
<databaseVersion>310.19042701</databaseVersion>
```

Regards

**Comment by ednt** [comment]
I have exactly the same versions and up to now no solution.

Sometimes I need to do a search for an entry twice to get the results.

**Comment by tanmarpaul** [comment]
I changed the value in the `config.xml` to be `310.19042701` for all 3 and I don't get the error flood anymore but I didn't have the issue when searching.

Regards.

**Comment by nuxsmin** [comment]
Thanks for the feedback!
