### ISSUE TITLE
[Bug] Can't restore backup

### ISSUE THREAD

**Issue by Nebucatnetzer** [nuxsmin/sysPass#1492]
**sysPass Version**
3.1

**Describe the question**
How do correctly restore a backup?

When I tried to do it I get the error message below and a 404 error from Nginx.
The steps I do are the following:
1. A server which makes a daily backup with a cronjob.
2. I then download the backups and copy them into a new VM.
3. Extract the application to /var/www/syspass
4. Make some changes to the config.xml (change the URL, disable AD login).
5. Import the database with sudo mysql < /path/to/syspass.sql
6. Go to the URL of the new VM and try to login with the admin account. Now I get the 404 error.

I noticed that it wants to access a table which it can't find, however I couldn't find the word Track anywhere in the DB dump.

**Platform (please complete the following information):**
- The server and the VM are a Ubuntu 18.04 machine.

**Additional context**
It seems that #1469 has the same problem.
Log message which gets throw before the 404 happens:

```
2019/11/18 15:00:42 [error] 1324#1324: *29 FastCGI sent in stderr: "PHP message: [INFO] [Extensions checked] SP\Core\PhpExtensionChecker::checkMandatory                          
PHP message: [INFO] [Loaded icons cache] SP\Core\UI\Theme::initIcons                                                                                                              
PHP message: [INFO] [Loaded actions cache] SP\Core\Acl\Actions::loadCache                                                                                                         
PHP message: [EXCEPTION] [SQLSTATE[42S02]: Base table or view not found: 1146 Table 'syspassdb.Track' doesn't exist                                                               
#0 /var/www/syspass/lib/SP/Storage/Database/Database.php(219): PDO->prepare(String,Array)                                                                                         
#1 /var/www/syspass/lib/SP/Storage/Database/Database.php(175): SP\Storage\Database\Database->prepareQueryData(Object(SP\Storage\Database\QueryData))                              
#2 /var/www/syspass/lib/SP/Storage/Database/Database.php(136): SP\Storage\Database\Database->doQuery(Object(SP\Storage\Database\QueryData))                                       
#3 /var/www/syspass/lib/SP/Repositories/Track/TrackRepository.php(204): SP\Storage\Database\Database->doSelect(Object(SP\Storage\Database\QueryData))                             
#4 /var/www/syspass/lib/SP/Services/Track/TrackService.php(199): SP\Repositories\Track\TrackRepository->getTracksForClientFromTime(Object(SP\Repositories\Track\TrackRequest))    
#5 /var/www/syspass/lib/SP/Services/Track/TrackService.php(162): SP\Services\Track\TrackService->getTracksForClientFromTime(Object(SP\Repositories\Track\TrackRequest))           
#6 /var/www/syspass/lib/SP/Servi...                                                                                                                                               
PHP message: [EXCEPTION] [SQLSTATE[42S02]: Base table or view not found: 1146 Table 'syspassdb.Track' doesn't exist                                                               
#0 /var/www/syspass/lib/SP/Storage/Database/Database.php(175): SP\Storage\Database\Database->prepareQueryData(Object(SP\Storage\Database\QueryData))                              
#1 /var/www/syspass/lib/SP/Storage/Database/Database.php(136): SP\Storage\Database\Database->doQuery(Object(SP\Storage\Database\QueryData))                                       
#2 /var/www/syspass/lib/SP/Repositories/Track/TrackRepository.php(204): SP\Storage\Database\Database->doSelect(Object(SP\Storage\Database\QueryData))                             
#3 /var/www/syspass/lib/SP/Services/Track/TrackService.php(199): SP\Repositories\Track\TrackRepository->getTracksForClientFromTime(Object(SP\Repositories\Track\TrackRequest      
2019/11/18 15:00:42 [error] 1324#1324: *29 FastCGI sent in stderr: "(162): SP\Services\Track\TrackService->getTracksForClientFromTime(Object(SP\Repositories\Track\TrackRequest)) 
#5 /var/www/syspass/lib/SP/Services/Auth/LoginService.php(143): SP\Services\Track\TrackService->checkTracking(Object(SP\Re...                                                     
PHP message: [EXCEPTION] [(P) SQLSTATE[42S02]: Base table or view not found: 1146 Table 'syspassdb.Track' doesn't exist                                                           
#0 /var/www/syspass/lib/SP/Storage/Database/Database.php(219): PDO->prepare('SELECT id, user...', Array)                                                                          
#1 /var/www/syspass/lib/SP/Storage/Database/Database.php(175): SP\Storage\Database\Database->prepareQueryData(Object(SP\Storage\Database\QueryData))                              
#2 /var/www/syspass/lib/SP/Storage/Database/Database.php(136): SP\Storage\Database\Database->doQuery(Object(SP\Storage\Database\QueryData))                                       
#3 /var/www/syspass/lib/SP/Repositories/Track/TrackRepository.php(204): SP\Storage\Database\Database->doSelect(Object(SP\Storage\Database\QueryData))                             
#4 /var/www/syspass/lib/SP/Services/Track/TrackService.php(199): SP\Repositories\Track\TrackRepository->getTracksForClientFromTime(Object(SP\Repositories\Track\TrackRequest))    
#5 /var/www/syspass/lib/SP/Services/Track/TrackService.php(162): SP\Services\Track\TrackService->getTracksForClientFromTime(Object(SP\Repositories\Track\TrackRequest))           
#6 /var/www/s...                                                                                                                                                                  
PHP message: [EXCEPTION] [SQLSTATE[42S02]: Base table or view not found: 1146 Table 'syspassdb.Track' doesn't exist                                                               
#0 /var/www/syspass/lib/SP/Storage/Database/Database.php(175): SP\Storage\Database\Database->prepareQueryData(Object(SP\Storage\Database\QueryData))                              
#1 /var/www/syspass/lib/SP/Storage/Database/Database.php(136): SP\Storage\Database\Database->doQuery(Object(SP\Storage\Database\QueryData))                                       
#2 /var/www/syspass/lib/SP/Repositories/Track/TrackRepository.php(204): SP\Storage\Database\Database->doSelect(Object(SP\Storage\Database\QueryData))                             
#3 /var/www/syspass/lib/SP/Services/Track/TrackService.php(199): SP\Repositories\Track\TrackRepository->getTracksForClientFromTime(Object(SP\Repositories\Track\Trac              
```

**Comment by Nebucatnetzer** [comment]
I created now a manual mysql dump and got the missing Track table.
I'll check if a diff of the sql files shows anything interesting.

**Comment by Nebucatnetzer** [comment]
BTW I noticed that syspass throws a lot of errors which are actually infos.
Maybe you can tweak the level here?
```
2019/11/18 17:08:43 [error] 20407#20407: *20420 FastCGI sent in stderr: "PHP message: [INFO] [Extensions checked] SP\Core\PhpExtensionChecker::checkMandatory" while reading response header from upstream, client: 127.0.0.1, server: _, request: "POST /api.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "localhost"
```

**Comment by Nebucatnetzer** [comment]
@nuxsmin do you have an input on this?

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply...

I've no idea why your exported SQL file doesn't contain the `Track` table. This kind of restore procedure is being performed on demo site daily, so it should work.

Apart from this issue, be aware of the permissions of the database views, since if you're exporting the database with the root user, it will set the permission of the views to root, so syspass' user won't be able to list the accounts and other tasks.

Regards

**Comment by Nebucatnetzer** [comment]
Ah okay thank you for the hint.
Is there something we could do to debug the export?
I would gladly help to fix it, I'm not a PHP dev however so I would mostly be able to test stuff for you.

**Comment by nuxsmin** [comment]
This is the command I run to export the database: 

`mysqldump syspass --skip-extended-insert --result-file="/home/dumps/syspass_v3.sql" --lock-tables --add-locks`

And this the script used to restore it:
```bash
#!/bin/bash

SQL_FILE="/home/dumps/syspass_v3.sql"
DB_HOST="localhost"
DB_NAME="syspass"
DB_USER="XXX"
DB_PASS="YYY"

if [[ ! -e "${SQL_FILE}" ]]; then
    echo "SQL file does not exist: ${SQL_FILE}"
    exit 1
fi

echo "Database host: ${DB_HOST}"
echo "Database name: ${DB_NAME}"

mysql -h ${DB_HOST} -u ${DB_USER} -p${DB_PASS} ${DB_NAME} < ${SQL_FILE}

if [[ $? -eq 0 ]]; then
    echo "Database data imported"
    echo `date`
fi
```
Please take a look to the exported file, and search for the `Track` table.
