### ISSUE TITLE
Installing syspass on debian 9 : Issue with Install page

### ISSUE THREAD

**Issue by nlagos1996** [nuxsmin/sysPass#1508]
I am having an issue with syspass when I try and enter in any type of password (Master Password,Admin Password,SQLPassword) on the install page. I enter the password and a bunch of "random" characters just load after typing it. Something does not look proper about the install screen.

**Comment by nlagos1996** [comment]
[Thu Jan 09 22:22:03.787595 2020] [:error] [pid 78396] [client 192.168.1.253:50670] [EXCEPTION] [Unable to check the sysPass user (sp_5e18180bc01c4)\n#0 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(276): SP\\Services\\Install\\MySQL->setupDbUser()\n#1 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(187): SP\\Services\\Install\\Installer->setupDb()\n#2 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(99): SP\\Services\\Install\\Installer->install()\n#3 /var/www/html/syspass/app/modules/web/Controllers/InstallController.php(88): SP\\Services\\Install\\Installer->run(Object(SP\\Services\\Install\\InstallData))\n#4 [internal function]: SP\\Modules\\Web\\Controllers\\InstallController->installAction()\n#5 /var/www/html/syspass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)\n#6 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)\n#7 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)\n#8 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route),Object(Klein\\DataCollection\\RouteCollection),Array)\n#9 /var/www/html/syspass/lib/SP/Bootstrap.php(464): Klein\\Klein->dispatch(Object(Klein\\Request))\n#10 /var/www/html/syspass/lib/Base.php(75): SP\\Bootstrap->run(Object(DI\\Container))\n#11 /var/www/html/syspass/index.php(28): require(String)] N/A, referer: http://syspass.ntechlife.com/index.php?r=install/index
[Thu Jan 09 22:22:03.787691 2020] [:error] [pid 78396] [client 192.168.1.253:50670] [EXCEPTION] [(P) SQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'pwadmin'@'localhost' for table 'user'\n#0 /var/www/html/syspass/lib/SP/Services/Install/MySQ

**Comment by nlagos1996** [comment]
What does it mean when it says for "table  'user'" at the bottom of the error log?

**Comment by nlagos1996** [comment]
This has been resolved... was not checking off hosted mode.
