### ISSUE TITLE
Have issue when sign in 

### ISSUE THREAD

**Issue by tungton** [nuxsmin/sysPass#1509]
Dear Nuxsmin,
One day, I sign in by admin account(local), but it face with error :"Connection Error(Bind)". I try using sign by account LDAP but it still in the pop up same error. I tail log in syspass.log, it show:
#0 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(114): SP\Providers\Auth\Ldap\LdapConnection->bind()
#1 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(95): SP\Providers\Auth\Ldap\LdapConnection->connectAndBind()
#2 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/Ldap.php(96): SP\Providers\Auth\Ldap\LdapConnection->checkConnection()
#3 /var/www/html/syspass/lib/SP/Providers/Auth/AuthProvider.php(154): SP\Providers\Auth\Ldap\Ldap->factory(Object(SP\Providers\Auth\Ldap\LdapParams),Object(SP\Core\Events\EventDispatcher),Boolean)
#4 /var/www/html/syspass/lib/SP/Providers/Auth/AuthProvider.php(116): SP\Providers\Auth\AuthProvider->getLdapAuth()
#5 /var/www/html/syspass/lib/SP/Providers/Auth/AuthProvider.php(97): SP\Providers\Auth\AuthProvider->authLdap()
#6 /var/www/html/syspass/lib/SP/Services/Auth/LoginService.php(154): SP\Providers\Auth\AuthProvider->doAuth(Object(SP\DataModel\UserLoginData))
#7 /var/www/html/syspass/app/modules/web/Controllers/LoginController.php(65): SP\Services\Auth\LoginService->doLogin()
#8 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#9 /var/www/html/syspass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#10 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#11 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#12 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#13 /var/www/html/syspass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#14 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#15 /var/www/html/syspass/index.php(28): require(String)","caller":"N/A"}
Please help me to tshoot the issue,
Thank you and best regards,
Tung Ton

**Comment by nuxsmin** [comment]
Hello, could you provide some more info about your sysPass instance?. Please use the issue template.

Regards

**Comment by tungton** [comment]
Thank you for your support. How can I get the issue template?
best regards,
Tung

**Comment by tungton** [comment]
I add some information. I use app version "311.1912160", PHP 7.2.24-0ubuntu0.18.04.1 , and Mariadb Server version: 10.1.43-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04
Thank you,

**Comment by matejzero** [comment]
Error message (`One day, I sign in by admin account(local), but it face with error :"Connection Error(Bind)"`) seems like the server can'd connect to LDAP. Can you check with telnet or ldapsearch if you can connect to it from the same server?

**Comment by tungton** [comment]
> Error message (`One day, I sign in by admin account(local), but it face with error :"Connection Error(Bind)"`) seems like the server can'd connect to LDAP. Can you check with telnet or ldapsearch if you can connect to it from the same server?

Thank for your reply, I had also checked connection port and it is OK. I think the issue is not related to LDAP server because I sign in with admin and it still show same error.

**Comment by tungton** [comment]
Sorry , does not anyone to help me?

**Comment by nuxsmin** [comment]
Hello, I found some issues with `ldap_connect` PHP function which skips the LDAP port if the URI is set. Please check out he latest release.

Regards

**Comment by tungton** [comment]
Dear Nuxsmin, 
Thank you for your response. You means I need to upgrade with latest version or fresh install with lastest version. If upgrade, would you like to show me the link to upgrade?
Best regards,

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply.

It will be ready in next v3.2 release.

Regards

**Comment by tungton** [comment]
Thank for reply, now we use Ubuntu 18.04 to build syspass server? is it applicable or i need to change another distro? If not could you please send me instruction step to upgrade syspass to version 3.2 
regards,
