### ISSUE TITLE
Unable to import accounts unless general configuration is also enabled for a profile.

### ISSUE THREAD

**Issue by 11anthonym** [nuxsmin/sysPass#1539]
**sysPass Version**
3.1 (311.19121601) 

**Describe the question**
Not sure if this is intended functionality so listing as a question. When trying to import xml or csv if import accounts is enabled for a profile but general config is not, it will not import and return error "Service Unavailable Invalid Action". Main concern is giving user profiles access to addition config options other than ability to import xml or csv files.

**Screenshots**

![firefox_07GQAYJ3s6](https://user-images.githubusercontent.com/62766485/78579094-6e0d8600-77fe-11ea-9a02-aec85f7d04c7.png)

![brave_um09AiPuXu](https://user-images.githubusercontent.com/62766485/78579153-7bc30b80-77fe-11ea-939f-163126ad1289.png)

![firefox_hlpGvZxuZv](https://user-images.githubusercontent.com/62766485/78579225-97c6ad00-77fe-11ea-8495-663efb05ea7d.png)

![brave_52bg9kgY4R](https://user-images.githubusercontent.com/62766485/78579203-8f6e7200-77fe-11ea-8f69-f6a983fd15f0.png)

**Platform (please complete the following information):**
 - OS: Microsoft Windows 10 Pro
 - OS Version: 10.0.18363 Build 18363
 - Browser: Firefox, Chrome

**Additional context**

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply, I've been so busy....

I'll try to find out the issue. Thanks for the feedback!

Regards

**Comment by xtonousou** [comment]
Any progress on this one?

**Comment by glxnet** [comment]
I have been poking around a little bit.  The exception thrown for a profile with (only) Import permissions is:
```
Invalid Action
#0 /srv/sysPass/app/modules/web/Controllers/ConfigImportController.php(59): SP\\Modules\\Web\\Controllers\\SimpleControllerBase->checkSecurityToken(String,Object(SP\\Http\\Request))
#1 [internal function]: SP\\Modules\\Web\\Controllers\\ConfigImportController->importAction()
#2 /srv/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#3 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)
#4 /srv/sysPass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)
#5 /srv/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route),Object(Klein\\DataCollection\\RouteCollection),Array)
#6 /srv/sysPass/lib/SP/Bootstrap.php(464): Klein\\Klein->dispatch(Object(Klein\\Request))
#7 /srv/sysPass/lib/Base.php(75): SP\\Bootstrap->run(Object(DI\\Container))
#8 /srv/sysPass/index.php(28): require(String)
```
The "Configuration -> Import Accounts" tab is added, but the session key does not seem to contain the `configImport/import ` action.
