### ISSUE TITLE
Connecting to restored database/app results in:     error_outline Unable to connect to DB

### ISSUE THREAD

**Issue by alexseys** [nuxsmin/sysPass#1626]
sysPass Version
3.0 (305.19020701)

mysql --version
/usr/local/mysql/bin/mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1

Describe the question
Connecting to restored database/app results in: 

    error_outline Unable to connect to DB

    Please contact to the administrator
Steps taken to restore:
1. Installed apache, mysql 
2. moved syspass dir from original server via tar
3. imported database via: mysql -h localhost -u root -p  < syspass_v3.sql

Screenshots

Platform (please complete the following information):

    OS: Linux
    OS Ubuntu 18
    Browser any

Additional context
`2020-12-09 20:42:42 [EXCEPTION] [N/A] (P) Unable to connect to DB
#0 /var/www/html/lib/SP/Storage/Database/Database.php(215): SP\Storage\Database\MySQLHandler->getConnection()
#1 /var/www/html/lib/SP/Storage/Database/Database.php(174): SP\Storage\Database\Database->prepareQueryData(Object(SP\Storage\Database\QueryData))
#2 /var/www/html/lib/SP/Storage/Database/Database.php(135): SP\Storage\Database\Database->doQuery(Object(SP\Storage\Database\QueryData))
#3 /var/www/html/lib/SP/Repositories/Plugin/PluginRepository.php(445): SP\Storage\Database\Database->doSelect(Object(SP\Storage\Database\QueryData))
#4 /var/www/html/lib/SP/Services/Plugin/PluginService.php(290): SP\Repositories\Plugin\PluginRepository->getEnabled()
#5 /var/www/html/lib/SP/Plugin/PluginManager.php(360): SP\Services\Plugin\PluginService->getEnabled()
#6 /var/www/html/app/modules/web/Controllers/BootstrapController.php(114): SP\Plugin\PluginManager->getEnabledPlugins()
#7 /var/www/html/app/modules/web/Controllers/BootstrapController.php(67): SP\Modules\Web\Controllers\BootstrapController->getPlugins()
#8 [internal function]: SP\Modules\Web\Controllers\BootstrapController->getEnvironmentAction()
#9 /var/www/html/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#10 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#12 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#13 /var/www/html/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#14 /var/www/html/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#15 /var/www/html/index.php(28): require('/var/www/html/l...')
#16 {main}`

Thank you for all your work!!

**Comment by alexseys** [comment]
log file showed it was failing on applying  schemas/31019012201.sql
removed such from database updated just fine

Thank you
