### ISSUE TITLE
Can't Install Syspass

### ISSUE THREAD

**Issue by trentdavis** [nuxsmin/sysPass#1665]
Hello, I've been trying to install Syspass on a hosted system.  I've finally gotten the install screen, but it doesn't go any further - even though I have entered the correct information.  Also, the install screen isn't displaying correctly.  Please see attached screen shot and also part of the syspass.log below:

![Syspass1](https://user-images.githubusercontent.com/11521067/110792869-4dd61a80-824a-11eb-978f-80dd32820856.png)

[2021-03-11 02:56:48] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2021-03-11 02:56:48] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2021-03-11 02:56:48] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2021-03-11 02:56:48] syspass.INFO: logger {"message":"Loaded icons cache","caller":"SP\Core\UI\Theme::initIcons"}
[2021-03-11 02:56:48] syspass.INFO: logger {"message":"Loaded icons cache","caller":"SP\Core\UI\Theme::initIcons"}
[2021-03-11 02:56:48] syspass.INFO: logger {"message":"Loaded icons cache","caller":"SP\Core\UI\Theme::initIcons"}
[2021-03-11 02:56:48] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2021-03-11 02:56:48] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2021-03-11 02:56:48] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2021-03-11 02:56:48] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2021-03-11 02:56:48] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2021-03-11 02:56:48] syspass.INFO: logger {"message":"Loaded icons cache","caller":"SP\Core\UI\Theme::initIcons"}
[2021-03-11 02:56:48] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2021-03-11 02:56:48] syspass.INFO: logger {"message":"Loaded icons cache","caller":"SP\Core\UI\Theme::initIcons"}
[2021-03-11 02:56:48] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2021-03-11 05:30:28] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2021-03-11 05:30:28] syspass.INFO: logger {"message":"Loaded icons cache","caller":"SP\Core\UI\Theme::initIcons"}
[2021-03-11 05:30:28] syspass.ERROR: logger {"message":"Not installed","caller":"SP\Modules\Web\Init::initialize"}
[2021-03-11 05:30:28] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2021-03-11 05:30:28] syspass.EXCEPTION: logger {"message":"Response is locked
#0 /home2/sitehub1/public_html/onion/vendor/klein/klein/src/Klein/AbstractResponse.php(211): Klein\AbstractResponse->requireUnlocked()
#1 /home2/sitehub1/public_html/onion/vendor/klein/klein/src/Klein/AbstractResponse.php(523): Klein\AbstractResponse->code(Integer)
#2 /home2/sitehub1/public_html/onion/app/modules/web/Controllers/IndexController.php(50): Klein\AbstractResponse->redirect(String)
#3 [internal function]: SP\Modules\Web\Controllers\IndexController->indexAction()
#4 /home2/sitehub1/public_html/onion/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#5 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /home2/sitehub1/public_html/onion/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#7 /home2/sitehub1/public_html/onion/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#8 /home2/sitehub1/public_html/onion/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#9 /home2/sitehub1/public_html/onion/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#10 /home2/sitehub1/public_html/onion/index.php(28): require(String)","caller":"N/A"}
[2021-03-11 05:30:28] syspass.EXCEPTION: logger {"message":"Response is locked
#0 /home2/sitehub1/public_html/onion/vendor/klein/klein/src/Klein/AbstractResponse.php(157): Klein\AbstractResponse->requireUnlocked()
#1 /home2/sitehub1/public_html/onion/lib/SP/Bootstrap.php(149): Klein\AbstractResponse->body(String)
#2 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Klein),String,String,Object(Klein\Exceptions\LockedResponseException))
#3 /home2/sitehub1/public_html/onion/vendor/klein/klein/src/Klein/Klein.php(936): call_user_func(Object(Closure),Object(Klein\Klein),String,String,Object(Klein\Exceptions\LockedResponseException))
#4 /home2/sitehub1/public_html/onion/vendor/klein/klein/src/Klein/Klein.php(645): Klein\Klein->error(Object(Klein\Exceptions\LockedResponseException))
#5 /home2/sitehub1/public_html/onion/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#6 /home2/sitehub1/public_html/onion/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#7 /home2/sitehub1/public_html/onion/index.php(28): require(String)","caller":"N/A"}
[2021-03-11 05:30:28] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2021-03-11 05:30:28] syspass.INFO: logger {"message":"Loaded icons cache","caller":"SP\Core\UI\Theme::initIcons"}
[2021-03-11 05:30:28] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}

**Comment by nuxsmin** [comment]
Hello, 

it seems to be an issue with some HTTP requests, since some resources, like icons, are loaded from an icon font resource. Please the a look to the network traffic between the browser and sysPass server.

Regards
