### ISSUE TITLE
SSL connection is required when using Azure Database for MariaDB

### ISSUE THREAD

**Issue by hairmare** [nuxsmin/sysPass#1776]
**Is your feature request related to a problem? Please describe.**
I'm trying to install sysPass using a Azure Database for MariaDB instance with default settings (SSL/TLS required)

**Describe the solution you'd like**
I would like to be able to connect to the database without having to allow non encrypted connections in the database. To do so I would need to be able to configure a root CA file and the PDO object needs to be passed an additional `PDO::MYSQL_ATTR_SSL_CA` opt.

**Describe alternatives you've considered**
Allowing non encrypted connections tot the database is not a viable solution due to the nature of the data stored in sysPass. 

**Additional context**
sysPass logs the following error when I try to connect to MariaDB:
```
[Wed Nov 03 08:07:48.273127 2021] [php7:notice] [pid 722] [client 10.7.24.169:49326] [EXCEPTION] [(P) SQLSTATE[HY000] [9002] SSL connection is required. Please specify SSL options and retry.\n#0 /var/www/html/sysPass/lib/SP/Storage/Database/MySQLHandler.php(109): PDO->__construct('mysql:charset=u...', 'syspass', 'secretpassword...', Array)\n#1 /var/www/html/sysPass/lib/SP/Storage/Database/DatabaseUtil.php(119): SP\\Storage\\Database\\MySQLHandler->getConnection()\n#2 /var/www/html/sysPass/app/modules/web/Init.php(193): SP\\Storage\\Database\\DatabaseUtil->checkDatabaseConnection()\n#3 /var/www/html/sysPass/lib/SP/Bootstrap.php(232): SP\\Modules\\Web\\Init->initialize('index')\n#4 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#5 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#6 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#7 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\\Klein->dispatch(Object(Klein\\Request))\n#8 /var/www/html/sysPass/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))\n#9 /var/www/html/sysPass/index.php(28): require('/var/www/html/s...')\n#10 {main}] N/A,
```

A quick review of `lib/SP/Storage/Database/MySQLHandler.php` indicates we would need to add a way to pass `PDO::MYSQL_ATTR_SSL_CA => '/pat/to/rootCA.crt.pem'` to `$opts` when creating the `PDO` client.

There is an example in the Microsoft docs: https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl#php-using-pdo.

This issue is  about using transport layer encryption and not about replacing username/password with a client cert.

**Comment by hairmare** [comment]
Duplicate of #1607
