### ISSUE TITLE
Backup does not dump all tables needed for a full restore

### ISSUE THREAD

**Issue by Jonher937** [nuxsmin/sysPass#1786]
**sysPass Version**
3.1

**Describe the bug**
Database backup task is not including all tables for a restore

**To Reproduce**
1. Go to Configuration -> Backup and perform a database backup
2. Download database backup
3. Note that we are missing 3 tables in the backup: `ItemPreset`, `PluginData`, `Track`
4. Try wiping database and restoring the backup. The login page will load but upon trying to login it will fail and log that it's missing tables. See example posted below in the "Console.log" header.

**Expected behavior**
Backup to include all tables in the database (including tables added by schema migrations), not just the "base" tables.

**Console log**
```
syspass-app | [Fri Nov 26 13:34:08.157330 2021] [:error] [pid 721] [client 127.0.0.1:39650] [EXCEPTION] [SQLSTATE[42S02]: Base table or view not found: 1146 Table 'syspass.Track' doesn't exist
#0 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(219): PDO->prepare(String,Array)
#1 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(175): SP\\Storage\\Database\\Database->prepareQueryData(Object(SP\\Storage\\Database\\QueryData))
#2 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(136): SP\\Storage\\Database\\Database->doQuery(Object(SP\\Storage\\Database\\QueryData))
#3 /var/www/html/sysPass/lib/SP/Repositories/Track/TrackRepository.php(204): SP\\Storage\\Database\\Database->doSelect(Object(SP\\Storage\\Database\\QueryData))
#4 /var/www/html/sysPass/lib/SP/Services/Track/TrackService.php(199): SP\\Repositories\\Track\\TrackRepository->getTracksForClientFromTime(Object(SP\\Repositories\\Track\\TrackRequest))
#5 /var/www/html/sysPass/lib/SP/Services/Track/TrackService.php(162): SP\\Services\\Track\\TrackService->getTracksForClientFromTime(Object(SP\\Repositories\\Track\\TrackRequest))
#6 /var/www/html/sysPass/lib/SP/Services/Auth/LoginService.php(143): SP\\Services\\Track\\TrackService->checkTracking(Object(SP\\Repositories\\Track\\TrackRequest))
#7 /var/www/html/sysPass/app/modules/web/Controllers/LoginController.php(65): SP\\Services\\Auth\\LoginService->doLogin()
#8 [internal function]: SP\\Modules\\Web\\Controllers\\LoginController->loginAction()
#9 /var/www/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#10 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)
#11 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)
#12 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route),Object(Klein\\DataCollection\\RouteCollection),Array)
#13 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\\Klein->dispatch(Object(Klein\\Request))
#14 /var/www/html/sysPass/lib/Base.php(75): SP\\Bootstrap->run(Object(DI\\Container))
#15 /var/www/html/sysPass/index.php(28): require(String)] N/A, referer: http://127.0.0.1:8080/index.php?r=login
```

**Platform (please complete the following information):**
* Docker image: `syspass/syspass:3.1.1`

**Additional context**
It looks like the backup task is loading the list of tables from DatabaseUtil which does not contain the tables missing, probably since they are added by schema migrations.
https://github.com/nuxsmin/sysPass/blob/5882699f2247d0d582bd053f7b350d555f7bfe70/lib/SP/Services/Backup/FileBackupService.php#L239

List of tables, where `ItemPreset`, `PluginData`, `Track` are missing.
https://github.com/nuxsmin/sysPass/blob/5882699f2247d0d582bd053f7b350d555f7bfe70/lib/SP/Storage/Database/DatabaseUtil.php#L39-L66

### Production
```
MariaDB [syspass]> show tables;
+-----------------------+
| Tables_in_syspass     |
+-----------------------+
| Account               |
| AccountFile           |
| AccountHistory        |
| AccountToFavorite     |
| AccountToTag          |
| AccountToUser         |
| AccountToUserGroup    |
| AuthToken             |
| Category              |
| Client                |
| Config                |
| CustomFieldData       |
| CustomFieldDefinition |
| CustomFieldType       |
| EventLog              |
| ItemPreset            |
| Notification          |
| Plugin                |
| PluginData            |
| PublicLink            |
| Tag                   |
| Track                 |
| User                  |
| UserGroup             |
| UserPassRecover       |
| UserProfile           |
| UserToUserGroup       |
| account_data_v        |
| account_search_v      |
+-----------------------+
29 rows in set (0.00 sec)
```

### Restore from syspass SQL backup
```
MariaDB [syspass]> show tables;
+-----------------------+
| Tables_in_syspass     |
+-----------------------+
| Account               |
| AccountFile           |
| AccountHistory        |
| AccountToFavorite     |
| AccountToTag          |
| AccountToUser         |
| AccountToUserGroup    |
| AuthToken             |
| Category              |
| Client                |
| Config                |
| CustomFieldData       |
| CustomFieldDefinition |
| CustomFieldType       |
| EventLog              |
| Notification          |
| Plugin                |
| PublicLink            |
| Tag                   |
| User                  |
| UserGroup             |
| UserPassRecover       |
| UserProfile           |
| UserToUserGroup       |
| account_data_v        |
| account_search_v      |
+-----------------------+
26 rows in set (0.00 sec)
```

**Comment by Jonher937** [comment]
@nuxsmin could you have a look and confirm this is an issue? I could send a PR for adding the missing tables into DatabaseUtil but I don't have enough knowledge of the codebase to know if that would potentially break other things.
Thanks and have a nice weekend.

**Comment by nuxsmin** [comment]
Hello @Jonher937 

you're right, there are some missing tables in the backup. I'll fix it shortly.

Thanks for the notice!
