### ISSUE TITLE
Unable to log in with LDAP user if group or profile changed before initial login.

### ISSUE THREAD

**Issue by FooBarTrixibell** [nuxsmin/sysPass#1790]
**sysPass Version**
3.2 (322.21031301)

**Describe the bug**
If LDAP users are imported and then edited to change their group or profile prior to their first login it will prevent login and tell you that the user is not a member of any groups.

**To Reproduce**
Steps to reproduce the behaviour:
1. Import a user from LDAP
2. Edit the user and change their profile
3. Get the user to attempt to log in
4. Recieve error "User has no associated groups"

**Expected behaviour**
The user is able to log in and Master Password is requested.

**Event log**
[EXCEPTION] [User has no associated groups\n#0 /var/www/html/sysPass/lib/SP/Services/Auth/LoginService.php(160): SP\\Services\\Auth\\LoginServi
ce->authLdap()\n#1 /var/www/html/sysPass/app/modules/web/Controllers/LoginController.php(65): SP\\Services\\Auth\\LoginService->doLogin()\n#2 [internal function]: SP\\Modules\\Web\\Controllers\\LoginController->loginAction()\n#3 /var/www
/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array()\n#4 [internal function]: SP\\Bootstrap->SP\\{closure}()\n#5 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func()\n#6 /var/www/html/sysPass/ven
dor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback()\n#7 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\\Klein->dispatch()\n#8 /var/www/html/sysPass/lib/Base.php(75): SP\\Bootstrap->run()\n#9 /var/www/htm
l/sysPass/index.php(28): require(String)] N/A, referer: https://syspass.lockheedmartin.co.nz/index.php?r=login

57 | 2021-11-29 14:30:00 | ERROR | exception | - | X.X.X.X | User has no associated groupsauthLdap -- | -- | -- | -- | -- | -- | --

**Platform (please complete the following information):**
 - OS: Centos
 - OS 7
 - Browser Chrome 96.0.4664.45

**Additional context**
Removal of the imported account and recreation (through the import process again) allows the user to log in.

**Comment by FooBarTrixibell** [comment]
After further investigation, it appears that on our side someone changed the group in the LDAP settings in order to do an import and did not change it back correctly. The 'fix' only worked because the import was performed on a small group and then the group was changed back to Domain Users (which is one level below all of the other groups, hence the typo.)

In respect of this, my only suggestion would be to have a separate logon group from the import groups or to only allow save after validation.

Either way I will close this as a non-issue!
