### ISSUE TITLE
Account expired when account is active

### ISSUE THREAD

**Issue by matejzero** [nuxsmin/sysPass#1796]
**sysPass Version**
3.2 (322.21031301) 

**Describe the bug**
Sometimes users can't login, getting an `account expired` error. I have checked on multiple occasions and the account was active and the user was able to login to other AD backed services without a problem.

Clearing the cache folder or restarting the apache / php process doesn't help.

Is it possible to get more info like what LDAP actually returns to see what the real error code received from AD is?

**To Reproduce**
Don't have a reproducible case. It happens every now and then for a random user. 

**Event log**
The logs are not really useful I think.
```
[2021-12-21 08:09:15] syspass.EXCEPTION: logger {"message":"Account expired
#0 /var/www/html/syspass/lib/SP/Services/Auth/LoginService.php(160): SP\Services\Auth\LoginService->authLdap(Object(SP\Providers\Auth\Ldap\LdapAuthData))
#1 /var/www/html/syspass/app/modules/web/Controllers/LoginController.php(65): SP\Services\Auth\LoginService->doLogin()
#2 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#3 /var/www/html/syspass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/html/syspass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#9 /var/www/html/syspass/index.php(28): require(String)","caller":"N/A"}
```

**Platform (please complete the following information):**
- OS: CentOS 7, Linux, Apache, mod_php 7.3.31

**Comment by nuxsmin** [comment]
Hello, you can try to enable debug on `Configuration > General`.

Regards.

**Comment by matejzero** [comment]
I enabled it and now I have to wait for another case to apear as it is pretty random. Will update the ticket once it happens.

**Comment by JohnAlcantara14** [comment]
Block and unblock the user in Active directory, solved the problem.

**Comment by JohnAlcantara14** [comment]
Block and unblock the user in Active directory, solved the problem with user there moment.
