### ISSUE TITLE
Timeout undefined

### ISSUE THREAD

**Issue by Asapian** [nuxsmin/sysPass#1808]
**sysPass Version 3.2**

**Describe the bug**
A pop-up appears with  "There was an error timeout undefined"

**To Reproduce**
I receive this pop-up when I go to Configuration or Security and Audit

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/25057237/159877605-a22ab116-285e-4e7c-b895-1f8d02737968.png)

**Event log**
Mar 24 07:17:01 syspass CRON[29562]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Mar 24 07:39:01 syspass CRON[29620]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Mar 24 07:39:06 syspass systemd[1]: Starting Clean php session files...
Mar 24 07:39:06 syspass sessionclean[29659]: PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
Mar 24 07:39:06 syspass systemd[1]: phpsessionclean.service: Succeeded.
Mar 24 07:39:06 syspass systemd[1]: Finished Clean php session files.
Mar 24 08:09:00 syspass systemd[1]: Starting Clean php session files...
Mar 24 08:09:00 syspass sessionclean[29823]: PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
Mar 24 08:09:00 syspass systemd[1]: phpsessionclean.service: Succeeded.
Mar 24 08:09:00 syspass systemd[1]: Finished Clean php session files.
Mar 24 08:09:01 syspass CRON[29855]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Mar 24 08:17:01 syspass CRON[29873]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Mar 24 08:39:00 syspass systemd[1]: Starting Clean php session files...
Mar 24 08:39:00 syspass sessionclean[29968]: PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
Mar 24 08:39:00 syspass systemd[1]: phpsessionclean.service: Succeeded.
Mar 24 08:39:00 syspass systemd[1]: Finished Clean php session files.
Mar 24 08:39:01 syspass CRON[30000]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Mar 24 08:47:10 syspass systemd[1]: Created slice User Slice of UID 1002.
Mar 24 08:47:10 syspass systemd[1]: Starting User Runtime Directory /run/user/1002...
Mar 24 08:47:10 syspass systemd[1]: Finished User Runtime Directory /run/user/1002.
Mar 24 08:47:10 syspass systemd[1]: Starting User Manager for UID 1002...
Mar 24 08:47:10 syspass systemd[30070]: Reached target Paths.
Mar 24 08:47:10 syspass systemd[30070]: Reached target Timers.
Mar 24 08:47:10 syspass systemd[30070]: Starting D-Bus User Message Bus Socket.
Mar 24 08:47:10 syspass systemd[30070]: Listening on GnuPG network certificate management daemon.
Mar 24 08:47:10 syspass systemd[30070]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Mar 24 08:47:10 syspass systemd[30070]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Mar 24 08:47:10 syspass systemd[30070]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Mar 24 08:47:10 syspass systemd[30070]: Listening on GnuPG cryptographic agent and passphrase cache.
Mar 24 08:47:10 syspass systemd[30070]: Listening on debconf communication socket.
Mar 24 08:47:10 syspass systemd[30070]: Listening on REST API socket for snapd user session agent.
Mar 24 08:47:10 syspass systemd[30070]: Listening on D-Bus User Message Bus Socket.
Mar 24 08:47:10 syspass systemd[30070]: Reached target Sockets.
Mar 24 08:47:10 syspass systemd[30070]: Reached target Basic System.
Mar 24 08:47:10 syspass systemd[1]: Started User Manager for UID 1002.
Mar 24 08:47:10 syspass systemd[1]: Started Session 211 of user asentinel.
Mar 24 08:47:10 syspass systemd[30070]: Reached target Main User Target.
Mar 24 08:47:10 syspass systemd[30070]: Startup finished in 92ms.
**Platform (please complete the following information):**
 - OS: Ubuntu
 - OS Version 20.04
 - Browser : Chrome, Edge, Firefox

**Comment by nuxsmin** [comment]
Hello, could you provide `syspass.log` file?

Regards

**Comment by kevinl2022** [comment]
Hello, I got the same problem any solutions for that? thx
```
There was an error<p>timeout</p><p>undefined</p>
error @ index.php?
```
syspass log:
`[2024-07-22 09:50:33] syspass.EXCEPTION: logger {"message":"cURL error 28: Connection timed out after 10001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
#0 /var/www/sysPass/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory->createRejection()
#1 /var/www/sysPass/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory->finishError()
#2 /var/www/sysPass/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory->finish()
#3 /var/www/sysPass/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
#4 /var/www/sysPass/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy->GuzzleHttp\Handler\{closure}()
#5 /var/www/sysPass/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\Proxy->GuzzleHttp\Handler\{closure}()
#6 /var/www/sysPass/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#7 /var/www/sysPass/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware->GuzzleHttp\{closure}()
#8 /var/www/sysPass/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke()
#9 /var/www/sysPass/vendor/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\Middleware->GuzzleHttp\{closure}()
#10 /var/www/sysPass/vendor/guzzlehttp/guzzle/src/Client.php(351): GuzzleHttp\HandlerStack->__invoke()
#11 /var/www/sysPass/vendor/guzzlehttp/guzzle/src/Client.php(162): GuzzleHttp\Client->transfer()
#12 /var/www/sysPass/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\Client->requestAsync()
#13 /var/www/sysPass/app/modules/web/Controllers/StatusController.php(59): GuzzleHttp\Client->request()
#14 [internal function]: SP\Modules\Web\Controllers\StatusController->checkReleaseAction()
#15 /var/www/sysPass/lib/SP/Bootstrap.php(247): call_user_func_array()
#16 [internal function]: SP\Bootstrap->SP\{closure}()
#17 /var/www/sysPass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func()
#18 /var/www/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback()
#19 /var/www/sysPass/lib/SP/Bootstrap.php(471): Klein\Klein->dispatch()
#20 /var/www/sysPass/lib/Base.php(75): SP\Bootstrap->run()
#21 /var/www/sysPass/index.php(28): require(String)","caller":"N/A"}`
