### ISSUE TITLE
Error 500 and Php error suddenly on previously working instance

### ISSUE THREAD

**Issue by dimitriscr** [nuxsmin/sysPass#1818]
**sysPass Version**
Can be found on `Config -> Information` tab
Version 322.21031301

**Describe the question**
A clear and concise description.
Hello, completely out of the blue (no updates, no major changes to the system, no php update) the syspass page now gives me a error 500, i don't have a lot to work with, but i do get an error in the apache logs:

PHP Fatal error:  Uncaught Error: Call to a member function getConfigDate() on bool in /var/www/password.teamhelix.net/lib/SP/Config/Config.php:129\nStack trace:\n#0 /var/www/password.teamhelix.net/lib/SP/Config/Config.php(95): SP\\Config\\Config->initialize()\n#1 /var/www/password.teamhelix.net/lib/Definitions.php(65): SP\\Config\\Config->__construct()\n#2 [internal function]: DI\\Definition\\Source\\DefinitionFile->{closure}()\n#3 /var/www/password.teamhelix.net/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()\n#4 /var/www/password.teamhelix.net/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\\Invoker->call()\n#5 /var/www/password.teamhelix.net/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\\Definition\\Resolver\\FactoryResolver->resolve()\n#6 /var/www/password.teamhelix.net/vendor/php-di/php-di/src/Container.php(380): DI\\Definition\\Resolver\\ResolverDispatcher->resolve()\n#7 /var/www/password.teamhelix.net/vendor/php-di/php-di/src/Container.php(138): DI\\Container->resol in /var/www/password.teamhelix.net/lib/SP/Config/Config.php on line 129

I have tried updating the install but i was already on the latest commit. Do you have any idea were i could begin to look for clues to the problem, i have checked all the php dependencies and am using 7.4.2 which i believe is supported.

**Screenshots**
![image](https://user-images.githubusercontent.com/58117095/166086816-b0b740bb-d319-44a1-b10e-ce9845bf23e9.png)

**Platform (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 20.04.3
 - Browser Vivaldi (Although tested by other team members on Chrome and Firefox)

**Additional context**
The instance was working just fine since it was installed a few moth ago, there are other services on the server that i do keep up to date, so something might have change that affected syspass, but I did not touch anything php related and the apache2 configuration is still the same. I should also mention that this is the standalone install and not the docker container.

Thank you so much in advance for any advice you do have

**Comment by nuxsmin** [comment]
Hello, could you provide some more entries from `syspass.log` file?

Regards.

**Comment by nguyenvantien2009** [comment]
> **sysPass Version** Can be found on `Config -> Information` tab Version 322.21031301
> 
> **Describe the question** A clear and concise description. Hello, completely out of the blue (no updates, no major changes to the system, no php update) the syspass page now gives me a error 500, i don't have a lot to work with, but i do get an error in the apache logs:
> 
> PHP Fatal error: Uncaught Error: Call to a member function getConfigDate() on bool in /var/www/password.teamhelix.net/lib/SP/Config/Config.php:129\nStack trace:\n#0 /var/www/password.teamhelix.net/lib/SP/Config/Config.php(95): SP\Config\Config->initialize()\n#1 /var/www/password.teamhelix.net/lib/Definitions.php(65): SP\Config\Config->__construct()\n#2 [internal function]: DI\Definition\Source\DefinitionFile->{closure}()\n#3 /var/www/password.teamhelix.net/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()\n#4 /var/www/password.teamhelix.net/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call()\n#5 /var/www/password.teamhelix.net/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\Definition\Resolver\FactoryResolver->resolve()\n#6 /var/www/password.teamhelix.net/vendor/php-di/php-di/src/Container.php(380): DI\Definition\Resolver\ResolverDispatcher->resolve()\n#7 /var/www/password.teamhelix.net/vendor/php-di/php-di/src/Container.php(138): DI\Container->resol in /var/www/password.teamhelix.net/lib/SP/Config/Config.php on line 129
> 
> I have tried updating the install but i was already on the latest commit. Do you have any idea were i could begin to look for clues to the problem, i have checked all the php dependencies and am using 7.4.2 which i believe is supported.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/58117095/166086816-b0b740bb-d319-44a1-b10e-ce9845bf23e9.png)
> 
> **Platform (please complete the following information):**
> 
> * OS: Ubuntu
> * OS Version: 20.04.3
> * Browser Vivaldi (Although tested by other team members on Chrome and Firefox)
> 
> **Additional context** The instance was working just fine since it was installed a few moth ago, there are other services on the server that i do keep up to date, so something might have change that affected syspass, but I did not touch anything php related and the apache2 configuration is still the same. I should also mention that this is the standalone install and not the docker container.
> 
> Thank you so much in advance for any advice you do have
I am also get the same error.

**Comment by simfender** [comment]
Hello, same problem today but I figured it out. For what I understood the hdd on my nas was 100% full and running syspass meanwhile wrongly created cache files. To resolve this was enough to empty the "syspass\app\cache" folder, freeing some space on the disk and then relaunch the system, new cache files have been created successfully and the error is gone.
