### ISSUE TITLE
The Master Password either is not saved or is wrong

### ISSUE THREAD

**Issue by quercus-idejuan** [nuxsmin/sysPass#1891]
SysPass Version: 3.2 (3211.22070201)

Clean installation from the repository on an Ubuntu 22.04 LTS, PHP7.4, MariaDB.
Everything works just fine, however, after importing my users from LDAP, I can't login into them without inputting the Master password over and over again.
The following message appears after trying to log in using their username + password combination:
"The Master Password either is not saved or is wrong".
Permissions are set correctly.

**To Reproduce**
1. Perform a clean install of SysPass
2. Import your LDAP users
3. Log off and try to log into any of them using their username and password from the AD
4. Get the error, and a prompt to input the Master password.

**Expected behavior**
I should be able to log into the account just fine. The Master password is currently set, the "www-data" user is the owner of /var/www/html/syspass and all its sub-directories and permissions are properly set.

**Event log**
[Sun Feb 05 11:47:53.686114 2023] [php7:notice] [pid 166824] [client 10.1.0.28:55958] [EXCEPTION] [User does not exist\n#0 /var/www/html/syspass/lib/SP/Providers/Auth/Database/Database.php(109): SP\\Services\\User\\UserService->getByLogin()\n#1 /var/www/html/syspass/lib/SP/Providers/Auth/Database/Database.php(83): SP\\Providers\\Auth\\Database\\Database->authUser()\n#2 /var/www/html/syspass/lib/SP/Providers/Auth/AuthProvider.php(171): SP\\Providers\\Auth\\Database\\Database->authenticate()\n#3 /var/www/html/syspass/lib/SP/Providers/Auth/AuthProvider.php(97): SP\\Providers\\Auth\\AuthProvider->authDatabase()\n#4 /var/www/html/syspass/lib/SP/Services/Auth/LoginService.php(154): SP\\Providers\\Auth\\AuthProvider->doAuth()\n#5 /var/www/html/syspass/app/modules/web/Controllers/LoginController.php(65): SP\\Services\\Auth\\LoginService->doLogin()\n#6 [internal function]: SP\\Modules\\Web\\Controllers\\LoginController->loginAction()\n#7 /var/www/html/syspass/lib/SP/Bootstrap.php(247): call_user_func_array()\n#8 [internal function]: SP\\Bootstrap->SP\\{closure}()\n#9 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func()\n#10 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback()\n#11 /var/www/html/syspass/lib/SP/Bootstrap.php(471): Klein\\Klein->dispatch()\n#12 /var/www/html/syspass/lib/Base.php(75): SP\\Bootstrap->run()\n#13 /var/www/html/syspass/index.php(28): require(String)] N/A, referer: http://10.7.0.6/index.php?r=login
[Sun Feb 05 11:47:53.805904 2023] [php7:notice] [pid 166824] [client 10.1.0.28:55958] [EXCEPTION] [The Master Password either is not saved or is wrong\n#0 /var/www/html/syspass/lib/SP/Services/Auth/LoginService.php(180): SP\\Services\\Auth\\LoginService->loadMasterPass()\n#1 /var/www/html/syspass/app/modules/web/Controllers/LoginController.php(65): SP\\Services\\Auth\\LoginService->doLogin()\n#2 [internal function]: SP\\Modules\\Web\\Controllers\\LoginController->loginAction()\n#3 /var/www/html/syspass/lib/SP/Bootstrap.php(247): call_user_func_array()\n#4 [internal function]: SP\\Bootstrap->SP\\{closure}()\n#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func()\n#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback()\n#7 /var/www/html/syspass/lib/SP/Bootstrap.php(471): Klein\\Klein->dispatch()\n#8 /var/www/html/syspass/lib/Base.php(75): SP\\Bootstrap->run()\n#9 /var/www/html/syspass/index.php(28): require(String)] N/A, referer: http://10.7.0.6/index.php?r=login

**Platform:**
 - OS: Linux Ubuntu Server 22.04 LTS
 - Browser: Google Chrome

**Comment by gainward700** [comment]
I guess it's intended behaviour that every user needs to enter it for the first time they log in.
But you could create a temporary password that will expire to not share the master passwort.
Maybe I'm wrong but that's my understanding.
