### ISSUE TITLE
Error afte adding an account

### ISSUE THREAD

**Issue by Cobra78** [nuxsmin/sysPass#452]
Hi.
 
I've installed sysPass 2.0.0.17021601 on my RaspberryPi with Archlinux Arm

sysPass runs under:
* lighttpd 1.4.45
* php 7.1.2
* mariadb 10.2.21

After adding an account i receive an internal server error on the main search screen, and the page ramain balk.

Here the trace of the error

```
2017-02-19 10:26:51: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to SP\Core\Session::setAccountColor() must be of the type array, string given, called in /srv/http/sysPass-2.0.0.17021601/inc/SP/Account/AccountSearch.class.php on line 663 and defined in /srv/http/sysPass-2.0.0.17021601/inc/SP/Core/Session.class.php:495
2017-02-19 10:26:51: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2017-02-19 10:26:51: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /srv/http/sysPass-2.0.0.17021601/inc/SP/Account/AccountSearch.class.php(663): SP\Core\Session::setAccountColor(' #')
2017-02-19 10:26:51: (mod_fastcgi.c.2543) FastCGI-stderr: #1 /srv/http/sysPass-2.0.0.17021601/inc/SP/Account/AccountSearch.class.php(332): SP\Account\AccountSearch->pickAccountColor(1)
2017-02-19 10:26:51: (mod_fastcgi.c.2543) FastCGI-stderr: #2 /srv/http/sysPass-2.0.0.17021601/inc/SP/Controller/AccountSearchController.class.php(194): SP\Account\AccountSearch->processSearchResults()
2017-02-19 10:26:51: (mod_fastcgi.c.2543) FastCGI-stderr: #3 /srv/http/sysPass-2.0.0.17021601/inc/SP/Controller/AccountSearchController.class.php(401): SP\Controller\AccountSearchController->getSearch()
2017-02-19 10:26:51: (mod_fastcgi.c.2543) FastCGI-stderr: #4 /srv/http/sysPass-2.0.0.17021601/ajax/ajax_getContent.php(75): SP\Controller\AccountSearchController->doAction()
2017-02-19 10:26:51: (mod_fastcgi.c.2543) FastCGI-stderr: #5 {main}
2017-02-19 10:26:51: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /srv/http/sysPass-2.0.0.17021601/inc/SP/Core/Session.class.php on line 495
```

Please let me know if you need mor details

**Comment by nuxsmin** [comment]
Hi,

Unfortunately sysPass won't run on PHP 7.1 by the moment, it requires many changes and they will be done for the next release.

**Comment by Cobra78** [comment]
Ok, thnx for the response :)Il 19 feb 2017 10:48 AM, RubénD <notifications@github.com> ha scritto:Hi,
Unfortunately sysPass won't run on PHP 7.1 by the moment, it requires many changes and they will be done for the next release.

**Comment by nuxsmin** [comment]
You're welcome
