### ISSUE TITLE
Problems Updating v3

### ISSUE THREAD

**Issue by Fizard** [nuxsmin/sysPass#923]
Hi, I tried to update the syspass v3 beta, but I've changed the config.xml also (because I just unziped the file and overwrite it all) and when I tried to login it asked me to do as a new installation. I tried to put the same configuration but it keeps giving me the same error:
Unable to connect to the DB
Please, check the connection parameters
Error 1045: SQLSTATE[HY000] [1045] Access denied for user 'syspass_app'@'ip' (using password: YES)

I even tried to do it as a new database, changing the database name but it keeps with the same error. I think when it is encrypting the email in the configuration it is not passing the correct password to the database. Is there any changes on this? I'm sure I'm inserting the correct user, password and its with permissions.

The log has this line:
2018-04-25 19:59:56 - #0 /var/www/html/syspass/lib/SP/Storage/MySQLHandler.php(170): PDO->__construct('mysql:host=172....', 'syspass_app', 'WUmm2YAWtSVrGwo...', Array)

And I'm sure my password doesn't begin with this "WUmm2.....".

I also tried to modify the config.xml manually with the database and password and inserting '1' in INSTALLED conf in text but when I do it there the server returns that the application needs updating and ask for a security code.

**Comment by nuxsmin** [comment]
Hi, which version did you update from? Is it v2?.

The security code is generated in the config.xml file (upgradeKey tag).

The database user is not the same as the admin user. sysPass will generate a new database connection user and pass on every new installation.

Hope it works ;)

**Comment by Fizard** [comment]
N,o I was updating the version v3 3.0.0.18033001 to the new commit v3 3.0.0.18042501-beta, but I overwrite all the configuration, so it lost the config and tried to do a clean install again.

The first problem: I tried to create a new database to test but it seems that the password that I put in the "db access password" is being encrypted but when it's trying to connect it's not decrypting, as you can see in this log:
2018-04-25 19:59:56 - #0 /var/www/html/syspass/lib/SP/Storage/MySQLHandler.php(170): PDO->__construct('mysql:host=172....', 'syspass_app', 'WUmm2YAWtSVrGwo...', Array)
So it is giving me always an connection error.
PS: I know the database user is not the admin user, I'm using the database user syspass_app with full rights on the database.

The other problem I'll try to input manually on the config.xml file with the database, user and password. I'll try again tomorrow using the upgradeKey in the config.xml and see if it works. The only fields I need to give manually in the config.xml file to work are those:
<installed>1</installed>
<dbHost></dbHost>
<dbName></dbName>
<dbPass></dbPass>
<dbPort>3306</dbPort>
<dbSocket></dbSocket>
<dbUser></dbUser>
or there are another one that I need?

Thanks

**Comment by Fizard** [comment]
Hi, today I tried again to manually update the config.xml file inserting the SecurityCode after but it didn't work, it's like the database didn't need the update but it tried to do anyway. Here is the log.
2018-04-26 11:42:26 - Loaded actions cache
2018-04-26 11:42:28 - SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'CustomFieldType' already exists
2018-04-26 11:42:28 - Error while updating the database
2018-04-26 11:42:28 - #0 /var/www/html/syspass/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(92): SP\Services\Upgrade\UpgradeDatabaseService->applyUpgrade('300.18010101')

I also tried to create a new database today and it worked. So, after I created the new database I just changed the dbuser, dbpassword and dbname manually in the config.xml with the existing database that I was using and it worked (just needed to insert the Master Key again in admin user).
Seems like this fields needed to be inserted so the application didn't try to update the database:
\<configDate\>1524743165\</configDate\>
\<configHash\>bbed4807e760e5ec026fd10ce08ab37f3bce9b8e\</configHash\>
\<configSaver\>\</configSaver\>
\<configVersion\>300.18042501\</configVersion\>
\<databaseVersion\>300.18042501\</databaseVersion\>

**Comment by nuxsmin** [comment]
Hi, I'm glad to know you got it working. Regarding your points:

>  Seems like this fields needed to be inserted so the application didn't try to update the database:

Yes these fields need to be in the XML but, you don't need to create them since sysPass will create/update whenever is needed. The only tag that would have triggered the update process is `databaseVersion` because it didn't exist in previous versions.

> Just one suggestion, isn't it better to remove the config.xml file from the release code and make the application create this file if it doesn't found it and go to the "first installation" page?

Hmmm, this file is not bundled within the source code ;)

Thanks for the feedback and testing!!
