### ISSUE TITLE
Ldap configuration (v3.0-beta)

### ISSUE THREAD

**Issue by lcuervott** [nuxsmin/sysPass#928]
Hi,

When I try to configure the ldap address in the ldap configuration not all string is stored.
For example, if I use X.X.X.X:389, it only store X.X.X.X, if I use ldap://X.X.X.X:389, it only store "ldap". I see the code and seems that it store it as a string and it's parsed to take all not valid characters out, ":" in this case.

**Comment by Fizard** [comment]
Hi.

I'm with the same problem, when I save in LDAP configuration it is not accepting the ":" and also in password it is doing the same with "$", "#", "@" inside the password.

**Comment by Fizard** [comment]
Also, after saving it doesn't allow to clean all the configuration for LDAP. Maybe should have a reset LDAP configuration button.

**Comment by lcuervott** [comment]
The problem is that all this input are being checked as a string, so no "strange" characters are allowed. I see it in the code, but my knowledge of this language is not enough to fix it. If you search for the strings in the webpage will see where they are checked.

**Comment by Fizard** [comment]
Yes I did. In my configuration it has this values: 
```
  <ldapDefaultGroup>7</ldapDefaultGroup>
  <ldapDefaultProfile>2</ldapDefaultProfile>
```

**Comment by nuxsmin** [comment]
This error warns about a missing user group:

```2018-05-25 14:19:13 - SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`syspass3`.`User`, CONSTRAINT `fk_User_userGroupId` FOREIGN KEY (`userGroupId`) REFERENCES `UserGroup` (`id`))```

**Comment by Fizard** [comment]
Yes, but in the configuration is all set. I've already saw on the database and there is an record in Group table with the ID '7'. Maybe it's something in the LDAP User creation code that it isn't sending the id from the config file.

**Comment by Fizard** [comment]
I tried to search in code and I just found this function that is probably trying to create the login with LDAP:
```
public function createOnLogin(UserLoginRequest $userLoginRequest)
    {
        $userData = new UserData();
        $userData->setLogin($userLoginRequest->getLogin());
        $userData->setName($userLoginRequest->getName());
        $userData->setEmail($userLoginRequest->getEmail());
        $userData->setIsLdap($userLoginRequest->getisLdap());
        $userData->setPass($userLoginRequest->getPassword());
        return $this->create($userData);
    }
```
And also this code:
```
public function create($itemData)
    {
        if ($this->checkDuplicatedOnAdd($itemData)) {
            throw new SPException(__u('Login/email de usuario duplicados'), SPException::INFO);
        }

        $query = /** @lang SQL */
            'INSERT INTO User SET
            name = ?,
            login = ?,
            ssoLogin = ?,
            email = ?,
            notes = ?,
            userGroupId = ?,
            userProfileId = ?,
            mPass = ?,
            mKey = ?,
            lastUpdateMPass = ?,
            isAdminApp = ?,
            isAdminAcc = ?,
            isDisabled = ?,
            isChangePass = ?,
            isLdap = ?,
            pass = ?,
            hashSalt = \'\'';

        $queryData = new QueryData();
        $queryData->setQuery($query);
        $queryData->addParam($itemData->getName());
        $queryData->addParam($itemData->getLogin());
        $queryData->addParam($itemData->getSsoLogin());
        $queryData->addParam($itemData->getEmail());
        $queryData->addParam($itemData->getNotes());
        $queryData->addParam($itemData->getUserGroupId());
        $queryData->addParam($itemData->getUserProfileId());
        $queryData->addParam($itemData->getMPass());
        $queryData->addParam($itemData->getMKey());
        $queryData->addParam($itemData->getLastUpdateMPass());
        $queryData->addParam($itemData->isAdminApp());
        $queryData->addParam($itemData->isAdminAcc());
        $queryData->addParam($itemData->isDisabled());
        $queryData->addParam($itemData->isChangePass());
        $queryData->addParam($itemData->isLdap());
        $queryData->addParam($itemData->getPass());
        $queryData->setOnErrorMessage(__u('Error al crear el usuario'));

        DbWrapper::getQuery($queryData, $this->db);

        return $this->db->getLastId();
    }
```
I can't see this getting the "userGroupId". Maybe it's not sending in the parameters the default group?

**Comment by Fizard** [comment]
I could also debug my MySQL query for the insert:
`INSERT INTO User SET
            name = '[USER NAME OK]',
            login = '[LOGIN OK]',
            ssoLogin = NULL,
            email = '[EMAIL OK]',
            notes = NULL,
            userGroupId = 0,
            userProfileId = 0,
            mPass = NULL,
            mKey = NULL,
            lastUpdateMPass = 0,
            isAdminApp = 0,
            isAdminAcc = 0,
            isDisabled = 0,
            isChangePass = 0,
            isLdap = 1,
            pass = '[PASSWORD OK ENCRYPTED]',
            hashSalt = ''`

**Comment by nuxsmin** [comment]
Hello, these issues should have been fixed in the latest commits. Please let me know if so.

Regards

**Comment by Fizard** [comment]
Also, after I did this commit, when I try to connect with a local user "admin" it is always asking my "Last password" but I didn't change it. So when I put the same password it says "Senha Mestre Incorreta" and I have to input my master password again. But when I logout it happens again. I also tested the new created LDAP user and it is the same.
Just to help, my Syspass version after copying the commit is: 3.0-beta (300.18052901)
This is what it appears at log:
```
2018-05-29 12:26:02 - Loaded actions cache
2018-05-29 12:26:02 - No RSA encrypted data from request
2018-05-29 12:26:02 - Erro ao localizar o usuário no LDAP
2018-05-29 12:26:02 - #0 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapBase.php(328): SP\Providers\Auth\Ldap\LdapBase->getUserAttributes()
#1 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapBase.php(299): SP\Providers\Auth\Ldap\LdapBase->getAttributes()
#2 /var/www/html/syspass/lib/SP/Providers/Auth/AuthProvider.php(110): SP\Providers\Auth\Ldap\LdapBase->authenticate(Object(SP\DataModel\UserLoginData))
#3 /var/www/html/syspass/lib/SP/Providers/Auth/AuthProvider.php(78): SP\Providers\Auth\AuthProvider->authLdap()
#4 /var/www/html/syspass/lib/SP/Services/Auth/LoginService.php(154): SP\Providers\Auth\AuthProvider->doAuth(Object(SP\DataModel\UserLoginData))
#5 /var/www/html/syspass/app/modules/web/Controllers/LoginController.php(63): SP\Services\Auth\LoginService->doLogin()
#6 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#7 /var/www/html/syspass/lib/SP/Bootstrap.php(239): call_user_func_array(Array, Array)
#8 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/html/syspass/lib/SP/Bootstrap.php(446): Klein\Klein->dispatch()
#12 /var/www/html/syspass/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#13 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#14 {main}
2018-05-29 12:26:02 - No RSA encrypted data from request
2018-05-29 12:26:02 - No RSA encrypted data from request
2018-05-29 12:26:02 - Invalid header.
2018-05-29 12:26:02 - Invalid header.
2018-05-29 12:26:02 - A sua senha anterior é necessária
2018-05-29 12:26:02 - #0 /var/www/html/syspass/lib/SP/Services/Auth/LoginService.php(178): SP\Services\Auth\LoginService->loadMasterPass()
#1 /var/www/html/syspass/app/modules/web/Controllers/LoginController.php(63): SP\Services\Auth\LoginService->doLogin()
#2 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#3 /var/www/html/syspass/lib/SP/Bootstrap.php(239): call_user_func_array(Array, Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/syspass/lib/SP/Bootstrap.php(446): Klein\Klein->dispatch()
#8 /var/www/html/syspass/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#9 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#10 {main}
```

**Comment by Fizard** [comment]
Perfect @nuxsmin. Now this LDAP seems to be working fine. Tested saving the LDAP configurations too and its all right. Thank you very much!

**Comment by rafaeldomingos** [comment]
Good afternoon.
I am trying to use syspass with Zimbra's ldap ..
But I can't get it to work. After changing the Bindpass path directly in the file: lib / SP / Providers / Auth / Ldap / LdapConnection.php
I can even list via WEBGUI but login does not work.
