### ISSUE TITLE
Error in local user with ldap configured

### ISSUE THREAD

**Issue by lcuervott** [nuxsmin/sysPass#929]
If you have ldap configured, but it's unable to conect to this ldap server, and try to use the local admin user to login, the attached screen is shown.
![error_login](https://user-images.githubusercontent.com/24292046/39572366-30612578-4ecf-11e8-9d1d-c9c798799192.png)

**Comment by nuxsmin** [comment]
Hi @lcuervott !

I'm quite busy on these weeks, but I'll take a look to this issues and others to get it fixed.

Thanks for the feedback and testing!

Kind regards

PS: sorry for not replying the email..

**Comment by lcuervott** [comment]
@nuxsmin No problem. I've been busy too with an office moving, so take your time.

Thanks

**Comment by nuxsmin** [comment]
Hello @lcuervott , is there any error logged in `syspass.log` file (within `config` directory)?.

Regards.

**Comment by lcuervott** [comment]
Yes,

2018-05-29 13:18:37 - ------------
2018-05-29 13:18:37 - Boostrap:web
2018-05-29 13:18:37 - initializeCommon
2018-05-29 13:18:37 - SP\Modules\Web\Init::initialize
2018-05-29 13:18:37 - Loaded icons cache
2018-05-29 13:18:37 - Attach: SP\Providers\Log\LogHandler
2018-05-29 13:18:37 - Attach: SP\Providers\Notification\NotificationHandler
2018-05-29 13:18:37 - Routing call: SP\Modules\Web\Controllers\LoginController::loginAction::Array
(
)

2018-05-29 13:18:37 - Loaded actions cache
2018-05-29 13:18:37 - No es posible conectar con el servidor de LDAP
2018-05-29 13:18:37 - #0 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapStd.php(139): SP\Providers\Auth\Ldap\LdapBase->connect()
#1 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapBase.php(136): SP\Providers\Auth\Ldap\LdapStd->connect()
#2 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapBase.php(298): SP\Providers\Auth\Ldap\LdapBase->connectAndBind()
#3 /var/www/html/syspass/lib/SP/Providers/Auth/AuthProvider.php(110): SP\Providers\Auth\Ldap\LdapBase->authenticate(Object(SP\DataModel\UserLoginData))
#4 /var/www/html/syspass/lib/SP/Providers/Auth/AuthProvider.php(78): SP\Providers\Auth\AuthProvider->authLdap()
#5 /var/www/html/syspass/lib/SP/Services/Auth/LoginService.php(154): SP\Providers\Auth\AuthProvider->doAuth(Object(SP\DataModel\UserLoginData))
#6 /var/www/html/syspass/app/modules/web/Controllers/LoginController.php(63): SP\Services\Auth\LoginService->doLogin()
#7 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#8 /var/www/html/syspass/lib/SP/Bootstrap.php(239): call_user_func_array(Array, Array)
#9 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#12 /var/www/html/syspass/lib/SP/Bootstrap.php(446): Klein\Klein->dispatch()
#13 /var/www/html/syspass/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#14 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#15 {main}
2018-05-29 13:18:38 - No RSA encrypted data from request
2018-05-29 13:18:38 - No RSA encrypted data from request

**Comment by lcuervott** [comment]
Seems that with ldap enabled I can't be able to use the local admin account :(

**Comment by lcuervott** [comment]
With ldap disabled this is the log:

2018-05-29 13:17:45 - Loaded actions cache
2018-05-29 13:17:45 - Loaded accounts color cache
2018-05-29 13:17:45 - Account ACL HIT
2018-05-29 13:17:45 - Account ACL HIT
2018-05-29 13:17:45 - Account ACL HIT
2018-05-29 13:17:45 - Account ACL HIT
2018-05-29 13:17:45 - Account ACL HIT
2018-05-29 13:17:45 - Account ACL HIT
2018-05-29 13:17:45 - Account ACL HIT
2018-05-29 13:17:45 - Account ACL HIT
2018-05-29 13:17:45 - Account ACL HIT
2018-05-29 13:17:45 - Account ACL HIT
2018-05-29 13:17:45 - Account ACL HIT
2018-05-29 13:17:45 - Account ACL HIT

**Comment by nuxsmin** [comment]
@lcuervott I've just pushed a commit that solves an issue with the encryption process (it was decrypting the key twice).

Which is the URL format used for the LDAP server?, is it set correctly in the `config.xml` file?

Regards

**Comment by lcuervott** [comment]
With your last commit the local user login with ldap enables is working :+1: 

This is the data stored in the ldap section of config.xml (private data removed):

  <ldapAds>0</ldapAds>
  <ldapBase>dc=server,dc=local,dc=lan</ldapBase>
  <ldapBindPass>password</ldapBindPass>
  <ldapBindUser>uid=admin,cn=users,cn=accounts,dc=server,dc=local,dc=lan</ldapBindUser>
  <ldapDefaultGroup>2</ldapDefaultGroup>
  <ldapDefaultProfile>2</ldapDefaultProfile>
  <ldapEnabled>1</ldapEnabled>
  <ldapGroup>cn=ipausers,cn=groups,cn=accounts,dc=server,dc=local,dc=lan</ldapGroup>
  <ldapProxyUser></ldapProxyUser>
  <ldapServer>ldap://server</ldapServer>
  <ldapUserattr></ldapUserattr>

All values are correctly stored, but the port is not. I mean.. if I write ldap://server:389 it store ldap://server only.

I don't know if it uses 389 by default, but with this configuration ldap is not working. This is the log:

2018-05-29 16:05:52 - Loaded actions cache
2018-05-29 16:05:57 - ------------
2018-05-29 16:05:57 - Boostrap:web
2018-05-29 16:05:57 - initializeCommon
2018-05-29 16:05:57 - SP\Modules\Web\Init::initialize
2018-05-29 16:05:57 - Loaded icons cache
2018-05-29 16:05:57 - Attach: SP\Providers\Log\LogHandler
2018-05-29 16:05:57 - Attach: SP\Providers\Notification\NotificationHandler
2018-05-29 16:05:57 - Routing call: SP\Modules\Web\Controllers\ConfigLdapController::checkAction::Array
(
)

2018-05-29 16:05:57 - Loaded actions cache
2018-05-29 16:05:57 - No RSA encrypted data from request
2018-05-29 16:05:57 - Error al conectar (BIND)
2018-05-29 16:05:57 - #0 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapBase.php(137): SP\Providers\Auth\Ldap\LdapBase->bind()
#1 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapBase.php(119): SP\Providers\Auth\Ldap\LdapBase->connectAndBind()
#2 /var/www/html/syspass/lib/SP/Services/Ldap/LdapCheckService.php(57): SP\Providers\Auth\Ldap\LdapBase->checkConnection()
#3 /var/www/html/syspass/app/modules/web/Controllers/ConfigLdapController.php(141): SP\Services\Ldap\LdapCheckService->checkConnection(Object(SP\Providers\Auth\Ldap\LdapParams))
#4 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#5 /var/www/html/syspass/lib/SP/Bootstrap.php(239): call_user_func_array(Array, Array)
#6 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/syspass/lib/SP/Bootstrap.php(446): Klein\Klein->dispatch()
#10 /var/www/html/syspass/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#11 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#12 {main}

**Comment by lcuervott** [comment]
I detected the problem...

This is what I get in the ldap logs:

[29/May/2018:16:55:59 +0200] conn=263 fd=151 slot=151 connection from 172.16.70.204 to 172.16.70.202
[29/May/2018:16:55:59 +0200] conn=263 op=0 BIND dn="uid=admin,cn=users,cn=accounts,dc=server,dc=local,dc=lan" method=128 version=3
[29/May/2018:16:55:59 +0200] conn=263 op=0 RESULT err=0 tag=97 nentries=0 etime=0 dn="uid=admin,cn=users,cn=accounts,dc=server,dc=local,dc=lan"
[29/May/2018:16:55:59 +0200] conn=263 op=1 SRCH base="cn=users,cn=accounts,dc=server,dc=local,dc=lan" scope=2 filter="(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))" **attrs="distinguishedName"**
[29/May/2018:16:55:59 +0200] conn=263 op=1 RESULT err=0 tag=101 nentries=5 etime=0 notes=P pr_idx=0
[29/May/2018:16:55:59 +0200] conn=263 op=2 UNBIND
[29/May/2018:16:55:59 +0200] conn=263 op=2 fd=151 closed - U1

The problem is that my user is using **uid** and not **distinguishedName**

If in the lower part (Import) I set login=uid and name=cn it detects the correct users, but when I try to import it search again for distinguishedName and fails.

**Comment by Fizard** [comment]
@lcuervott, You use LDAP and not Active Directory, right? Did you select the "Active Directory" option? If you did try "unselecting" it. 
![image](https://user-images.githubusercontent.com/7660657/40667879-8e307f22-6339-11e8-8bc3-53d11bae78ec.png)

**Comment by lcuervott** [comment]
Yes, tested with AD enabled and disabled. 

There is some problem with the recovery of info in the app. If I press the refresh button in the lower side of the page it shows the users, if I press the one above or the import button it gives me errors (unable to bind), but the logs in the ldap are always the same and it's getting 5 users. 

LDAP logs when pressing the lower sync button:

[29/May/2018:17:39:01 +0200] conn=292 fd=151 slot=151 connection from 172.16.70.204 to 172.16.70.202
[29/May/2018:17:39:01 +0200] conn=292 op=0 BIND dn="uid=admin,cn=users,cn=accounts,dc=server,dc=local,dc=lan" method=128 version=3
[29/May/2018:17:39:01 +0200] conn=292 op=0 RESULT err=0 tag=97 nentries=0 etime=0 dn="uid=admin,cn=users,cn=accounts,dc=server,dc=local,dc=lan"
[29/May/2018:17:39:01 +0200] conn=292 op=1 SRCH base="cn=users,cn=accounts,dc=server,dc=local,dc=lan" scope=2 filter="(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))" attrs="distinguishedName"
[29/May/2018:17:39:01 +0200] conn=292 op=1 RESULT err=0 tag=101 nentries=5 etime=0 notes=P pr_idx=0
[29/May/2018:17:39:01 +0200] conn=292 op=2 UNBIND
[29/May/2018:17:39:01 +0200] conn=292 op=2 fd=151 closed - U1


LDAP log when pressing the above sync button:

[29/May/2018:17:39:15 +0200] conn=293 op=0 BIND dn="uid=admin,cn=users,cn=accounts,dc=server,dc=local,dc=lan" method=128 version=3
[29/May/2018:17:39:15 +0200] conn=293 op=0 RESULT err=0 tag=97 nentries=0 etime=0 dn="uid=admin,cn=users,cn=accounts,dc=server,dc=local,dc=lan"
[29/May/2018:17:39:15 +0200] conn=293 op=1 SRCH base="cn=users,cn=accounts,dc=server,dc=local,dc=lan" scope=2 filter="(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))" attrs="distinguishedName"
[29/May/2018:17:39:15 +0200] conn=293 op=1 RESULT err=0 tag=101 nentries=5 etime=0 notes=P pr_idx=0
[29/May/2018:17:39:15 +0200] conn=293 op=2 SRCH base="cn=users,cn=accounts,dc=server,dc=local,dc=lan" scope=2 filter="(|(objectClass=groupOfNames)(objectClass=groupOfUniqueNames)(objectClass=group))" attrs="distinguishedName"
[29/May/2018:17:39:15 +0200] conn=293 op=2 RESULT err=0 tag=101 nentries=0 etime=0 notes=P pr_idx=0
[29/May/2018:17:39:15 +0200] conn=293 op=3 UNBIND

It's searching for group too?

**Comment by nuxsmin** [comment]
@lcuervott that sounds good! I'm glad it's working fine now.

Regards.
