### ISSUE TITLE
Delete Selected Problem in V3

### ISSUE THREAD

**Issue by Fizard** [nuxsmin/sysPass#958]
Hi, I'm trying to use the function DELETE SELECTED from some "Items and Customization" tabs, but it is giving me an error while using it. This is the error trying to delete from "Items and Customization" -> "Accounts (H)":
```
×
There was an error
SyntaxError: Unexpected token O in JSON at position 0parsererror

2018-06-06 20:18:09 - ------------
2018-06-06 20:18:09 - Boostrap:web
2018-06-06 20:18:09 - SP\Modules\Web\Controllers\AccountHistoryManagerController::deleteundefinedAction
2018-06-06 20:18:09 - Oops, it looks like this content doesn't exist...
2018-06-06 20:18:09 - #0 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#1 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#2 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#3 /var/www/html/syspass/lib/SP/Bootstrap.php(446): Klein\Klein->dispatch()
#4 /var/www/html/syspass/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#5 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#6 {main}
```
I tried also in "Categories" with the same error, probably it's something in the Function.
Just to be sure, when I delete it clicking on the "Remove Account" button of each account it deletes normally.

**Comment by nuxsmin** [comment]
@Fizard some JavaScript weird behaviour...it works now.

Thanks for the feedback!
