### ISSUE TITLE
Los permisos del directorio "/config" son incorrectos in SysPass v3

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#985]
Hello,

I just installed sysPass v3 beta from latest git, using a git clone and composer update.
When trying to access to sysPass, I get the upper message.

php logs show:
```
[04-Jul-2018 19:07:18 Europe/Paris] Los permisos del directorio "/config" son incorrectos
[04-Jul-2018 19:07:18 Europe/Paris] #0 /home/www/beta.syspass.local/ftp/www/lib/SP/Config/Config.php(82): SP\Config\Config->initialize()
#1 [internal function]: SP\Config\Config->__construct(Object(SP\Storage\XmlHandler), Object(SP\Core\Context\SessionContext), Object(DI\Container))
#2 /home/www/beta.syspass.local/ftp/www/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(138): ReflectionClass->newInstanceArgs(Array)
#3 /home/www/beta.syspass.local/ftp/www/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(70): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#4 /home/www/beta.syspass.local/ftp/www/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php(58): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#5 /home/www/beta.syspass.local/ftp/www/vendor/php-di/php-di/src/DI/Container.php(303): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#6 /home/www/beta.syspass.local/ftp/www/vendor/php-di/php-di/src/DI/Container.php(131): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#7 /home/www/beta.syspass.local/ftp/www/lib/SP/Bootstrap.php(128): DI\Container->get('SP\\Config\\Confi...')
#8 /home/www/beta.syspass.local/ftp/www/lib/SP/Bootstrap.php(438): SP\Bootstrap->__construct(Object(DI\Container))
#9 /home/www/beta.syspass.local/ftp/www/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#10 /home/www/beta.syspass.local/ftp/www/index.php(28): require('/home/www/beta....')
#11 {main}
```

Looking at my config directory, it doesn't seem so bad:
```
ls -alh /home/www/beta.syspass.local/ftp/www | grep config
drwxr-x---.  2 apache apache   90  4 juil. 18:29 config
```

I tried to relax my php config a bit (allowed chmod and chown functions among others), doesn't work better.
SELinux has been disabled too.

Using CentOS 7 x64 1804 with latest httpd and rh-php70

Any chance that this message is a bit too generic to explain what actually happens ?

Best regards.

**Comment by nuxsmin** [comment]
Hello @deajan 

The new config dir is not being displayed on the message (translations would break if I change it). You need to set the permissions on `/app/config` dir instead.

Best regards

**Comment by nuxsmin** [comment]
Although the translation isn't working well on this view...

**Comment by deajan** [comment]
Okay thanks. Maybe a quick documentation note about this would be good :)
After copying 2.1 config.xml and pem files to the new syspass 3 install, I tried to update the database.
Having copied my current 2.1 database to a new one with 
```
CREATE DATABASE syspass3beta;
mysqldump syspass | mysql syspass3beta
GRANT ALL PRIVILEGES ON syspass3beta.* TO syspassuser@localhost;
FLUSH PRIVILEGES;
```

After updading config.xml database, I tried to ugprade and got the following

```
2018-07-05 10:36:43 - ------------
2018-07-05 10:36:43 - Boostrap:web
2018-07-05 10:36:43 - initializeCommon
2018-07-05 10:36:43 - SP\Modules\Web\Init::initialize
2018-07-05 10:36:43 - Loaded icons cache
2018-07-05 10:36:43 - Session closed
2018-07-05 10:36:43 - Routing call: SP\Modules\Web\Controllers\UpgradeController::upgradeAction::Array
(
)

2018-07-05 10:36:43 - Loaded actions cache
2018-07-05 10:36:43 - SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
2018-07-05 10:36:43 - #0 /home/www/beta.syspass.local/ftp/www/lib/SP/Storage/Database/Database.php(246): PDOStatement->execute()
#1 /home/www/beta.syspass.local/ftp/www/lib/SP/Storage/Database/Database.php(179): SP\Storage\Database\Database->prepareQueryData(Object(SP\Storage\Database\QueryData))
#2 /home/www/beta.syspass.local/ftp/www/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(174): SP\Storage\Database\Database->doQuery(Object(SP\Storage\Database\QueryData))
#3 /home/www/beta.syspass.local/ftp/www/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(93): SP\Services\Upgrade\UpgradeDatabaseService->applyUpgrade('300.18010101')
#4 /home/www/beta.syspass.local/ftp/www/app/modules/web/Controllers/UpgradeController.php(76): SP\Services\Upgrade\UpgradeDatabaseService->upgrade('0.0', Object(SP\Config\ConfigData))
#5 [internal function]: SP\Modules\Web\Controllers\UpgradeController->upgradeAction()
#6 /home/www/beta.syspass.local/ftp/www/lib/SP/Bootstrap.php(238): call_user_func_array(Array, Array)
#7 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /home/www/beta.syspass.local/ftp/www/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /home/www/beta.syspass.local/ftp/www/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#10 /home/www/beta.syspass.local/ftp/www/lib/SP/Bootstrap.php(445): Klein\Klein->dispatch()
#11 /home/www/beta.syspass.local/ftp/www/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#12 /home/www/beta.syspass.local/ftp/www/index.php(28): require('/home/www/beta....')
#13 {main}
2018-07-05 10:36:43 - SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
2018-07-05 10:36:43 - #0 /home/www/beta.syspass.local/ftp/www/lib/SP/Storage/Database/Database.php(179): SP\Storage\Database\Database->prepareQueryData(Object(SP\Storage\Database\QueryData))
#1 /home/www/beta.syspass.local/ftp/www/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(174): SP\Storage\Database\Database->doQuery(Object(SP\Storage\Database\QueryData))
#2 /home/www/beta.syspass.local/ftp/www/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(93): SP\Services\Upgrade\UpgradeDatabaseService->applyUpgrade('300.18010101')
#3 /home/www/beta.syspass.local/ftp/www/app/modules/web/Controllers/UpgradeController.php(76): SP\Services\Upgrade\UpgradeDatabaseService->upgrade('0.0', Object(SP\Config\ConfigData))
#4 [internal function]: SP\Modules\Web\Controllers\UpgradeController->upgradeAction()
#5 /home/www/beta.syspass.local/ftp/www/lib/SP/Bootstrap.php(238): call_user_func_array(Array, Array)
#6 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /home/www/beta.syspass.local/ftp/www/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /home/www/beta.syspass.local/ftp/www/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#9 /home/www/beta.syspass.local/ftp/www/lib/SP/Bootstrap.php(445): Klein\Klein->dispatch()
#10 /home/www/beta.syspass.local/ftp/www/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#11 /home/www/beta.syspass.local/ftp/www/index.php(28): require('/home/www/beta....')
#12 {main}
2018-07-05 10:36:43 - SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
2018-07-05 10:36:43 - #0 /home/www/beta.syspass.local/ftp/www/lib/SP/Storage/Database/Database.php(246): PDOStatement->execute()
#1 /home/www/beta.syspass.local/ftp/www/lib/SP/Storage/Database/Database.php(179): SP\Storage\Database\Database->prepareQueryData(Object(SP\Storage\Database\QueryData))
#2 /home/www/beta.syspass.local/ftp/www/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(174): SP\Storage\Database\Database->doQuery(Object(SP\Storage\Database\QueryData))
#3 /home/www/beta.syspass.local/ftp/www/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(93): SP\Services\Upgrade\UpgradeDatabaseService->applyUpgrade('300.18010101')
#4 /home/www/beta.syspass.local/ftp/www/app/modules/web/Controllers/UpgradeController.php(76): SP\Services\Upgrade\UpgradeDatabaseService->upgrade('0.0', Object(SP\Config\ConfigData))
#5 [internal function]: SP\Modules\Web\Controllers\UpgradeController->upgradeAction()
#6 /home/www/beta.syspass.local/ftp/www/lib/SP/Bootstrap.php(238): call_user_func_array(Array, Array)
#7 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /home/www/beta.syspass.local/ftp/www/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /home/www/beta.syspass.local/ftp/www/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#10 /home/www/beta.syspass.local/ftp/www/lib/SP/Bootstrap.php(445): Klein\Klein->dispatch()
#11 /home/www/beta.syspass.local/ftp/www/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#12 /home/www/beta.syspass.local/ftp/www/index.php(28): require('/home/www/beta....')
#13 {main}
2018-07-05 10:36:43 - SQL: DROP PROCEDURE IF EXISTS drop_primary
2018-07-05 10:36:43 - Erreur pendant la mise à jour de la base de données
2018-07-05 10:36:43 - #0 /home/www/beta.syspass.local/ftp/www/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(93): SP\Services\Upgrade\UpgradeDatabaseService->applyUpgrade('300.18010101')
#1 /home/www/beta.syspass.local/ftp/www/app/modules/web/Controllers/UpgradeController.php(76): SP\Services\Upgrade\UpgradeDatabaseService->upgrade('0.0', Object(SP\Config\ConfigData))
#2 [internal function]: SP\Modules\Web\Controllers\UpgradeController->upgradeAction()
#3 /home/www/beta.syspass.local/ftp/www/lib/SP/Bootstrap.php(238): call_user_func_array(Array, Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /home/www/beta.syspass.local/ftp/www/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /home/www/beta.syspass.local/ftp/www/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#7 /home/www/beta.syspass.local/ftp/www/lib/SP/Bootstrap.php(445): Klein\Klein->dispatch()
#8 /home/www/beta.syspass.local/ftp/www/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#9 /home/www/beta.syspass.local/ftp/www/index.php(28): require('/home/www/beta....')
#10 {main}
```

Having searched around, this seems to be a PDO issue depending on the programming style used.
Any hints ?

**Comment by nuxsmin** [comment]
It could be an odd behavior of MySQL driver: https://stackoverflow.com/questions/22803938/what-is-causing-pdo-error-cannot-execute-queries-while-other-unbuffered-queries

Could you check out the driver installed?. I could modify the code but some tests will be needed as it could raise some odd behaviors.

Thanks for the feedback!

**Comment by deajan** [comment]
I have `rh-php70-php-mysqlnd-7.0.27-1.el7.x86_64` pdo mysql driver installed.

Here's my full config
```

System | Linux fmiflxa00p.fmi-lyon.local 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64
-- | --
Build Date | Apr 4 2018 13:50:08
Server API | FPM/FastCGI
Virtual Directory Support | disabled
Configuration File (php.ini) Path | /etc/opt/rh/rh-php70
Loaded Configuration File | /etc/opt/rh/rh-php70/php.ini
Scan this dir for additional .ini files | /etc/opt/rh/rh-php70/php.d
Additional .ini files parsed | /etc/opt/rh/rh-php70/php.d/10-opcache.ini, /etc/opt/rh/rh-php70/php.d/20-bz2.ini, /etc/opt/rh/rh-php70/php.d/20-calendar.ini, /etc/opt/rh/rh-php70/php.d/20-ctype.ini, /etc/opt/rh/rh-php70/php.d/20-curl.ini, /etc/opt/rh/rh-php70/php.d/20-dom.ini, /etc/opt/rh/rh-php70/php.d/20-exif.ini, /etc/opt/rh/rh-php70/php.d/20-fileinfo.ini, /etc/opt/rh/rh-php70/php.d/20-ftp.ini, /etc/opt/rh/rh-php70/php.d/20-gd.ini, /etc/opt/rh/rh-php70/php.d/20-gettext.ini, /etc/opt/rh/rh-php70/php.d/20-iconv.ini, /etc/opt/rh/rh-php70/php.d/20-json.ini, /etc/opt/rh/rh-php70/php.d/20-ldap.ini, /etc/opt/rh/rh-php70/php.d/20-mbstring.ini, /etc/opt/rh/rh-php70/php.d/20-mcrypt.ini, /etc/opt/rh/rh-php70/php.d/20-mysqlnd.ini, /etc/opt/rh/rh-php70/php.d/20-pdo.ini, /etc/opt/rh/rh-php70/php.d/20-phar.ini, /etc/opt/rh/rh-php70/php.d/20-simplexml.ini, /etc/opt/rh/rh-php70/php.d/20-sockets.ini, /etc/opt/rh/rh-php70/php.d/20-sqlite3.ini, /etc/opt/rh/rh-php70/php.d/20-tokenizer.ini, /etc/opt/rh/rh-php70/php.d/20-xml.ini, /etc/opt/rh/rh-php70/php.d/20-xmlwriter.ini, /etc/opt/rh/rh-php70/php.d/20-xsl.ini, /etc/opt/rh/rh-php70/php.d/20-zip.ini, /etc/opt/rh/rh-php70/php.d/30-mysqli.ini, /etc/opt/rh/rh-php70/php.d/30-pdo_mysql.ini, /etc/opt/rh/rh-php70/php.d/30-pdo_sqlite.ini, /etc/opt/rh/rh-php70/php.d/30-wddx.ini, /etc/opt/rh/rh-php70/php.d/30-xmlreader.ini
PHP API | 20151012
PHP Extension | 20151012
Zend Extension | 320151012
Zend Extension Build | API320151012,NTS
PHP Extension Build | API20151012,NTS
Debug Build | no
Thread Safety | disabled
Zend Signal Handling | disabled
Zend Memory Manager | enabled
Zend Multibyte Support | provided by mbstring
IPv6 Support | enabled
DTrace Support | available, disabled
Registered PHP Streams | https, ftps, compress.zlib, php, file, glob, data, http, ftp, compress.bzip2, phar, zip
Registered Stream Socket Transports | tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2
Registered Stream Filters | zlib.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, bzip2.*, convert.iconv.*, mcrypt.*, mdecrypt.*
```

PDO mysql driver is:
```
Version | mysqlnd 5.0.12-dev - 20150407$
-- | --
Compression | supported
core SSL | supported
extended SSL | supported
Command buffer size | 4096
Read buffer size | 32768
Read timeout | 31536000
Collecting statistics | Yes
Collecting memory statistics | No
Tracing | n/a
Loaded plugins | mysqlnd,debug_trace,auth_plugin_mysql_native_password,auth_plugin_mysql_clear_password,auth_plugin_sha256_password
API Extensions | mysqli,pdo_mysql
```

Willing to to some tests if it might help.

**Comment by deajan** [comment]
Using CentOS SCL, I may also switch between various PHP versions if needed.

**Comment by nuxsmin** [comment]
@deajan no worries about testing, I told that because it would take some time to complete the tests. In the meantime, could you execute the SQL script related to this version?. It could be useful to get some feedback about the database upgrade. Be aware that after executing the script the app will still complaint about the missing upgrade, since it looks for the correct database version in config table.

Regards

**Comment by deajan** [comment]
You mean `mysql --database syspass < 30018010101.sql` ?

**Comment by nuxsmin** [comment]
@deajan right, it should upgrade your database, but this would be a simple test while I find out the hack to this issue.

**Comment by deajan** [comment]
Updated the database manually, worked without errors.
Btw, I tried to cheat here with `UPDATE Config set value = '300.18010101' WHERE parameter = 'version';` in order to be able to play with sysPass v3, but it still asks me to do the upgrade.

**Comment by nuxsmin** [comment]
Hmm, I'm thinking about the upgrade and it will need additional steps like converting custom fields, so the upgrade process (application only) need to be performed.

**Comment by deajan** [comment]
I've updated the corresponding entry in config.xml, still got sysPass to ask for upgrade, so I did. Seems to work now.
Leaving this open for the update process.

**Comment by nuxsmin** [comment]
Fine!
