### ISSUE TITLE
Upgrade from SysPass v2.1.14 to v3 beta truncates ldap server

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#987]
Some minor quicks I found using the latest beta:

After updating to sysPass v3, ldap server config got truncated.

In v2 I have `ldap://xxxxxxxxxx.yyy-zzzz.local` (I kept real number of characters here)
In v3 I now have `ldap://xxxxxxxxxx.yyy`

When updating the ldap server to the initial value, it gets truncated again after saving.

Also, when copying LDAP bind password using the eye icon, it litterally copies `***` into the clipboard :)

**Comment by deajan** [comment]
Proposed fix works.
I still cannot bind with v3, maybe something todo with the password being transformed into '***'.

Here are the logs (which IMHO don't look very helpfull)
```
2018-07-10 09:38:18 - Loaded actions cache
2018-07-10 09:38:23 - ------------
2018-07-10 09:38:23 - Boostrap:web
2018-07-10 09:38:23 - initializeCommon
2018-07-10 09:38:23 - SP\Modules\Web\Init::initialize
2018-07-10 09:38:23 - Loaded icons cache
2018-07-10 09:38:23 - Attach: SP\Providers\Log\DatabaseLogHandler
2018-07-10 09:38:23 - Attach: SP\Providers\Mail\MailHandler
2018-07-10 09:38:23 - Attach: SP\Providers\Notification\NotificationHandler
2018-07-10 09:38:23 - Routing call: SP\Modules\Web\Controllers\ConfigLdapController::checkAction::Array
(
)

2018-07-10 09:38:23 - Loaded actions cache
2018-07-10 09:38:23 - No RSA encrypted data from request
2018-07-10 09:38:23 - Erreur de connexion (BIND)
2018-07-10 09:38:23 - #0 /home/www/beta.syspass.local/ftp/www/lib/SP/Providers/Auth/Ldap/LdapBase.php(137): SP\Providers\Auth\Ldap\LdapBase->bind()
#1 /home/www/beta.syspass.local/ftp/www/lib/SP/Providers/Auth/Ldap/LdapBase.php(119): SP\Providers\Auth\Ldap\LdapBase->connectAndBind()
#2 /home/www/beta.syspass.local/ftp/www/lib/SP/Services/Ldap/LdapCheckService.php(57): SP\Providers\Auth\Ldap\LdapBase->checkConnection()
#3 /home/www/beta.syspass.local/ftp/www/app/modules/web/Controllers/ConfigLdapController.php(141): SP\Services\Ldap\LdapCheckService->checkConnection(Object(SP\Providers\Auth\Ldap\LdapParams))
#4 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#5 /home/www/beta.syspass.local/ftp/www/lib/SP/Bootstrap.php(238): call_user_func_array(Array, Array)
#6 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /home/www/beta.syspass.local/ftp/www/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /home/www/beta.syspass.local/ftp/www/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#9 /home/www/beta.syspass.local/ftp/www/lib/SP/Bootstrap.php(445): Klein\Klein->dispatch()
#10 /home/www/beta.syspass.local/ftp/www/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#11 /home/www/beta.syspass.local/ftp/www/index.php(28): require('/home/www/beta....')
#12 {main}
```

**Comment by deajan** [comment]
Oh, the latter is a duplicate of #959 so I'll close this.

**Comment by nuxsmin** [comment]
The `***` are there because security reasons, so it won't successfully check the connection, so you need to provide the correct credentials instead. This behaviour is only for checking purposes, since the real LDAP credentials are stored in `config.xml` file.

Regards
