### ISSUE TITLE
[NOT A BUG] curl error on connection with v3

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#988]
Hello,

When logging in into v3, I get the following error:

Shown in UI: 
`SyntaxError: Unexpected token G in JSON at position 0parsererror`

Logs:

```
2018-07-10 09:41:21 - Loaded actions cache
2018-07-10 09:41:21 - GuzzleHttp requires cURL, the allow_url_fopen ini setting, or a custom HTTP handler.
2018-07-10 09:41:21 - #0 /home/www/beta.syspass.local/ftp/www/vendor/guzzlehttp/guzzle/src/HandlerStack.php(40): GuzzleHttp\choose_handler()
#1 /home/www/beta.syspass.local/ftp/www/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create()
#2 [internal function]: GuzzleHttp\Client->__construct(Array)
#3 /home/www/beta.syspass.local/ftp/www/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(138): ReflectionClass->newInstanceArgs(Array)
#4 /home/www/beta.syspass.local/ftp/www/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(70): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#5 /home/www/beta.syspass.local/ftp/www/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php(58): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#6 /home/www/beta.syspass.local/ftp/www/vendor/php-di/php-di/src/DI/Container.php(303): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#7 /home/www/beta.syspass.local/ftp/www/vendor/php-di/php-di/src/DI/Container.php(131): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#8 /home/www/beta.syspass.local/ftp/www/app/modules/web/Controllers/StatusController.php(95): DI\Container->get('GuzzleHttp\\Clie...')
#9 [internal function]: SP\Modules\Web\Controllers\StatusController->checkNoticesAction()
#10 /home/www/beta.syspass.local/ftp/www/lib/SP/Bootstrap.php(238): call_user_func_array(Array, Array)
#11 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#12 /home/www/beta.syspass.local/ftp/www/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#13 /home/www/beta.syspass.local/ftp/www/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#14 /home/www/beta.syspass.local/ftp/www/lib/SP/Bootstrap.php(445): Klein\Klein->dispatch()
#15 /home/www/beta.syspass.local/ftp/www/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#16 /home/www/beta.syspass.local/ftp/www/index.php(28): require('/home/www/beta....')
#17 {main}
```

After thinking around, I remembered that I disabled a lot of functions for security reasons, eg;
```
php_admin_value[disable_functions]=exec,passthru,shell_exec,system,proc_open,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source,chmod,chown
```

Is curl really needed ?

Thanks.

**Comment by nuxsmin** [comment]
Hello,

it would be needed for checking sysPass updates or notices (through GitHub API), but you can safely disable them. 

Regards

**Comment by deajan** [comment]
Maybe for v3+ the JSON message could become a "no curl found" message :)
Anyway, thanks four your answer.

**Comment by nuxsmin** [comment]
I agree with you, modules checking are being improved in next release.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Added in latest commit ;)
