### ISSUE TITLE
v3 Class 'Symfony\Component\Debug\Debug' not found

### ISSUE THREAD

**Issue by GGOUSSEAUD** [nuxsmin/sysPass#999]
**sysPass Version**
devel-3.0 218a481 * [FIX] Minor bugfixes

**Describe the bug**
"Class 'Symfony\Component\Debug\Debug' not found" is returned when JSON payload is expected.

**To Reproduce**
1. git pull the latest commit
2. Try this curl request on our server : 
```
curl -H 'Content-Type: application/json' -X POST -d '{"jsonrpc": "2.0","method":"account/search", "id" : "1", "params": {"authToken": "OUR API KEY", "text": "OUR ACCOUNT NAME"}}' https://server-sys.net/sysPass/api.php
```
3. Get error: 
```
Class 'Symfony\Component\Debug\Debug' not found
```
**Expected behavior**
Get our JSON payload.

**Event log**
php_err.log:
```
[02-Aug-2018 09:35:03 Europe/Paris] [DEBUG] [SP\Config\Config::initialize] Config loaded
[02-Aug-2018 09:35:03 Europe/Paris] [DEBUG] [SP\Bootstrap::run] ------------
[02-Aug-2018 09:35:03 Europe/Paris] [DEBUG] [SP\Bootstrap::run] Boostrap:api
[02-Aug-2018 09:35:03 Europe/Paris] [DEBUG] [SP\Bootstrap::initializeCommon] initializeCommon
[02-Aug-2018 09:35:03 Europe/Paris] [DEBUG] [SP\Bootstrap::SP{closure}] Routing error: Class 'Symfony\Component\Debug\Debug' not found
[02-Aug-2018 09:35:03 Europe/Paris] [DEBUG] [SP\Bootstrap::SP{closure}] Routing error: #0 /home/sites/docroot/sysPass/lib/SP/Bootstrap.php(250): SP\Bootstrap->initPHPVars()
#1 /home/sites/docroot/sysPass/lib/SP/Bootstrap.php(162): SP\Bootstrap->initializeCommon()
#2 [internal function]: SP\Bootstrap->SP{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#3 /home/sites/docroot/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#4 /home/sites/docroot/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#5 /home/sites/docroot/sysPass/lib/SP/Bootstrap.php(436): Klein\Klein->dispatch(Object(Klein\Request))
#6 /home/sites/docroot/sysPass/lib/Base.php(72): SP\Bootstrap::run(Object(DI\Container))
#7 /home/sites/docroot/sysPass/api.php(28): require('/home/hosting/d...')
```
access.log :
```
[02/Aug/2018:09:35:03 +0200] "POST /sysPass/api.php HTTP/1.1" 200 58 "-" "curl/7.47.0"
```
**Platform (please complete the following information):**
 - OS: [Debian]
 - OS Version 8
 - CLI

**Additional context**
We were still getting these empty responses from the server even though they were still reaching it as explained in https://github.com/nuxsmin/sysPass/issues/994#issuecomment-408407270. Then we git pulled and this happened.

**Comment by nuxsmin** [comment]
Please, run `php composer.phar update` since some dependencies have been added/updated.

**Comment by nuxsmin** [comment]
**Advice**, you would need to run the above command on every pull, since beta releases would either update or add dependencies between builds.

**Comment by GGOUSSEAUD** [comment]
This helped me for the missing component thanks!

**Comment by nuxsmin** [comment]
Great! Thanks for the feedback
